import { existsSync, readFileSync } from "node:fs"
import { is, getTableColumns, getTableName } from "drizzle-orm"
import { SQLiteTable, getTableConfig } from "drizzle-orm/sqlite-core"
import * as schema from "../../../src/db/schema"
import * as vocabularies from "../../../src/db/vocabularies-schema"
import { ACTION, GRANTS, RELATION } from "../../../src/domain/vocabularies"
import { BLOCKED, NOT_BUILT, declared } from "./action-coverage"
import { parse, sources, walk, type Node } from "./ast"

/** A reviewable home for each data structure, not a claim of field rendering. */
const SURFACES: Record<string, string[]> = {
  user: ["pages/profile.tsx", "pages/admin.tsx", "components/who-are-you.tsx"],
  event: ["pages/event.tsx", "components/event-settings.tsx"],
  team: ["pages/team.tsx", "pages/teams.tsx"],
  org: ["pages/org.tsx"], player: ["pages/player.tsx", "components/your-players.tsx"],
  venue: ["components/event-venues.tsx"], division: ["components/event-divisions.tsx"],
  orgMember: ["pages/org.tsx"], eventCoOrganizer: ["components/event-settings.tsx", "components/invitations.tsx"],
  game: ["components/schedule.tsx", "pages/live.tsx"], gameReferee: ["components/schedule.tsx"],
  playerGameStat: ["components/game-stats.tsx", "pages/player.tsx"],
  gameBroadcast: ["components/moq-video.tsx", "pages/live.tsx"],
  eventPlayer: ["components/event-players.tsx"], eventTeam: ["components/entries.tsx"],
  eventDivision: ["components/event-divisions.tsx"], eventVenue: ["components/event-venues.tsx"],
  eventSession: ["components/event-sessions.tsx"], sessionAttendance: ["components/event-sessions.tsx"],
  guardian: ["components/your-players.tsx"], playerTeam: ["pages/player.tsx", "pages/team.tsx"],
  teamCoach: ["pages/team.tsx"], subscription: ["components/follow.tsx", "components/following.tsx"],
  userNotificationChannel: ["pages/devices.tsx"], userNotificationPreference: ["components/notification-settings.tsx"],
}
const INTERNAL: Record<string, string> = {
  session: "Better Auth session lifecycle; credentials are never displayed. Sign-in/out and device ownership are the user journeys.",
  account: "Better Auth credential/provider bookkeeping, managed by authentication flows rather than a raw-table editor.",
  verification: "Expiring authentication challenges; showing their stored values would expose credentials.",
  notificationSent: "Delivery deduplication and scheduling bookkeeping; the user sees the delivered notification and preferences.",
}

const link = (path: string) => `[${path}](../${path})`
const cell = (value: string) => value.replaceAll("|", "\\|").replaceAll("\n", " ")

/** Stable, field-qualified inventory: adding a field changes the checked report. */
export function domainCoverage() {
  const problems: string[] = []
  const declarations = declared()
  const gates = new Map<string, Set<string>>()
  for (const file of sources("src/web")) walk(parse(file).program, (node) => {
    if (node.type !== "JSXOpeningElement" || !["Can", "PlatformCan"].includes(String((node.name as Node)?.name))) return
    const attr = (node.attributes as Node[]).find((a) => (a.name as Node)?.name === "action")
    const action = (attr?.value as Node)?.value
    if (typeof action !== "string") return
    const files = gates.get(action) ?? new Set<string>()
    files.add(file); gates.set(action, files)
    if (!ACTION.some((a) => a.code === action)) problems.push(`${file}: unknown gated action ${action}`)
  })
  const lines = [
    "# React domain coverage inventory", "",
    "Generated by `bun run ops coverage domain --write`. Checked by the repository test.", "",
    "This inventories declarations, real action gates, exact schema fields and foreign keys.",
    "A declaration or gate is not proof of a usable journey. Behavioral tests must also pass.",
    "The five model-blocked actions remain unfinished; internal data is accounted for, not rendered.", "",
    "## Actions", "",
    "| Action | Object | Declaration / blocker | Gated surfaces |",
    "| --- | --- | --- | --- |",
  ]
  for (const a of [...ACTION].sort((a, b) => a.code.localeCompare(b.code))) {
    const files = [...(declarations.get(a.code) ?? [])].sort()
    const reason = BLOCKED[a.code] ?? NOT_BUILT[a.code]
    if (!files.length && !reason) problems.push(`${a.code}: no journey declaration or explicit blocker`)
    lines.push(`| ${a.code} | ${a.objectTypeCode} | ${cell(reason ? `BLOCKED: ${reason}` : files.map(link).join(", "))} | ${[...(gates.get(a.code) ?? [])].sort().map(link).join(", ") || "—"} |`)
  }
  lines.push("", "## Unresolvable model grants", "",
    "These relations target a different object type; a screen cannot repair the missing domain relation.", "")
  for (const a of ACTION) for (const g of GRANTS[a.code]) {
    const relation = RELATION.find((r) => r.code === g.relation)
    if (a.objectTypeCode !== "PLATFORM" && relation && relation.objectTypeCode !== "PLATFORM" && relation.objectTypeCode !== a.objectTypeCode) {
      lines.push(`- ${a.code} / ${g.relation}: ${a.objectTypeCode} action, ${relation.objectTypeCode} relation.`)
    }
  }
  lines.push("", "## Entities, fields and relationships", "",
    "A surface is the audit location for this entity. Fields are individually qualified so shared names cannot hide additions.",
    "Vocabulary metadata supports translated labels, ordering, choices and model authorization; it does not need raw CRUD screens.", "")
  const vocabularyTables = new Set<unknown>(Object.values(vocabularies).filter((v) => is(v, SQLiteTable)))
  const tables = (Object.entries(schema) as [string, unknown][]).filter((entry): entry is [string, SQLiteTable] => is(entry[1], SQLiteTable))
  for (const [name, table] of tables.sort(([a], [b]) => a.localeCompare(b))) {
    const internal = INTERNAL[name]
    const files = SURFACES[name] ?? (vocabularyTables.has(table) ? ["lib/locale.tsx"] : [])
    if (!files.length && !internal) problems.push(`${name}: unaccounted entity`)
    for (const file of files) if (!existsSync(`src/web/${file}`)) problems.push(`${name}: missing surface ${file}`)
    lines.push(`### ${name}`, "", internal ?? files.map((f) => link(`src/web/${f}`)).join(", "), "",
      "| Field | Value type | Nullable |", "| --- | --- | --- |")
    for (const [field, column] of Object.entries(getTableColumns(table)).sort(([a], [b]) => a.localeCompare(b))) {
      lines.push(`| ${name}.${field} | ${column.dataType} | ${column.notNull || column.primary ? "no" : "yes"} |`)
    }
    const refs = getTableConfig(table).foreignKeys.map((fk) => {
      const ref = fk.reference()
      return `${getTableName(table)}.(${ref.columns.map((c) => c.name).join(", ")}) → ${getTableName(ref.foreignTable)}.(${ref.foreignColumns.map((c) => c.name).join(", ")})`
    }).sort()
    if (refs.length) lines.push("", ...refs.map((r) => `- ${r}`))
    lines.push("")
  }
  return { report: lines.join("\n"), problems }
}

export const COVERAGE_REPORT = "docs/react-domain-coverage.md"
export function coverageDrift(report: string) {
  return !existsSync(COVERAGE_REPORT) || readFileSync(COVERAGE_REPORT, "utf8") !== report
}
