import { defineConfig } from "vitest/config"
import { cloudflareTest, readD1Migrations } from "@cloudflare/vitest-pool-workers"

/**
 * Worker tests, run inside workerd — no wrangler dev, no browser, no port.
 *
 * The middle tier this repo was missing. 61 of the 151 Playwright specs never
 * opened a browser: they were HTTP calls against the Worker, paying for a real
 * server process and a Playwright runner to make them. Here the Worker is
 * loaded into the test process and `SELF.fetch()` calls its fetch handler
 * directly, with Miniflare providing D1 and R2 from the same wrangler.toml
 * production uses.
 *
 *   mise run test:unit    pure logic, no runtime      ~20ms
 *   mise run test:worker  the Worker, in workerd      this file
 *   mise run test         a real browser, and only that
 *
 * `isolatedStorage` gives each test file its own D1 stack, so specs cannot race
 * each other over shared rows — which is exactly what held Playwright to two
 * workers.
 *
 * `cloudflareTest`, not `defineWorkersConfig`: the `./config` entrypoint was
 * removed in @cloudflare/vitest-pool-workers 0.22, which pairs with vitest 4.
 */
/**
 * The same migrations wrangler applies, handed to Miniflare's D1.
 *
 * Miniflare starts each test file with an empty database. Reading the real
 * migration files rather than a fixture means these tests exercise the schema
 * that ships — a migration that breaks the app breaks them too.
 */
const migrations = await readD1Migrations("./src/db/migrations")

export default defineConfig({
  plugins: [
    cloudflareTest({
      isolatedStorage: true,
      wrangler: { configPath: "./wrangler.toml" },
      miniflare: {
        // Never let a test reach the real mail binding, whatever wrangler.toml
        // says. `outbox` captures messages in the isolate instead of sending.
        bindings: {
          MAIL_TRANSPORT: "outbox",
          // The worker tier is a dev environment: it reads the outbox, asserts
          // on the seed route and the demo picker, and needs every sample. The
          // fallback is production, so leaving this out would silently strip
          // the routes half these tests are about.
          ENVIRONMENT: "dev",
          TEST_OTP: "424242",
          TEST_MIGRATIONS: migrations,
          // A throwaway VAPID pair, so push is *on* in tests and the code that
          // signs and encrypts actually runs. With these absent the sender
          // short-circuits and a push test would pass by doing nothing —
          // exactly the shape of test that lets a broken feature ship.
          //
          // Generated by `mise run push:keys`, and used nowhere else. Its
          // presence in a public repo costs nothing: it can only sign for
          // subscriptions created against itself, and every one of those is
          // made and thrown away inside a single test.
          VAPID_SUBJECT: "mailto:test@remy.test",
          VAPID_PUBLIC_KEY:
            "BFB12hNwXz2bSHhJyLc4tKbhvcerRaQbzgAFs9jZ-4wMAId90HY43vCYGLE4azKZPlPQn5pcsifiKD1ZiwaIRIo",
          VAPID_PRIVATE_KEY: "tBr-FkbcKihsliWUd3ABzOMiSl8fu0cqHQQ9uDpl2bo",
        },
      },
    }),
  ],
  test: {
    include: ["tests/worker/**/*.test.ts"],
    setupFiles: ["./tests/worker/apply-migrations.ts"],

    /**
     * No `dangerouslyIgnoreUnhandledErrors`, and that is now a fixed bug rather
     * than a tolerated one.
     *
     * It used to be set, with a page of reasoning: Better Auth answered 400
     * correctly and separately left an unhandled rejection behind, so ten of
     * them printed on every run and the suite exited non-zero at random. The
     * flag made the run green by decision.
     *
     * The cost was in that reasoning too, honestly stated and never paid off:
     * the flag is all-or-nothing, so an unhandled rejection in **our** Worker
     * code was ignored just as quietly.
     *
     * The cause was never Better Auth. workerd fired `unhandledrejection`
     * before the microtask checkpoint completed, so a promise that rejects on
     * one tick and is caught on the next was reported as unhandled when nothing
     * ever was — and Better Auth wraps every endpoint in
     * `AsyncLocalStorage.run()`, which is exactly such a chain.
     * `unhandled_rejection_after_microtask_checkpoint` in wrangler.toml fixes
     * it at the runtime. With the cause gone the suppression is not a trade any
     * more, so it is deleted and a real unhandled rejection fails the run again.
     */
  },
})
