import { defineConfig } from "vitest/config"
import { cloudflareTest, readD1Migrations } from "@cloudflare/vitest-pool-workers"

/**
 * Worker tests, run inside workerd — no wrangler dev, no browser, no port.
 *
 * The middle tier this repo was missing. 61 of the 151 Playwright specs never
 * opened a browser: they were HTTP calls against the Worker, paying for a real
 * server process and a Playwright runner to make them. Here the Worker is
 * loaded into the test process and `SELF.fetch()` calls its fetch handler
 * directly, with Miniflare providing D1 and R2 from the same wrangler.toml
 * production uses.
 *
 *   mise run test:unit    pure logic, no runtime      ~20ms
 *   mise run test:worker  the Worker, in workerd      this file
 *   mise run test         a real browser, and only that
 *
 * `isolatedStorage` gives each test file its own D1 stack, so specs cannot race
 * each other over shared rows — which is exactly what held Playwright to two
 * workers.
 *
 * `cloudflareTest`, not `defineWorkersConfig`: the `./config` entrypoint was
 * removed in @cloudflare/vitest-pool-workers 0.22, which pairs with vitest 4.
 */
/**
 * The same migrations wrangler applies, handed to Miniflare's D1.
 *
 * Miniflare starts each test file with an empty database. Reading the real
 * migration files rather than a fixture means these tests exercise the schema
 * that ships — a migration that breaks the app breaks them too.
 */
const migrations = await readD1Migrations("./src/db/migrations")

export default defineConfig({
  plugins: [
    cloudflareTest({
      isolatedStorage: true,
      wrangler: { configPath: "./wrangler.toml" },
      miniflare: {
        // Never let a test reach the real mail binding, whatever wrangler.toml
        // says. `outbox` captures messages in the isolate instead of sending.
        bindings: {
          MAIL_TRANSPORT: "outbox",
          TEST_OTP: "424242",
          TEST_MIGRATIONS: migrations,
          // A throwaway VAPID pair, so push is *on* in tests and the code that
          // signs and encrypts actually runs. With these absent the sender
          // short-circuits and a push test would pass by doing nothing —
          // exactly the shape of test that lets a broken feature ship.
          //
          // Generated by `mise run push:keys`, and used nowhere else. Its
          // presence in a public repo costs nothing: it can only sign for
          // subscriptions created against itself, and every one of those is
          // made and thrown away inside a single test.
          VAPID_SUBJECT: "mailto:test@remy.test",
          VAPID_PUBLIC_KEY:
            "BFB12hNwXz2bSHhJyLc4tKbhvcerRaQbzgAFs9jZ-4wMAId90HY43vCYGLE4azKZPlPQn5pcsifiKD1ZiwaIRIo",
          VAPID_PRIVATE_KEY: "tBr-FkbcKihsliWUd3ABzOMiSl8fu0cqHQQ9uDpl2bo",
        },
      },
    }),
  ],
  test: {
    include: ["tests/worker/**/*.test.ts"],
    setupFiles: ["./tests/worker/apply-migrations.ts"],

    /**
     * Better Auth rejects internally on refused requests, and workerd reports
     * it where a Node runner would not.
     *
     * Asserting that password sign-in is gone means making a request Better
     * Auth refuses; it answers 400 correctly — which is what the test checks —
     * and separately leaves an unhandled rejection behind, inside its own
     * dispatch. The same happens seeding an existing user. Neither is our code
     * and neither changes a response.
     *
     * Scoped deliberately: this ignores unhandled REJECTIONS, not failing
     * assertions. A test that actually fails still fails.
     */
    dangerouslyIgnoreUnhandledErrors: true,
  },
})
