// GENERATED by `mise run domain:generate` — do not edit.
//
// Source: the remy-sport-biz fixtures, which AGENTS.md names as the source of
// truth for domain definitions. Edit the vocabularies there and regenerate;
// `mise run domain:check` fails when this file is stale.
//
// Languages are rows, not columns: `names` carries one entry per locale
// declared in the fixtures, so adding a language is a regeneration and nothing
// more. Nothing here should ever grow a `nameXx` field.
//
// Event type codes are lowercased here, a deliberate delta from the fixtures
// recorded in migrations 0005 and 0009 — this repo's published OpenAPI enum is
// lowercase and changing it would break clients.

/** Every language the fixtures declare. English first: it is the pivot. */
export const LOCALES = ["en", "th"] as const

export type Locale = (typeof LOCALES)[number]

/** A term in a controlled vocabulary, named in every declared locale. */
export interface Term {
  readonly code: string
  readonly names: Readonly<Record<Locale, string>>
  readonly minAge?: number | null
  readonly maxAge?: number | null
}

/** Look up a display name, falling back to English and then to the code. */
export function label(terms: readonly Term[], code: string, locale: Locale = "en"): string {
  const term = terms.find((t) => t.code === code)
  if (!term) return code
  return term.names[locale] ?? term.names.en ?? code
}

/** 8 rows, from age_groups.jsonl. */
export const AGE_GROUP = [
  { code: "U10", names: { en: "Under 10", th: "อายุไม่เกิน 10 ปี" }, minAge: null, maxAge: 10 },
  { code: "U12", names: { en: "Under 12", th: "อายุไม่เกิน 12 ปี" }, minAge: null, maxAge: 12 },
  { code: "U14", names: { en: "Under 14", th: "อายุไม่เกิน 14 ปี" }, minAge: null, maxAge: 14 },
  { code: "U16", names: { en: "Under 16", th: "อายุไม่เกิน 16 ปี" }, minAge: null, maxAge: 16 },
  { code: "U18", names: { en: "Under 18", th: "อายุไม่เกิน 18 ปี" }, minAge: null, maxAge: 18 },
  { code: "U21", names: { en: "Under 21", th: "อายุไม่เกิน 21 ปี" }, minAge: null, maxAge: 21 },
  { code: "OPEN", names: { en: "Open Age", th: "เปิดอายุ" }, minAge: null, maxAge: null },
  { code: "SENIOR", names: { en: "Senior", th: "อาวุโส" }, minAge: 30, maxAge: null },
] as const satisfies readonly Term[]

export const AGE_GROUP_CODES = AGE_GROUP.map((t) => t.code) as unknown as [
  "U10",
  "U12",
  "U14",
  "U16",
  "U18",
  "U21",
  "OPEN",
  "SENIOR",
]

export type AgeGroupCode = (typeof AGE_GROUP_CODES)[number]

/** 3 rows, from genders.jsonl. */
export const GENDER = [
  { code: "M", names: { en: "Boys", th: "ชาย" } },
  { code: "F", names: { en: "Girls", th: "หญิง" } },
  { code: "COED", names: { en: "Co-ed", th: "ผสม" } },
] as const satisfies readonly Term[]

export const GENDER_CODES = GENDER.map((t) => t.code) as unknown as [
  "M",
  "F",
  "COED",
]

export type GenderCode = (typeof GENDER_CODES)[number]

/** 4 rows, from org_types.jsonl. */
export const ORG_TYPE = [
  { code: "SCHOOL", names: { en: "School", th: "โรงเรียน" } },
  { code: "CLUB", names: { en: "Club", th: "สโมสร" } },
  { code: "FEDERATION", names: { en: "Federation", th: "สหพันธ์" } },
  { code: "GRASSROOTS", names: { en: "Grassroots", th: "ชุมชนรากหญ้า" } },
] as const satisfies readonly Term[]

export const ORG_TYPE_CODES = ORG_TYPE.map((t) => t.code) as unknown as [
  "SCHOOL",
  "CLUB",
  "FEDERATION",
  "GRASSROOTS",
]

export type OrgTypeCode = (typeof ORG_TYPE_CODES)[number]

/** 4 rows, from event_types.jsonl. */
export const EVENT_TYPE = [
  { code: "tournament", names: { en: "Tournament", th: "การแข่งขันแบบทัวร์นาเมนต์" } },
  { code: "league", names: { en: "League", th: "ลีก" } },
  { code: "camp", names: { en: "Camp / Clinic", th: "ค่ายฝึก" } },
  { code: "showcase", names: { en: "Showcase", th: "การโชว์ผู้เล่น" } },
] as const satisfies readonly Term[]

export const EVENT_TYPE_CODES = EVENT_TYPE.map((t) => t.code) as unknown as [
  "tournament",
  "league",
  "camp",
  "showcase",
]

export type EventTypeCode = (typeof EVENT_TYPE_CODES)[number]

/** 2 rows, from event_formats.jsonl. */
export const EVENT_FORMAT = [
  { code: "5x5", names: { en: "5-on-5", th: "5 ต่อ 5" } },
  { code: "3x3", names: { en: "3x3", th: "3 ต่อ 3" } },
] as const satisfies readonly Term[]

export const EVENT_FORMAT_CODES = EVENT_FORMAT.map((t) => t.code) as unknown as [
  "5x5",
  "3x3",
]

export type EventFormatCode = (typeof EVENT_FORMAT_CODES)[number]

/** 15 rows, from provinces.jsonl. */
export const PROVINCE = [
  { code: "BKK", names: { en: "Bangkok", th: "กรุงเทพมหานคร" } },
  { code: "NBI", names: { en: "Nonthaburi", th: "นนทบุรี" } },
  { code: "CMI", names: { en: "Chiang Mai", th: "เชียงใหม่" } },
  { code: "CRI", names: { en: "Chiang Rai", th: "เชียงราย" } },
  { code: "NMA", names: { en: "Nakhon Ratchasima", th: "นครราชสีมา" } },
  { code: "KKN", names: { en: "Khon Kaen", th: "ขอนแก่น" } },
  { code: "UBN", names: { en: "Ubon Ratchathani", th: "อุบลราชธานี" } },
  { code: "UDN", names: { en: "Udon Thani", th: "อุดรธานี" } },
  { code: "CBI", names: { en: "Chonburi", th: "ชลบุรี" } },
  { code: "PHK", names: { en: "Phuket", th: "ภูเก็ต" } },
  { code: "SKA", names: { en: "Songkhla", th: "สงขลา" } },
  { code: "NST", names: { en: "Nakhon Si Thammarat", th: "นครศรีธรรมราช" } },
  { code: "SNI", names: { en: "Surat Thani", th: "สุราษฎร์ธานี" } },
  { code: "RBR", names: { en: "Ratchaburi", th: "ราชบุรี" } },
  { code: "PTE", names: { en: "Pathum Thani", th: "ปทุมธานี" } },
] as const satisfies readonly Term[]

export const PROVINCE_CODES = PROVINCE.map((t) => t.code) as unknown as [
  "BKK",
  "NBI",
  "CMI",
  "CRI",
  "NMA",
  "KKN",
  "UBN",
  "UDN",
  "CBI",
  "PHK",
  "SKA",
  "NST",
  "SNI",
  "RBR",
  "PTE",
]

export type ProvinceCode = (typeof PROVINCE_CODES)[number]

/** 2 rows, from cities.jsonl. */
export const CITY = [
  { code: "BANGKOK", names: { en: "Bangkok", th: "กรุงเทพมหานคร" } },
  { code: "CHIANG_MAI", names: { en: "Chiang Mai", th: "เชียงใหม่" } },
] as const satisfies readonly Term[]

export const CITY_CODES = CITY.map((t) => t.code) as unknown as [
  "BANGKOK",
  "CHIANG_MAI",
]

export type CityCode = (typeof CITY_CODES)[number]
