import { test, expect } from "@playwright/test"

test.describe("The root serves the one GUI", () => {
  // These replace three tests against the server-rendered home page that ADR
  // 020 deleted. The interesting assertion is no longer "does the marketing
  // copy render" but "does `/` serve the SPA at all" — `not_found_handling` is
  // "none" in wrangler.toml, so a missing route here is a 404, not a fallback.
  test("/ serves the SPA document", async ({ page }) => {
    await page.goto("/")
    await expect(page.locator("#root")).toBeAttached()
  })

  test("the deleted harness paths are gone, not redirected", async ({ page }) => {
    // No aliases for /app, /login or /dashboard. There are no users, so nothing
    // holds a link to them, and a redirect kept "just in case" is how two URLs
    // for one page become permanent.
    for (const path of ["/app", "/dashboard"]) {
      const res = await page.goto(path)
      expect(res?.status(), `${path} should not resolve`).toBe(404)
    }
  })

  test("a deep link resolves client-side rather than 404ing", async ({ page }) => {
    await page.goto("/#/admin")
    await expect(page.locator("#root")).toBeAttached()
  })
})

test.describe("Health endpoint", () => {
  test("returns ok status", async ({ request }) => {
    const res = await request.get("/api/health")
    expect(res.ok()).toBeTruthy()
    const body = await res.json()
    expect(body.status).toBe("ok")
    expect(body.timestamp).toBeTruthy()
  })
})

test.describe("OpenAPI doc", () => {
  test("returns valid OpenAPI spec with security schemes", async ({ request }) => {
    const res = await request.get("/openapi.json")
    expect(res.ok()).toBeTruthy()
    const body = await res.json()
    // 3.1.1: the document is generated by oRPC from the contract now, not by
    // @hono/zod-openapi from route declarations. 3.1 is a superset of 3.0.
    expect(body.openapi).toMatch(/^3\.1\./)
    expect(body.info.title).toBe("Remy Sport API")
    expect(body.paths["/api/health"]).toBeTruthy()
    expect(body.paths["/api/events"]).toBeTruthy()
    expect(body.components.securitySchemes.Session).toBeTruthy()
    expect(body.components.securitySchemes.ApiKey).toBeTruthy()
  })

  test("serves Swagger UI", async ({ request }) => {
    const res = await request.get("/doc")
    expect(res.ok()).toBeTruthy()
    const html = await res.text()
    expect(html).toContain("swagger-ui")
  })
})
