-- ADR 006: align the database with the CLI-generated Better Auth schema.
--
-- src/db/auth-schema.ts is now generated by `mise run auth:schema:generate`
-- rather than hand-written. Two differences from the hand-maintained version
-- need DDL, and one needs a data reset.

-- 1. Missing column. The Better Auth admin plugin adds session.impersonated_by.
--    The generated schema declares it; the hand-written schema never did, so no
--    migration ever created it. Nothing failed while both were wrong in the
--    same way — the moment the schema became correct, every sign-in 500'd with
--    "table session has no column named impersonated_by". This is the exact
--    drift that generating the schema is meant to prevent.
ALTER TABLE session ADD COLUMN impersonated_by TEXT;

-- 2. Index names. The generated schema declares session_userId_idx,
--    account_userId_idx and verification_identifier_idx; the hand-written
--    migrations created the first two under different names and never created
--    the third at all. Names matter so a future generated migration diffs
--    cleanly against what is actually in the database.
DROP INDEX IF EXISTS idx_session_user_id;
DROP INDEX IF EXISTS idx_account_user_id;

CREATE INDEX IF NOT EXISTS session_userId_idx ON session(user_id);
CREATE INDEX IF NOT EXISTS account_userId_idx ON account(user_id);
CREATE INDEX IF NOT EXISTS verification_identifier_idx ON verification(identifier);

-- 3. Timestamp encoding. The hand-written schema declared Drizzle
--    `mode: "timestamp"` (Unix *seconds*); Better Auth generates
--    `mode: "timestamp_ms"` (milliseconds). Existing rows hold second-scale
--    values that would now be read as milliseconds — every date would decode
--    as 1970 and every session would look long expired.
--
--    The auth tables hold only seeded development accounts (see AGENTS.md), so
--    they are cleared rather than converted; `/api/seed` recreates them with
--    the correct encoding on the next deploy. event rows are removed too
--    because event.created_by references user(id).
--
--    This is safe precisely because the site has no real users yet. Do NOT
--    copy this pattern once it does — convert in place instead.
DELETE FROM event;
DELETE FROM session;
DELETE FROM account;
DELETE FROM verification;
DELETE FROM user;
