-- GENERATED by `mise run domain:generate` — do not edit.
--
-- Tables and rows for every reference vocabulary in remy-sport-biz. Add a file to the
-- fixtures' reference/ folder and regenerate; nothing here is hand-maintained,
-- and `mise run domain:check` fails when this goes stale.
--
-- Display names live in JSON columns keyed by locale — `names`, `descriptions`
-- — never a column per language. Each keeps its `*_en` pivot beside it: NOT
-- NULL, so there is always something renderable, and sortable without reaching
-- into JSON.
--

CREATE TABLE IF NOT EXISTS object_type (
  code               TEXT PRIMARY KEY,
  name_en            TEXT NOT NULL,
  names              TEXT NOT NULL,
  description_en     TEXT NOT NULL,
  descriptions       TEXT NOT NULL,
  sort               INTEGER NOT NULL
);
INSERT OR IGNORE INTO object_type (code, name_en, names, description_en, descriptions, sort) VALUES
  ('EVENT', 'Event', '{"th":"อีเวนต์","en":"Event"}', 'Tournaments leagues camps showcases — subtype lives in events.type_code', '{"th":"ทัวร์นาเมนต์ ลีก ค่ายฝึก และกิจกรรมแสดงผลงาน โดยประเภทย่อยอยู่ใน events.type_code","en":"Tournaments leagues camps showcases — subtype lives in events.type_code"}', 1),
  ('TEAM', 'Team', '{"th":"ทีม","en":"Team"}', 'Team profile and roster', '{"th":"โปรไฟล์ทีมและรายชื่อผู้เล่น","en":"Team profile and roster"}', 2),
  ('PLAYER', 'Player', '{"th":"ผู้เล่น","en":"Player"}', 'Individual player profile', '{"th":"โปรไฟล์ผู้เล่นรายบุคคล","en":"Individual player profile"}', 3),
  ('ORG', 'Organisation', '{"th":"องค์กร","en":"Organisation"}', 'Schools clubs federations', '{"th":"โรงเรียน สโมสร และสหพันธ์","en":"Schools clubs federations"}', 4),
  ('DIVISION', 'Division', '{"th":"ดิวิชั่น","en":"Division"}', 'Competitive division within events', '{"th":"ดิวิชั่นการแข่งขันภายในอีเวนต์","en":"Competitive division within events"}', 5),
  ('PLATFORM', 'Platform', '{"th":"แพลตฟอร์ม","en":"Platform"}', 'Global actions not tied to a specific object', '{"th":"การดำเนินการทั่วทั้งระบบที่ไม่ผูกกับออบเจ็กต์ใดโดยเฉพาะ","en":"Global actions not tied to a specific object"}', 6);

CREATE TABLE IF NOT EXISTS action (
  code               TEXT PRIMARY KEY,
  object_type_code   TEXT NOT NULL REFERENCES object_type(code),
  category           TEXT NOT NULL,
  name_en            TEXT NOT NULL,
  names              TEXT NOT NULL,
  sort               INTEGER NOT NULL
);
INSERT OR IGNORE INTO action (code, object_type_code, category, name_en, names, sort) VALUES
  ('SIGN_IN_OUT', 'PLATFORM', 'Auth', 'Sign in / Sign out', '{"th":"ลงชื่อเข้า / ออก","en":"Sign in / Sign out"}', 1),
  ('SIGN_UP_AS_SPECTATOR', 'PLATFORM', 'Auth', 'Sign up as Spectator', '{"th":"สมัครเป็นผู้ชม","en":"Sign up as Spectator"}', 2),
  ('SIGN_UP_AS_PLAYER', 'PLATFORM', 'Auth', 'Sign up as Player (adult)', '{"th":"สมัครเป็นผู้เล่น (ผู้ใหญ่)","en":"Sign up as Player (adult)"}', 3),
  ('SIGN_UP_AS_COACH', 'PLATFORM', 'Auth', 'Sign up as Coach', '{"th":"สมัครเป็นโค้ช","en":"Sign up as Coach"}', 4),
  ('SIGN_UP_AS_ORGANIZER', 'PLATFORM', 'Auth', 'Sign up as Organizer', '{"th":"สมัครเป็นผู้จัดการแข่งขัน","en":"Sign up as Organizer"}', 5),
  ('SIGN_UP_PLAYER_AS_GUARDIAN', 'PLATFORM', 'Auth', 'Sign up minor Player as Guardian', '{"th":"สมัครผู้เล่น (เด็กในความดูแล)","en":"Sign up minor Player as Guardian"}', 6),
  ('SIGN_UP_AS_REFEREE_REQUEST', 'PLATFORM', 'Auth', 'Submit Referee signup request', '{"th":"ส่งคำขอสมัครเป็นผู้ตัดสิน","en":"Submit Referee signup request"}', 7),
  ('APPROVE_REFEREE', 'PLATFORM', 'Admin', 'Approve pending Referee account', '{"th":"อนุมัติผู้ตัดสิน","en":"Approve pending Referee account"}', 8),
  ('CREATE_USER_ACCOUNT', 'PLATFORM', 'Admin', 'Create any user account (admin-only minting)', '{"th":"สร้างบัญชีผู้ใช้ (ใดๆ)","en":"Create any user account (admin-only minting)"}', 9),
  ('INVITE_CO_ORGANIZER', 'EVENT', 'Events', 'Invite Co-organizer to event', '{"th":"เชิญผู้ร่วมจัด","en":"Invite Co-organizer to event"}', 10),
  ('ACCEPT_CO_ORGANIZER_INVITE', 'EVENT', 'Events', 'Accept Co-organizer invite', '{"th":"ตอบรับเป็นผู้ร่วมจัด","en":"Accept Co-organizer invite"}', 11),
  ('INSTALL_APP', 'PLATFORM', 'Live', 'Install app (PWA)', '{"th":"ติดตั้งแอป (PWA)","en":"Install app (PWA)"}', 12),
  ('MANAGE_ALL_USERS', 'PLATFORM', 'Admin', 'Manage all users', '{"th":"จัดการผู้ใช้ทั้งหมด","en":"Manage all users"}', 13),
  ('MODERATE_LISTINGS', 'PLATFORM', 'Admin', 'Moderate listings', '{"th":"ตรวจสอบและจัดการรายการ","en":"Moderate listings"}', 14),
  ('BROWSE_EVENTS', 'PLATFORM', 'Events', 'Browse events (list)', '{"th":"เรียกดูอีเวนต์","en":"Browse events (list)"}', 15),
  ('BROWSE_TEAMS', 'PLATFORM', 'Teams', 'Browse / find a team', '{"th":"ค้นหาทีม","en":"Browse / find a team"}', 16),
  ('CREATE_EVENT', 'PLATFORM', 'Events', 'Create event', '{"th":"สร้างอีเวนต์","en":"Create event"}', 17),
  ('VIEW_EVENT', 'EVENT', 'Events', 'View event detail', '{"th":"ดูอีเวนต์","en":"View event detail"}', 18),
  ('EDIT_EVENT', 'EVENT', 'Events', 'Edit event', '{"th":"แก้ไขอีเวนต์","en":"Edit event"}', 19),
  ('DELETE_EVENT', 'EVENT', 'Events', 'Delete event', '{"th":"ลบอีเวนต์","en":"Delete event"}', 20),
  ('MANAGE_DIVISIONS', 'EVENT', 'Events', 'Manage event divisions', '{"th":"จัดการดิวิชั่น","en":"Manage event divisions"}', 21),
  ('REGISTER_TEAM_FOR_EVENT', 'EVENT', 'Events', 'Register team for event', '{"th":"ลงทะเบียนทีมเข้าอีเวนต์","en":"Register team for event"}', 22),
  ('REGISTER_PLAYER_FOR_EVENT', 'EVENT', 'Events', 'Register player for event', '{"th":"ลงทะเบียนผู้เล่นเข้าอีเวนต์","en":"Register player for event"}', 23),
  ('CREATE_TEAM', 'PLATFORM', 'Teams', 'Create team', '{"th":"สร้างทีม","en":"Create team"}', 24),
  ('VIEW_TEAM', 'TEAM', 'Teams', 'View team profile', '{"th":"ดูโปรไฟล์ทีม","en":"View team profile"}', 25),
  ('EDIT_TEAM_PROFILE', 'TEAM', 'Teams', 'Edit team profile', '{"th":"แก้ไขโปรไฟล์ทีม","en":"Edit team profile"}', 26),
  ('DELETE_TEAM', 'TEAM', 'Teams', 'Delete team', '{"th":"ลบทีม","en":"Delete team"}', 27),
  ('MANAGE_ROSTER', 'TEAM', 'Teams', 'Manage team roster', '{"th":"จัดการรายชื่อผู้เล่น","en":"Manage team roster"}', 28),
  ('CREATE_PLAYER', 'PLATFORM', 'Players', 'Create player profile', '{"th":"สร้างโปรไฟล์ผู้เล่น","en":"Create player profile"}', 29),
  ('VIEW_PLAYER', 'PLAYER', 'Players', 'View player profile', '{"th":"ดูโปรไฟล์ผู้เล่น","en":"View player profile"}', 30),
  ('EDIT_PLAYER_PROFILE', 'PLAYER', 'Players', 'Edit player profile', '{"th":"แก้ไขโปรไฟล์ผู้เล่น","en":"Edit player profile"}', 31),
  ('DELETE_PLAYER', 'PLAYER', 'Players', 'Delete player profile', '{"th":"ลบโปรไฟล์ผู้เล่น","en":"Delete player profile"}', 32),
  ('VIEW_PLAYER_STATS', 'PLAYER', 'Rankings', 'View player stats', '{"th":"ดูสถิติผู้เล่น","en":"View player stats"}', 33),
  ('FOLLOW_PLAYER', 'PLAYER', 'Players', 'Follow player', '{"th":"ติดตามผู้เล่น","en":"Follow player"}', 34),
  ('UNFOLLOW_PLAYER', 'PLAYER', 'Players', 'Unfollow player', '{"th":"เลิกติดตามผู้เล่น","en":"Unfollow player"}', 35),
  ('RECEIVE_PLAYER_NOTIFICATIONS', 'PLAYER', 'Live', 'Receive player notifications', '{"th":"รับการแจ้งเตือนผู้เล่น","en":"Receive player notifications"}', 36),
  ('FOLLOW_TEAM', 'TEAM', 'Teams', 'Follow team', '{"th":"ติดตามทีม","en":"Follow team"}', 37),
  ('UNFOLLOW_TEAM', 'TEAM', 'Teams', 'Unfollow team', '{"th":"เลิกติดตามทีม","en":"Unfollow team"}', 38),
  ('RECEIVE_TEAM_NOTIFICATIONS', 'TEAM', 'Live', 'Receive team notifications', '{"th":"รับการแจ้งเตือนทีม","en":"Receive team notifications"}', 39),
  ('FOLLOW_EVENT', 'EVENT', 'Events', 'Follow event', '{"th":"ติดตามอีเวนต์","en":"Follow event"}', 40),
  ('UNFOLLOW_EVENT', 'EVENT', 'Events', 'Unfollow event', '{"th":"เลิกติดตามอีเวนต์","en":"Unfollow event"}', 41),
  ('RECEIVE_EVENT_NOTIFICATIONS', 'EVENT', 'Live', 'Receive event notifications', '{"th":"รับการแจ้งเตือนอีเวนต์","en":"Receive event notifications"}', 42),
  ('VIEW_BRACKET', 'EVENT', 'Schedules', 'View bracket', '{"th":"ดูสายแข่งขัน","en":"View bracket"}', 43),
  ('VIEW_FIXTURE_SCHEDULE', 'EVENT', 'Schedules', 'View fixture schedule', '{"th":"ดูตารางแข่งขัน","en":"View fixture schedule"}', 44),
  ('VIEW_COURT_ASSIGNMENTS', 'EVENT', 'Schedules', 'View court assignments', '{"th":"ดูการจัดสนาม","en":"View court assignments"}', 45),
  ('GENERATE_BRACKETS', 'EVENT', 'Schedules', 'Generate brackets', '{"th":"สร้างสายแข่งขัน","en":"Generate brackets"}', 46),
  ('GENERATE_FIXTURES', 'EVENT', 'Schedules', 'Generate fixtures', '{"th":"สร้างตารางแข่งขัน","en":"Generate fixtures"}', 47),
  ('DEFINE_SESSION_SCHEDULE', 'EVENT', 'Schedules', 'Define session schedule', '{"th":"กำหนดตารางเซสชัน","en":"Define session schedule"}', 48),
  ('ASSIGN_COURTS', 'EVENT', 'Schedules', 'Assign courts', '{"th":"กำหนดสนาม","en":"Assign courts"}', 49),
  ('ENTER_SCORES', 'EVENT', 'Scores', 'Enter scores', '{"th":"บันทึกคะแนน","en":"Enter scores"}', 50),
  ('CONFIRM_MATCH_STATUS', 'EVENT', 'Scores', 'Confirm match status', '{"th":"ยืนยันสถานะการแข่งขัน","en":"Confirm match status"}', 51),
  ('RECORD_ATTENDANCE', 'EVENT', 'Scores', 'Record attendance', '{"th":"บันทึกการเข้าร่วม","en":"Record attendance"}', 52),
  ('VIEW_GAME_RESULTS', 'EVENT', 'Scores', 'View game results', '{"th":"ดูผลการแข่งขัน","en":"View game results"}', 53),
  ('VIEW_MATCH_STATUS', 'EVENT', 'Scores', 'View match status', '{"th":"ดูสถานะการแข่งขัน","en":"View match status"}', 54),
  ('SPOILER_MODE', 'PLATFORM', 'Scores', 'Spoiler mode preference', '{"th":"โหมดซ่อนสปอยล์","en":"Spoiler mode preference"}', 55),
  ('VIEW_RESULTS_ARCHIVE', 'PLATFORM', 'Scores', 'View results archive', '{"th":"ดูประวัติผลการแข่งขัน","en":"View results archive"}', 56),
  ('VIEW_STANDINGS', 'EVENT', 'Rankings', 'View standings', '{"th":"ดูตารางคะแนน","en":"View standings"}', 57),
  ('VIEW_RANK_MOVEMENT', 'EVENT', 'Rankings', 'View rank movement', '{"th":"ดูการเปลี่ยนอันดับ","en":"View rank movement"}', 58),
  ('VIEW_RANKINGS_HISTORY', 'PLATFORM', 'Rankings', 'View rankings history', '{"th":"ดูประวัติอันดับ","en":"View rankings history"}', 59),
  ('VIEW_SEASON_RECORDS', 'EVENT', 'Rankings', 'View season records', '{"th":"ดูสถิติประจำฤดูกาล","en":"View season records"}', 60),
  ('VIEW_LIVE_SCORES', 'EVENT', 'Live', 'View live scores', '{"th":"ดูคะแนนสด","en":"View live scores"}', 61),
  ('RECEIVE_NOTIFICATIONS', 'PLATFORM', 'Live', 'Receive push notifications', '{"th":"รับการแจ้งเตือน","en":"Receive push notifications"}', 62),
  ('MANAGE_OWN_NOTIFICATION_CHANNELS', 'PLATFORM', 'Live', 'Manage own notification channels (add / remove / verify / enable / disable)', '{"th":"จัดการช่องทางการแจ้งเตือนของตัวเอง","en":"Manage own notification channels (add / remove / verify / enable / disable)"}', 63),
  ('MANAGE_OWN_NOTIFICATION_PREFERENCES', 'PLATFORM', 'Live', 'Manage own per-type notification preferences (which type via which channel)', '{"th":"จัดการการตั้งค่าการแจ้งเตือนของตัวเอง","en":"Manage own per-type notification preferences (which type via which channel)"}', 64),
  ('VIEW_LIVE_STREAM', 'EVENT', 'Live', 'View live stream links', '{"th":"ดูถ่ายทอดสด","en":"View live stream links"}', 65),
  ('VIEW_COURT_STATUS_BOARD', 'EVENT', 'Live', 'View court status board', '{"th":"ดูกระดานสถานะสนาม","en":"View court status board"}', 66),
  ('AI_CREATE_EVENT', 'PLATFORM', 'AI', 'Create event via AI chat', '{"th":"สร้างอีเวนต์ผ่านแชต","en":"Create event via AI chat"}', 67),
  ('AI_BRACKET_SUGGESTIONS', 'EVENT', 'AI', 'AI bracket suggestions', '{"th":"คำแนะนำสายแข่งขัน","en":"AI bracket suggestions"}', 68),
  ('AI_QA', 'PLATFORM', 'AI', 'AI Q&A', '{"th":"ถาม-ตอบ AI","en":"AI Q&A"}', 69);

CREATE TABLE IF NOT EXISTS age_group (
  code               TEXT PRIMARY KEY,
  name_en            TEXT NOT NULL,
  names              TEXT NOT NULL,
  min_age            INTEGER,
  max_age            INTEGER,
  sort               INTEGER NOT NULL
);
INSERT OR IGNORE INTO age_group (code, name_en, names, min_age, max_age, sort) VALUES
  ('U10', 'Under 10', '{"th":"อายุไม่เกิน 10 ปี","en":"Under 10"}', NULL, 10, 1),
  ('U12', 'Under 12', '{"th":"อายุไม่เกิน 12 ปี","en":"Under 12"}', NULL, 12, 2),
  ('U14', 'Under 14', '{"th":"อายุไม่เกิน 14 ปี","en":"Under 14"}', NULL, 14, 3),
  ('U16', 'Under 16', '{"th":"อายุไม่เกิน 16 ปี","en":"Under 16"}', NULL, 16, 4),
  ('U18', 'Under 18', '{"th":"อายุไม่เกิน 18 ปี","en":"Under 18"}', NULL, 18, 5),
  ('U21', 'Under 21', '{"th":"อายุไม่เกิน 21 ปี","en":"Under 21"}', NULL, 21, 6),
  ('OPEN', 'Open Age', '{"th":"เปิดอายุ","en":"Open Age"}', NULL, NULL, 7),
  ('SENIOR', 'Senior', '{"th":"อาวุโส","en":"Senior"}', 30, NULL, 8);

CREATE TABLE IF NOT EXISTS province (
  code               TEXT PRIMARY KEY,
  name_en            TEXT NOT NULL,
  names              TEXT NOT NULL,
  sort               INTEGER NOT NULL
);
INSERT OR IGNORE INTO province (code, name_en, names, sort) VALUES
  ('BKK', 'Bangkok', '{"th":"กรุงเทพมหานคร","en":"Bangkok"}', 1),
  ('NBI', 'Nonthaburi', '{"th":"นนทบุรี","en":"Nonthaburi"}', 2),
  ('CMI', 'Chiang Mai', '{"th":"เชียงใหม่","en":"Chiang Mai"}', 3),
  ('CRI', 'Chiang Rai', '{"th":"เชียงราย","en":"Chiang Rai"}', 4),
  ('NMA', 'Nakhon Ratchasima', '{"th":"นครราชสีมา","en":"Nakhon Ratchasima"}', 5),
  ('KKN', 'Khon Kaen', '{"th":"ขอนแก่น","en":"Khon Kaen"}', 6),
  ('UBN', 'Ubon Ratchathani', '{"th":"อุบลราชธานี","en":"Ubon Ratchathani"}', 7),
  ('UDN', 'Udon Thani', '{"th":"อุดรธานี","en":"Udon Thani"}', 8),
  ('CBI', 'Chonburi', '{"th":"ชลบุรี","en":"Chonburi"}', 9),
  ('PHK', 'Phuket', '{"th":"ภูเก็ต","en":"Phuket"}', 10),
  ('SKA', 'Songkhla', '{"th":"สงขลา","en":"Songkhla"}', 11),
  ('NST', 'Nakhon Si Thammarat', '{"th":"นครศรีธรรมราช","en":"Nakhon Si Thammarat"}', 12),
  ('SNI', 'Surat Thani', '{"th":"สุราษฎร์ธานี","en":"Surat Thani"}', 13),
  ('RBR', 'Ratchaburi', '{"th":"ราชบุรี","en":"Ratchaburi"}', 14),
  ('PTE', 'Pathum Thani', '{"th":"ปทุมธานี","en":"Pathum Thani"}', 15);

CREATE TABLE IF NOT EXISTS city (
  code               TEXT PRIMARY KEY,
  name_en            TEXT NOT NULL,
  names              TEXT NOT NULL,
  province_code      TEXT NOT NULL REFERENCES province(code),
  sort               INTEGER NOT NULL
);
INSERT OR IGNORE INTO city (code, name_en, names, province_code, sort) VALUES
  ('BANGKOK', 'Bangkok', '{"th":"กรุงเทพมหานคร","en":"Bangkok"}', 'BKK', 1),
  ('CHIANG_MAI', 'Chiang Mai', '{"th":"เชียงใหม่","en":"Chiang Mai"}', 'CMI', 2);

CREATE TABLE IF NOT EXISTS coach_role (
  code               TEXT PRIMARY KEY,
  name_en            TEXT NOT NULL,
  names              TEXT NOT NULL,
  sort               INTEGER NOT NULL
);
INSERT OR IGNORE INTO coach_role (code, name_en, names, sort) VALUES
  ('HEAD', 'Head Coach', '{"th":"หัวหน้าผู้ฝึกสอน","en":"Head Coach"}', 1),
  ('ASSISTANT', 'Assistant Coach', '{"th":"ผู้ช่วยผู้ฝึกสอน","en":"Assistant Coach"}', 2),
  ('MANAGER', 'Team Manager', '{"th":"ผู้จัดการทีม","en":"Team Manager"}', 3);

CREATE TABLE IF NOT EXISTS event_format (
  code               TEXT PRIMARY KEY,
  name_en            TEXT NOT NULL,
  names              TEXT NOT NULL,
  sort               INTEGER NOT NULL
);
INSERT OR IGNORE INTO event_format (code, name_en, names, sort) VALUES
  ('5x5', '5-on-5', '{"th":"5 ต่อ 5","en":"5-on-5"}', 1),
  ('3x3', '3x3', '{"th":"3 ต่อ 3","en":"3x3"}', 2);

CREATE TABLE IF NOT EXISTS event_type (
  code               TEXT PRIMARY KEY,
  name_en            TEXT NOT NULL,
  names              TEXT NOT NULL,
  description_en     TEXT NOT NULL,
  descriptions       TEXT NOT NULL,
  sort               INTEGER NOT NULL
);
INSERT OR IGNORE INTO event_type (code, name_en, names, description_en, descriptions, sort) VALUES
  ('TOURNAMENT', 'Tournament', '{"th":"การแข่งขันแบบทัวร์นาเมนต์","en":"Tournament"}', 'Bracketed competition with elimination rounds and a declared winner', '{"th":"การแข่งขันแบบแบ่งสายและคัดออกจนได้ผู้ชนะที่ประกาศอย่างเป็นทางการ","en":"Bracketed competition with elimination rounds and a declared winner"}', 1),
  ('LEAGUE', 'League', '{"th":"ลีก","en":"League"}', 'Recurring season — teams play scheduled rounds and accumulate points', '{"th":"ฤดูกาลแข่งขันต่อเนื่อง ทีมแข่งขันตามรอบที่กำหนดและสะสมคะแนน","en":"Recurring season — teams play scheduled rounds and accumulate points"}', 2),
  ('CAMP', 'Camp / Clinic', '{"th":"ค่ายฝึก","en":"Camp / Clinic"}', 'Training event — skill development not competition', '{"th":"กิจกรรมฝึกทักษะเพื่อพัฒนาความสามารถ ไม่ใช่การแข่งขัน","en":"Training event — skill development not competition"}', 3),
  ('SHOWCASE', 'Showcase', '{"th":"การโชว์ผู้เล่น","en":"Showcase"}', 'Exhibition event for visibility — scouts recruiters media', '{"th":"กิจกรรมแสดงผลงานเพื่อสร้างโอกาสให้แมวมอง ผู้สรรหา และสื่อเห็นผู้เล่น","en":"Exhibition event for visibility — scouts recruiters media"}', 4);

CREATE TABLE IF NOT EXISTS gender (
  code               TEXT PRIMARY KEY,
  name_en            TEXT NOT NULL,
  names              TEXT NOT NULL,
  sort               INTEGER NOT NULL
);
INSERT OR IGNORE INTO gender (code, name_en, names, sort) VALUES
  ('M', 'Boys', '{"th":"ชาย","en":"Boys"}', 1),
  ('F', 'Girls', '{"th":"หญิง","en":"Girls"}', 2),
  ('COED', 'Co-ed', '{"th":"ผสม","en":"Co-ed"}', 3);

CREATE TABLE IF NOT EXISTS locale (
  code               TEXT PRIMARY KEY,
  name_en            TEXT NOT NULL,
  names              TEXT NOT NULL,
  status             TEXT NOT NULL,
  sort               INTEGER NOT NULL
);
INSERT OR IGNORE INTO locale (code, name_en, names, status, sort) VALUES
  ('th', 'Thai', '{"th":"ไทย","en":"Thai"}', 'released', 1),
  ('en', 'English', '{"th":"อังกฤษ","en":"English"}', 'released', 2),
  ('ja', 'Japanese', '{"th":"ญี่ปุ่น","en":"Japanese"}', 'draft', 3);

CREATE TABLE IF NOT EXISTS notification_category (
  code               TEXT PRIMARY KEY,
  name_en            TEXT NOT NULL,
  names              TEXT NOT NULL,
  sort               INTEGER NOT NULL
);
INSERT OR IGNORE INTO notification_category (code, name_en, names, sort) VALUES
  ('LIVE', 'Live', '{"th":"สด","en":"Live"}', 1),
  ('REMINDER', 'Reminder', '{"th":"เตือนความจำ","en":"Reminder"}', 2),
  ('DISCOVERY', 'Discovery', '{"th":"ค้นพบ","en":"Discovery"}', 3),
  ('TEAM', 'Team', '{"th":"ทีม","en":"Team"}', 4),
  ('REGISTRATION', 'Registration', '{"th":"การสมัคร","en":"Registration"}', 5),
  ('DIGEST', 'Digest', '{"th":"สรุป","en":"Digest"}', 6),
  ('ANNOUNCEMENT', 'Announcement', '{"th":"ประกาศ","en":"Announcement"}', 7),
  ('WORKFLOW', 'Workflow', '{"th":"ขั้นตอนดำเนินการ","en":"Workflow"}', 8);

CREATE TABLE IF NOT EXISTS notification_channel (
  code               TEXT PRIMARY KEY,
  name_en            TEXT NOT NULL,
  names              TEXT NOT NULL,
  address_format     TEXT NOT NULL,
  description_en     TEXT NOT NULL,
  descriptions       TEXT NOT NULL,
  sort               INTEGER NOT NULL
);
INSERT OR IGNORE INTO notification_channel (code, name_en, names, address_format, description_en, descriptions, sort) VALUES
  ('LINE', 'LINE', '{"th":"ไลน์","en":"LINE"}', 'LINE personal ID or LINE Official Account user ID', 'Dominant messaging channel in Thailand (90%+ penetration). Highest engagement.', '{"th":"ช่องทางรับส่งข้อความหลักในประเทศไทย มีการใช้งานมากกว่า 90 เปอร์เซ็นต์และมีการมีส่วนร่วมสูงสุด","en":"Dominant messaging channel in Thailand (90%+ penetration). Highest engagement."}', 1),
  ('EMAIL', 'Email', '{"th":"อีเมล","en":"Email"}', 'RFC 5322 email address', 'Universal but lower engagement in Thailand. Good for digests and receipts.', '{"th":"ใช้ได้ทั่วไปแต่มีการมีส่วนร่วมในไทยต่ำกว่า เหมาะสำหรับสรุปข้อมูลและใบเสร็จ","en":"Universal but lower engagement in Thailand. Good for digests and receipts."}', 2),
  ('SMS', 'SMS', '{"th":"เอสเอ็มเอส","en":"SMS"}', 'E.164 phone number', 'Reliable delivery; cost per message. Good for OTP and critical alerts.', '{"th":"ส่งถึงผู้รับได้อย่างน่าเชื่อถือ แต่มีค่าใช้จ่ายต่อข้อความ เหมาะสำหรับรหัส OTP และการแจ้งเตือนสำคัญ","en":"Reliable delivery; cost per message. Good for OTP and critical alerts."}', 3),
  ('PUSH', 'Push', '{"th":"การแจ้งเตือนแบบ Push","en":"Push"}', 'Web Push subscription token (PWA)', 'Requires PWA installation. Free at scale; limited reach until adoption grows.', '{"th":"ต้องติดตั้ง PWA ไม่มีค่าใช้จ่ายเมื่อใช้งานในปริมาณมาก แต่การเข้าถึงยังจำกัดจนกว่าจะมีผู้ติดตั้งเพิ่ม","en":"Requires PWA installation. Free at scale; limited reach until adoption grows."}', 4),
  ('IN_APP', 'In-app', '{"th":"การแจ้งเตือนในแอป","en":"In-app"}', 'Internal user ID (delivered when user opens app/site)', 'Always works for signed-in users; only seen when user is active.', '{"th":"ใช้งานได้เสมอสำหรับผู้ที่ลงชื่อเข้าใช้ แต่จะแสดงเมื่อผู้ใช้กำลังใช้งานแอปหรือเว็บไซต์","en":"Always works for signed-in users; only seen when user is active."}', 5);

CREATE TABLE IF NOT EXISTS notification_type (
  code               TEXT PRIMARY KEY,
  category_code      TEXT NOT NULL REFERENCES notification_category(code),
  name_en            TEXT NOT NULL,
  names              TEXT NOT NULL,
  description_en     TEXT NOT NULL,
  descriptions       TEXT NOT NULL,
  sort               INTEGER NOT NULL
);
INSERT OR IGNORE INTO notification_type (code, category_code, name_en, names, description_en, descriptions, sort) VALUES
  ('MATCH_START', 'LIVE', 'Match Start', '{"th":"เริ่มแข่งขัน","en":"Match Start"}', 'A match is starting now', '{"th":"การแข่งขันกำลังจะเริ่มต้น","en":"A match is starting now"}', 1),
  ('MATCH_END', 'LIVE', 'Match End', '{"th":"จบการแข่งขัน","en":"Match End"}', 'A match has ended (final score available)', '{"th":"การแข่งขันจบลงแล้วและมีผลคะแนนสุดท้าย","en":"A match has ended (final score available)"}', 2),
  ('SCORE_UPDATE', 'LIVE', 'Score Update', '{"th":"คะแนนเปลี่ยนแปลง","en":"Score Update"}', 'Score changed during a live match', '{"th":"คะแนนเปลี่ยนแปลงระหว่างการแข่งขันสด","en":"Score changed during a live match"}', 3),
  ('EVENT_REMINDER', 'REMINDER', 'Event Reminder', '{"th":"เตือนความจำอีเวนต์","en":"Event Reminder"}', 'An event is starting soon (24h or 1h before)', '{"th":"อีเวนต์กำลังจะเริ่มในอีกไม่นาน ก่อนเริ่ม 24 ชั่วโมงหรือ 1 ชั่วโมง","en":"An event is starting soon (24h or 1h before)"}', 4),
  ('EVENT_CREATED', 'DISCOVERY', 'Event Created', '{"th":"อีเวนต์ใหม่","en":"Event Created"}', 'A new event was published in your followed scope', '{"th":"มีการเผยแพร่อีเวนต์ใหม่ในขอบเขตที่คุณติดตาม","en":"A new event was published in your followed scope"}', 5),
  ('ROSTER_CHANGE', 'TEAM', 'Roster Change', '{"th":"เปลี่ยนแปลงรายชื่อผู้เล่น","en":"Roster Change"}', 'A followed team''s roster changed', '{"th":"รายชื่อผู้เล่นของทีมที่คุณติดตามมีการเปลี่ยนแปลง","en":"A followed team''s roster changed"}', 6),
  ('REGISTRATION_OPEN', 'REGISTRATION', 'Registration Open', '{"th":"เปิดลงทะเบียน","en":"Registration Open"}', 'Event registration is now open', '{"th":"เปิดรับลงทะเบียนอีเวนต์แล้ว","en":"Event registration is now open"}', 7),
  ('REGISTRATION_CLOSING', 'REGISTRATION', 'Registration Closing Soon', '{"th":"ปิดลงทะเบียนเร็วๆนี้","en":"Registration Closing Soon"}', 'Event registration is about to close', '{"th":"การลงทะเบียนอีเวนต์กำลังจะปิด","en":"Event registration is about to close"}', 8),
  ('DAILY_DIGEST', 'DIGEST', 'Daily Digest', '{"th":"สรุปประจำวัน","en":"Daily Digest"}', 'Daily summary of activity you follow', '{"th":"สรุปกิจกรรมที่คุณติดตามประจำวัน","en":"Daily summary of activity you follow"}', 9),
  ('WEEKLY_DIGEST', 'DIGEST', 'Weekly Digest', '{"th":"สรุปประจำสัปดาห์","en":"Weekly Digest"}', 'Weekly summary of activity you follow', '{"th":"สรุปกิจกรรมที่คุณติดตามประจำสัปดาห์","en":"Weekly summary of activity you follow"}', 10),
  ('ANNOUNCEMENT', 'ANNOUNCEMENT', 'Announcement', '{"th":"ประกาศ","en":"Announcement"}', 'General announcement from an organizer or admin', '{"th":"ประกาศทั่วไปจากผู้จัดการแข่งขันหรือผู้ดูแลระบบ","en":"General announcement from an organizer or admin"}', 11),
  ('APPROVAL_REQUEST', 'WORKFLOW', 'Approval Request', '{"th":"คำขออนุมัติ","en":"Approval Request"}', 'Admin action needed (e.g. pending REFEREE signup)', '{"th":"ต้องดำเนินการโดยผู้ดูแลระบบ เช่น คำขอสมัครผู้ตัดสินที่รออนุมัติ","en":"Admin action needed (e.g. pending REFEREE signup)"}', 12),
  ('APPROVAL_GRANTED', 'WORKFLOW', 'Approval Granted', '{"th":"ได้รับอนุมัติ","en":"Approval Granted"}', 'Your request was approved', '{"th":"คำขอของคุณได้รับการอนุมัติแล้ว","en":"Your request was approved"}', 13),
  ('INVITATION', 'WORKFLOW', 'Invitation', '{"th":"คำเชิญ","en":"Invitation"}', 'You were invited (co-organizer etc)', '{"th":"คุณได้รับคำเชิญ เช่น คำเชิญเป็นผู้ร่วมจัด","en":"You were invited (co-organizer etc)"}', 14);

CREATE TABLE IF NOT EXISTS org_type (
  code               TEXT PRIMARY KEY,
  name_en            TEXT NOT NULL,
  names              TEXT NOT NULL,
  sort               INTEGER NOT NULL
);
INSERT OR IGNORE INTO org_type (code, name_en, names, sort) VALUES
  ('SCHOOL', 'School', '{"th":"โรงเรียน","en":"School"}', 1),
  ('CLUB', 'Club', '{"th":"สโมสร","en":"Club"}', 2),
  ('FEDERATION', 'Federation', '{"th":"สหพันธ์","en":"Federation"}', 3),
  ('GRASSROOTS', 'Grassroots', '{"th":"ชุมชนรากหญ้า","en":"Grassroots"}', 4);

CREATE TABLE IF NOT EXISTS position (
  code               TEXT PRIMARY KEY,
  name_en            TEXT NOT NULL,
  names              TEXT NOT NULL,
  full_name_en       TEXT NOT NULL,
  full_names         TEXT NOT NULL,
  sort               INTEGER NOT NULL
);
INSERT OR IGNORE INTO position (code, name_en, names, full_name_en, full_names, sort) VALUES
  ('PG', 'PG', '{"th":"พอยต์การ์ด","en":"PG"}', 'Point Guard', '{"th":"พอยต์การ์ด","en":"Point Guard"}', 1),
  ('SG', 'SG', '{"th":"ชู้ตติ้งการ์ด","en":"SG"}', 'Shooting Guard', '{"th":"ชู้ตติ้งการ์ด","en":"Shooting Guard"}', 2),
  ('SF', 'SF', '{"th":"สมอลล์ฟอร์เวิร์ด","en":"SF"}', 'Small Forward', '{"th":"สมอลล์ฟอร์เวิร์ด","en":"Small Forward"}', 3),
  ('PF', 'PF', '{"th":"พาวเวอร์ฟอร์เวิร์ด","en":"PF"}', 'Power Forward', '{"th":"พาวเวอร์ฟอร์เวิร์ด","en":"Power Forward"}', 4),
  ('C', 'C', '{"th":"เซ็นเตอร์","en":"C"}', 'Center', '{"th":"เซ็นเตอร์","en":"Center"}', 5);

CREATE TABLE IF NOT EXISTS role (
  code               TEXT PRIMARY KEY,
  name_en            TEXT NOT NULL,
  names              TEXT NOT NULL,
  description_en     TEXT NOT NULL,
  descriptions       TEXT NOT NULL,
  sort               INTEGER NOT NULL
);
INSERT OR IGNORE INTO role (code, name_en, names, description_en, descriptions, sort) VALUES
  ('ADMIN', 'Admin', '{"th":"ผู้ดูแลระบบ","en":"Admin"}', 'Internal staff managing the platform — full write access across all data', '{"th":"เจ้าหน้าที่ภายในที่ดูแลแพลตฟอร์มและมีสิทธิ์เขียนข้อมูลทั้งหมด","en":"Internal staff managing the platform — full write access across all data"}', 1),
  ('ORGANIZER', 'Organizer', '{"th":"ผู้จัดการแข่งขัน","en":"Organizer"}', 'Creates and runs tournaments leagues camps showcases', '{"th":"สร้างและจัดทัวร์นาเมนต์ ลีก ค่ายฝึก และกิจกรรมแสดงผลงาน","en":"Creates and runs tournaments leagues camps showcases"}', 2),
  ('COACH', 'Coach', '{"th":"โค้ช","en":"Coach"}', 'Manages a team — roster registration attendance', '{"th":"จัดการทีม การลงทะเบียนรายชื่อผู้เล่น และการบันทึกการเข้าร่วม","en":"Manages a team — roster registration attendance"}', 3),
  ('PLAYER', 'Player', '{"th":"ผู้เล่น","en":"Player"}', 'Individual athlete — own profile registrations stats', '{"th":"นักกีฬารายบุคคลที่จัดการโปรไฟล์ การลงทะเบียน และสถิติของตนเอง","en":"Individual athlete — own profile registrations stats"}', 4),
  ('SPECTATOR', 'Spectator', '{"th":"ผู้ชม","en":"Spectator"}', 'Read-only follower — parents fans casual viewers', '{"th":"ผู้ติดตามที่อ่านข้อมูลได้อย่างเดียว เช่น ผู้ปกครอง แฟนกีฬา และผู้ชมทั่วไป","en":"Read-only follower — parents fans casual viewers"}', 5),
  ('REFEREE', 'Referee', '{"th":"ผู้ตัดสิน","en":"Referee"}', 'Certified official — score entry match status', '{"th":"เจ้าหน้าที่ผู้ได้รับการรับรองที่บันทึกคะแนนและสถานะการแข่งขัน","en":"Certified official — score entry match status"}', 6);

CREATE TABLE IF NOT EXISTS relation (
  code               TEXT PRIMARY KEY,
  object_type_code   TEXT NOT NULL REFERENCES object_type(code),
  name_en            TEXT NOT NULL,
  names              TEXT NOT NULL,
  via                TEXT NOT NULL,
  source_table       TEXT,
  object_column      TEXT,
  user_column        TEXT,
  filter_column      TEXT,
  filter_value       TEXT,
  through_table      TEXT,
  through_column     TEXT,
  active_to_column   TEXT,
  role_code          TEXT REFERENCES role(code),
  sort               INTEGER NOT NULL
);
INSERT OR IGNORE INTO relation (code, object_type_code, name_en, names, via, source_table, object_column, user_column, filter_column, filter_value, through_table, through_column, active_to_column, role_code, sort) VALUES
  ('OWNER', 'EVENT', 'Owner', '{"th":"เจ้าของ","en":"Owner"}', 'table', 'events', 'id', 'organizer_user_id', NULL, NULL, NULL, NULL, NULL, NULL, 1),
  ('CO_ORGANIZER', 'EVENT', 'Co-organizer', '{"th":"ผู้ร่วมจัด","en":"Co-organizer"}', 'table', 'event_co_organizers', 'event_id', 'user_id', NULL, NULL, NULL, NULL, NULL, NULL, 2),
  ('HEAD_COACH', 'TEAM', 'Head Coach', '{"th":"หัวหน้าผู้ฝึกสอน","en":"Head Coach"}', 'table', 'team_coaches', 'team_id', 'user_id', 'coach_role_code', 'HEAD', NULL, NULL, NULL, NULL, 3),
  ('ASSISTANT_COACH', 'TEAM', 'Assistant Coach', '{"th":"ผู้ช่วยผู้ฝึกสอน","en":"Assistant Coach"}', 'table', 'team_coaches', 'team_id', 'user_id', 'coach_role_code', 'ASSISTANT', NULL, NULL, NULL, NULL, 4),
  ('TEAM_MANAGER', 'TEAM', 'Team Manager', '{"th":"ผู้จัดการทีม","en":"Team Manager"}', 'table', 'team_coaches', 'team_id', 'user_id', 'coach_role_code', 'MANAGER', NULL, NULL, NULL, NULL, 5),
  ('TEAM_PLAYER', 'TEAM', 'Team Player', '{"th":"ผู้เล่นในทีม","en":"Team Player"}', 'table', 'player_teams', 'team_id', 'user_id', NULL, NULL, 'players', 'player_id', 'to_date', NULL, 6),
  ('SELF', 'PLAYER', 'Self', '{"th":"ตัวเอง","en":"Self"}', 'table', 'players', 'id', 'user_id', NULL, NULL, NULL, NULL, NULL, NULL, 7),
  ('GUARDIAN', 'PLAYER', 'Guardian', '{"th":"ผู้ปกครอง","en":"Guardian"}', 'table', 'guardians', 'player_id', 'user_id', NULL, NULL, NULL, NULL, NULL, NULL, 8),
  ('FOLLOWER_PLAYER', 'PLAYER', 'Player Follower', '{"th":"ผู้ติดตาม (ผู้เล่น)","en":"Player Follower"}', 'table', 'subscriptions', 'object_id', 'user_id', 'object_type_code', 'PLAYER', NULL, NULL, NULL, NULL, 9),
  ('FOLLOWER_TEAM', 'TEAM', 'Team Follower', '{"th":"ผู้ติดตาม (ทีม)","en":"Team Follower"}', 'table', 'subscriptions', 'object_id', 'user_id', 'object_type_code', 'TEAM', NULL, NULL, NULL, NULL, 10),
  ('FOLLOWER_EVENT', 'EVENT', 'Event Follower', '{"th":"ผู้ติดตาม (อีเวนต์)","en":"Event Follower"}', 'table', 'subscriptions', 'object_id', 'user_id', 'object_type_code', 'EVENT', NULL, NULL, NULL, NULL, 11),
  ('PLATFORM_ADMIN', 'PLATFORM', 'Platform Admin', '{"th":"ผู้ดูแลแพลตฟอร์ม","en":"Platform Admin"}', 'role', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ADMIN', 12),
  ('ANY_ORGANIZER', 'PLATFORM', 'Any Organizer', '{"th":"ผู้จัดการแข่งขันใดๆ","en":"Any Organizer"}', 'role', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ORGANIZER', 13),
  ('ANY_COACH', 'PLATFORM', 'Any Coach', '{"th":"โค้ชใดๆ","en":"Any Coach"}', 'role', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'COACH', 14),
  ('ANY_PLAYER', 'PLATFORM', 'Any Player', '{"th":"ผู้เล่นใดๆ","en":"Any Player"}', 'role', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'PLAYER', 15),
  ('ANY_REFEREE', 'PLATFORM', 'Any Referee', '{"th":"ผู้ตัดสินใดๆ","en":"Any Referee"}', 'role', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'REFEREE', 16),
  ('ANY_SPECTATOR', 'PLATFORM', 'Any Spectator', '{"th":"ผู้ชมใดๆ","en":"Any Spectator"}', 'role', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'SPECTATOR', 17),
  ('ANY_SIGNED_IN', 'PLATFORM', 'Any Signed-in User', '{"th":"ผู้ที่เข้าสู่ระบบใดๆ","en":"Any Signed-in User"}', 'everyone', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 18),
  ('PUBLIC', 'PLATFORM', 'Public', '{"th":"สาธารณะ","en":"Public"}', 'everyone', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 19);

CREATE TABLE IF NOT EXISTS relationship (
  code               TEXT PRIMARY KEY,
  name_en            TEXT NOT NULL,
  names              TEXT NOT NULL,
  sort               INTEGER NOT NULL
);
INSERT OR IGNORE INTO relationship (code, name_en, names, sort) VALUES
  ('PARENT', 'Parent', '{"th":"ผู้ปกครอง","en":"Parent"}', 1),
  ('GRANDPARENT', 'Grandparent', '{"th":"ปู่ย่าตายาย","en":"Grandparent"}', 2),
  ('GUARDIAN', 'Legal Guardian', '{"th":"ผู้ดูแล","en":"Legal Guardian"}', 3),
  ('OTHER', 'Other', '{"th":"อื่นๆ","en":"Other"}', 4);

CREATE TABLE IF NOT EXISTS skill_tier (
  code               TEXT PRIMARY KEY,
  name_en            TEXT NOT NULL,
  names              TEXT NOT NULL,
  sort               INTEGER NOT NULL
);
INSERT OR IGNORE INTO skill_tier (code, name_en, names, sort) VALUES
  ('PREMIER', 'Premier', '{"th":"พรีเมียร์","en":"Premier"}', 1);

CREATE TABLE IF NOT EXISTS user_status (
  code               TEXT PRIMARY KEY,
  name_en            TEXT NOT NULL,
  names              TEXT NOT NULL,
  description_en     TEXT NOT NULL,
  descriptions       TEXT NOT NULL,
  sort               INTEGER NOT NULL
);
INSERT OR IGNORE INTO user_status (code, name_en, names, description_en, descriptions, sort) VALUES
  ('ACTIVE', 'Active', '{"th":"ใช้งานอยู่","en":"Active"}', 'Account is fully active and can use the platform', '{"th":"บัญชีเปิดใช้งานเต็มรูปแบบและสามารถใช้แพลตฟอร์มได้","en":"Account is fully active and can use the platform"}', 1),
  ('PENDING_APPROVAL', 'Pending Approval', '{"th":"รออนุมัติ","en":"Pending Approval"}', 'Account exists but is waiting for admin approval (e.g. REFEREE awaiting BAT certification verification)', '{"th":"มีบัญชีแล้วแต่กำลังรอการอนุมัติจากผู้ดูแลระบบ เช่น ผู้ตัดสินที่รอการตรวจสอบการรับรอง BAT","en":"Account exists but is waiting for admin approval (e.g. REFEREE awaiting BAT certification verification)"}', 2),
  ('SUSPENDED', 'Suspended', '{"th":"ระงับชั่วคราว","en":"Suspended"}', 'Account is temporarily suspended by admin', '{"th":"บัญชีถูกระงับชั่วคราวโดยผู้ดูแลระบบ","en":"Account is temporarily suspended by admin"}', 3),
  ('DEACTIVATED', 'Deactivated', '{"th":"ปิดใช้งาน","en":"Deactivated"}', 'Account is permanently deactivated', '{"th":"บัญชีถูกปิดใช้งานถาวร","en":"Account is permanently deactivated"}', 4);
-- Foreign keys are added by rebuilding `team`: SQLite cannot add a constraint
-- to an existing table. `event` and `organization` are deliberately left alone
-- for now — organization is Better Auth's table and rebuilding it would put
-- this migration in the way of a future generated schema, and event.province
-- is nullable free text on rows that predate the province list.
PRAGMA defer_foreign_keys = true;

CREATE TABLE team_new (
  id             TEXT PRIMARY KEY,
  name           TEXT NOT NULL,
  names          TEXT NOT NULL DEFAULT '{}',
  org_id         TEXT NOT NULL REFERENCES organization(id),
  age_group_code TEXT NOT NULL REFERENCES age_group(code),
  gender_code    TEXT NOT NULL REFERENCES gender(code),
  created_at     INTEGER NOT NULL,
  updated_at     INTEGER NOT NULL
);

-- `names` is a JSON object keyed by locale. `name` stays beside it as the
-- English pivot: the guaranteed fallback and the column ORDER BY uses.
--
-- Any row whose code is not in the vocabulary would violate the new FK. The
-- copy filters rather than letting the rebuild fail halfway.
INSERT INTO team_new (id, name, names, org_id, age_group_code, gender_code, created_at, updated_at)
SELECT id, name, json_object('en', name), org_id, age_group_code, gender_code, created_at, updated_at
FROM team
WHERE age_group_code IN (SELECT code FROM age_group)
  AND gender_code    IN (SELECT code FROM gender);

DROP TABLE team;
ALTER TABLE team_new RENAME TO team;
CREATE INDEX IF NOT EXISTS team_org_idx ON team(org_id);
