-- GENERATED by `mise run domain:generate` — do not edit.
--
-- ADR 015: the controlled vocabularies are tables, seeded from the
-- remy-sport-biz fixtures. This file used to be hand-typed from those
-- fixtures, which ADR 015 recorded as a known limitation: nothing regenerated
-- one from the other, so a change upstream meant editing a migration by hand
-- and hoping a test noticed. Now the rows come from the fixtures directly and
-- `mise run domain:check` fails when they diverge.
--
-- Display names are NOT columns on these tables. Each vocabulary keeps
-- `name_en` as its pivot — the guaranteed fallback, and the province sort key
-- — and every language including English is a row in `translation`. Adding a
-- language is INSERTs, never a schema change.
--
-- Seeded in the migration rather than through /api/seed, because the foreign
-- keys at the bottom have to be satisfiable the moment they exist.
--
-- Event type codes are lowercased, a deliberate delta from the fixtures that
-- migration 0005 recorded: this repo's published OpenAPI enum is lowercase and
-- changing it would break existing clients for no gain. The mapping is 1:1.

CREATE TABLE IF NOT EXISTS locale (
  code    TEXT PRIMARY KEY,
  name_en TEXT NOT NULL
);
INSERT OR IGNORE INTO locale (code, name_en) VALUES
  ('en', 'English'),
  ('th', 'Thai');

-- One row per term per locale. A new language is INSERTs here and nothing
-- else: no ALTER TABLE, no regenerated type, no consumer changes.
CREATE TABLE IF NOT EXISTS translation (
  table_name  TEXT NOT NULL,
  record_key  TEXT NOT NULL,
  field_name  TEXT NOT NULL,
  locale_code TEXT NOT NULL REFERENCES locale(code),
  value       TEXT NOT NULL,
  PRIMARY KEY (table_name, record_key, field_name, locale_code)
);
INSERT OR IGNORE INTO translation (table_name, record_key, field_name, locale_code, value) VALUES
  ('age_group', 'U10', 'name', 'en', 'Under 10'),
  ('age_group', 'U10', 'name', 'th', 'อายุไม่เกิน 10 ปี'),
  ('age_group', 'U12', 'name', 'en', 'Under 12'),
  ('age_group', 'U12', 'name', 'th', 'อายุไม่เกิน 12 ปี'),
  ('age_group', 'U14', 'name', 'en', 'Under 14'),
  ('age_group', 'U14', 'name', 'th', 'อายุไม่เกิน 14 ปี'),
  ('age_group', 'U16', 'name', 'en', 'Under 16'),
  ('age_group', 'U16', 'name', 'th', 'อายุไม่เกิน 16 ปี'),
  ('age_group', 'U18', 'name', 'en', 'Under 18'),
  ('age_group', 'U18', 'name', 'th', 'อายุไม่เกิน 18 ปี'),
  ('age_group', 'U21', 'name', 'en', 'Under 21'),
  ('age_group', 'U21', 'name', 'th', 'อายุไม่เกิน 21 ปี'),
  ('age_group', 'OPEN', 'name', 'en', 'Open Age'),
  ('age_group', 'OPEN', 'name', 'th', 'เปิดอายุ'),
  ('age_group', 'SENIOR', 'name', 'en', 'Senior'),
  ('age_group', 'SENIOR', 'name', 'th', 'อาวุโส'),
  ('gender', 'M', 'name', 'en', 'Boys'),
  ('gender', 'M', 'name', 'th', 'ชาย'),
  ('gender', 'F', 'name', 'en', 'Girls'),
  ('gender', 'F', 'name', 'th', 'หญิง'),
  ('gender', 'COED', 'name', 'en', 'Co-ed'),
  ('gender', 'COED', 'name', 'th', 'ผสม'),
  ('org_type', 'SCHOOL', 'name', 'en', 'School'),
  ('org_type', 'SCHOOL', 'name', 'th', 'โรงเรียน'),
  ('org_type', 'CLUB', 'name', 'en', 'Club'),
  ('org_type', 'CLUB', 'name', 'th', 'สโมสร'),
  ('org_type', 'FEDERATION', 'name', 'en', 'Federation'),
  ('org_type', 'FEDERATION', 'name', 'th', 'สหพันธ์'),
  ('org_type', 'GRASSROOTS', 'name', 'en', 'Grassroots'),
  ('org_type', 'GRASSROOTS', 'name', 'th', 'ชุมชนรากหญ้า'),
  ('event_type', 'tournament', 'name', 'en', 'Tournament'),
  ('event_type', 'tournament', 'name', 'th', 'การแข่งขันแบบทัวร์นาเมนต์'),
  ('event_type', 'league', 'name', 'en', 'League'),
  ('event_type', 'league', 'name', 'th', 'ลีก'),
  ('event_type', 'camp', 'name', 'en', 'Camp / Clinic'),
  ('event_type', 'camp', 'name', 'th', 'ค่ายฝึก'),
  ('event_type', 'showcase', 'name', 'en', 'Showcase'),
  ('event_type', 'showcase', 'name', 'th', 'การโชว์ผู้เล่น'),
  ('event_format', '5x5', 'name', 'en', '5-on-5'),
  ('event_format', '5x5', 'name', 'th', '5 ต่อ 5'),
  ('event_format', '3x3', 'name', 'en', '3x3'),
  ('event_format', '3x3', 'name', 'th', '3 ต่อ 3'),
  ('province', 'BKK', 'name', 'en', 'Bangkok'),
  ('province', 'BKK', 'name', 'th', 'กรุงเทพมหานคร'),
  ('province', 'NBI', 'name', 'en', 'Nonthaburi'),
  ('province', 'NBI', 'name', 'th', 'นนทบุรี'),
  ('province', 'CMI', 'name', 'en', 'Chiang Mai'),
  ('province', 'CMI', 'name', 'th', 'เชียงใหม่'),
  ('province', 'CRI', 'name', 'en', 'Chiang Rai'),
  ('province', 'CRI', 'name', 'th', 'เชียงราย'),
  ('province', 'NMA', 'name', 'en', 'Nakhon Ratchasima'),
  ('province', 'NMA', 'name', 'th', 'นครราชสีมา'),
  ('province', 'KKN', 'name', 'en', 'Khon Kaen'),
  ('province', 'KKN', 'name', 'th', 'ขอนแก่น'),
  ('province', 'UBN', 'name', 'en', 'Ubon Ratchathani'),
  ('province', 'UBN', 'name', 'th', 'อุบลราชธานี'),
  ('province', 'UDN', 'name', 'en', 'Udon Thani'),
  ('province', 'UDN', 'name', 'th', 'อุดรธานี'),
  ('province', 'CBI', 'name', 'en', 'Chonburi'),
  ('province', 'CBI', 'name', 'th', 'ชลบุรี'),
  ('province', 'PHK', 'name', 'en', 'Phuket'),
  ('province', 'PHK', 'name', 'th', 'ภูเก็ต'),
  ('province', 'SKA', 'name', 'en', 'Songkhla'),
  ('province', 'SKA', 'name', 'th', 'สงขลา'),
  ('province', 'NST', 'name', 'en', 'Nakhon Si Thammarat'),
  ('province', 'NST', 'name', 'th', 'นครศรีธรรมราช'),
  ('province', 'SNI', 'name', 'en', 'Surat Thani'),
  ('province', 'SNI', 'name', 'th', 'สุราษฎร์ธานี'),
  ('province', 'RBR', 'name', 'en', 'Ratchaburi'),
  ('province', 'RBR', 'name', 'th', 'ราชบุรี'),
  ('province', 'PTE', 'name', 'en', 'Pathum Thani'),
  ('province', 'PTE', 'name', 'th', 'ปทุมธานี'),
  ('city', 'BANGKOK', 'name', 'en', 'Bangkok'),
  ('city', 'BANGKOK', 'name', 'th', 'กรุงเทพมหานคร'),
  ('city', 'CHIANG_MAI', 'name', 'en', 'Chiang Mai'),
  ('city', 'CHIANG_MAI', 'name', 'th', 'เชียงใหม่');

CREATE TABLE IF NOT EXISTS age_group (
  code    TEXT PRIMARY KEY,
  name_en TEXT NOT NULL,
  min_age INTEGER,
  max_age INTEGER,
  sort    INTEGER NOT NULL
);
INSERT OR IGNORE INTO age_group (code, name_en, min_age, max_age, sort) VALUES
  ('U10', 'Under 10', NULL, 10, 1),
  ('U12', 'Under 12', NULL, 12, 2),
  ('U14', 'Under 14', NULL, 14, 3),
  ('U16', 'Under 16', NULL, 16, 4),
  ('U18', 'Under 18', NULL, 18, 5),
  ('U21', 'Under 21', NULL, 21, 6),
  ('OPEN', 'Open Age', NULL, NULL, 7),
  ('SENIOR', 'Senior', 30, NULL, 8);

CREATE TABLE IF NOT EXISTS gender (
  code    TEXT PRIMARY KEY,
  name_en TEXT NOT NULL,
  sort    INTEGER NOT NULL
);
INSERT OR IGNORE INTO gender (code, name_en, sort) VALUES
  ('M', 'Boys', 1),
  ('F', 'Girls', 2),
  ('COED', 'Co-ed', 3);

CREATE TABLE IF NOT EXISTS org_type (
  code    TEXT PRIMARY KEY,
  name_en TEXT NOT NULL,
  sort    INTEGER NOT NULL
);
INSERT OR IGNORE INTO org_type (code, name_en, sort) VALUES
  ('SCHOOL', 'School', 1),
  ('CLUB', 'Club', 2),
  ('FEDERATION', 'Federation', 3),
  ('GRASSROOTS', 'Grassroots', 4);

CREATE TABLE IF NOT EXISTS event_type (
  code    TEXT PRIMARY KEY,
  name_en TEXT NOT NULL,
  sort    INTEGER NOT NULL
);
INSERT OR IGNORE INTO event_type (code, name_en, sort) VALUES
  ('tournament', 'Tournament', 1),
  ('league', 'League', 2),
  ('camp', 'Camp / Clinic', 3),
  ('showcase', 'Showcase', 4);

CREATE TABLE IF NOT EXISTS event_format (
  code    TEXT PRIMARY KEY,
  name_en TEXT NOT NULL,
  sort    INTEGER NOT NULL
);
INSERT OR IGNORE INTO event_format (code, name_en, sort) VALUES
  ('5x5', '5-on-5', 1),
  ('3x3', '3x3', 2);

CREATE TABLE IF NOT EXISTS province (
  code    TEXT PRIMARY KEY,
  name_en TEXT NOT NULL
);
INSERT OR IGNORE INTO province (code, name_en) VALUES
  ('BKK', 'Bangkok'),
  ('NBI', 'Nonthaburi'),
  ('CMI', 'Chiang Mai'),
  ('CRI', 'Chiang Rai'),
  ('NMA', 'Nakhon Ratchasima'),
  ('KKN', 'Khon Kaen'),
  ('UBN', 'Ubon Ratchathani'),
  ('UDN', 'Udon Thani'),
  ('CBI', 'Chonburi'),
  ('PHK', 'Phuket'),
  ('SKA', 'Songkhla'),
  ('NST', 'Nakhon Si Thammarat'),
  ('SNI', 'Surat Thani'),
  ('RBR', 'Ratchaburi'),
  ('PTE', 'Pathum Thani');

CREATE TABLE IF NOT EXISTS city (
  code    TEXT PRIMARY KEY,
  name_en TEXT NOT NULL,
  province_code TEXT NOT NULL REFERENCES province(code)
);
INSERT OR IGNORE INTO city (code, name_en, province_code) VALUES
  ('BANGKOK', 'Bangkok', 'BKK'),
  ('CHIANG_MAI', 'Chiang Mai', 'CMI');
-- Foreign keys are added by rebuilding `team`: SQLite cannot add a constraint
-- to an existing table. `event` and `organization` are deliberately left alone
-- for now — organization is Better Auth's table and rebuilding it would put
-- this migration in the way of a future generated schema, and event.province
-- is nullable free text on rows that predate the province list.
PRAGMA defer_foreign_keys = true;

CREATE TABLE team_new (
  id             TEXT PRIMARY KEY,
  name           TEXT NOT NULL,
  org_id         TEXT NOT NULL REFERENCES organization(id),
  age_group_code TEXT NOT NULL REFERENCES age_group(code),
  gender_code    TEXT NOT NULL REFERENCES gender(code),
  created_at     INTEGER NOT NULL,
  updated_at     INTEGER NOT NULL
);

-- `name` is the English pivot and stays on the row. Thai — and any other
-- language — is a `translation` row keyed ('team', id, 'name', locale), the
-- same rule the vocabularies follow. That is why `name_th` is not rebuilt.
--
-- Any row whose code is not in the vocabulary would violate the new FK. The
-- copy filters rather than letting the rebuild fail halfway.
INSERT INTO team_new (id, name, org_id, age_group_code, gender_code, created_at, updated_at)
SELECT id, name, org_id, age_group_code, gender_code, created_at, updated_at
FROM team
WHERE age_group_code IN (SELECT code FROM age_group)
  AND gender_code    IN (SELECT code FROM gender);

DROP TABLE team;
ALTER TABLE team_new RENAME TO team;
CREATE INDEX IF NOT EXISTS team_org_idx ON team(org_id);
