-- GENERATED by `mise run domain:generate` — do not edit.
--
-- The domain model for every reference vocabulary in remy-sport-biz. Add a file to the
-- fixtures' reference/ folder and regenerate; nothing here is hand-maintained,
-- and `mise run domain:check` fails when this goes stale.
--
-- Display names live in JSON columns keyed by locale — `names`, `descriptions`
-- — never a column per language. Each keeps its `*_en` pivot beside it: NOT
-- NULL, so there is always something renderable, and sortable without reaching
-- into JSON.
--

-- Every entity and join table the Product Owner defines that this repo does not
-- already own. `user` and `organization` are Better Auth's; `event` and
-- `team` carry columns the fixtures do not model. Everything else is here,
-- with the foreign keys the fixtures imply.
--
-- Rows are loaded by /api/seed rather than inlined, because `user_id` and
-- `org_id` have to be translated from the fixtures' ids to the ones Better
-- Auth generates.

CREATE TABLE IF NOT EXISTS division (
  id                   TEXT PRIMARY KEY,
  age_group_code       TEXT NOT NULL REFERENCES age_group(code),
  gender_code          TEXT NOT NULL REFERENCES gender(code),
  skill_tier_code      TEXT REFERENCES skill_tier(code),
  names                TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS player (
  id                   TEXT PRIMARY KEY,
  user_id              TEXT REFERENCES user(id),
  jersey_number        INTEGER NOT NULL,
  position_code        TEXT NOT NULL REFERENCES position(code),
  dob                  TEXT NOT NULL,
  names                TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS venue (
  id                   TEXT PRIMARY KEY,
  address              TEXT NOT NULL,
  city_code            TEXT NOT NULL REFERENCES city(code),
  province_code        TEXT NOT NULL REFERENCES province(code),
  names                TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS eventCoOrganizer (
  event_id             TEXT NOT NULL REFERENCES event(id),
  user_id              TEXT NOT NULL REFERENCES user(id),
  added_at             TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS eventPlayer (
  event_id             TEXT NOT NULL REFERENCES event(id),
  player_id            TEXT NOT NULL REFERENCES player(id),
  registered_at        TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS eventTeam (
  event_id             TEXT NOT NULL REFERENCES event(id),
  team_id              TEXT NOT NULL REFERENCES team(id),
  division_id          TEXT NOT NULL REFERENCES division(id),
  registered_at        TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS eventVenue (
  event_id             TEXT NOT NULL REFERENCES event(id),
  venue_id             TEXT NOT NULL REFERENCES venue(id),
  is_primary           INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS guardian (
  user_id              TEXT NOT NULL REFERENCES user(id),
  player_id            TEXT NOT NULL REFERENCES player(id),
  relationship_code    TEXT NOT NULL REFERENCES relationship(code)
);

CREATE TABLE IF NOT EXISTS playerTeam (
  player_id            TEXT NOT NULL REFERENCES player(id),
  team_id              TEXT NOT NULL REFERENCES team(id),
  from_date            TEXT NOT NULL,
  to_date              TEXT
);

CREATE TABLE IF NOT EXISTS subscription (
  user_id              TEXT NOT NULL REFERENCES user(id),
  object_type_code     TEXT NOT NULL REFERENCES object_type(code),
  object_id            TEXT NOT NULL,
  subscribed_at        TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS teamCoach (
  team_id              TEXT NOT NULL REFERENCES team(id),
  user_id              TEXT NOT NULL REFERENCES user(id),
  coach_role_code      TEXT NOT NULL REFERENCES coach_role(code)
);

CREATE TABLE IF NOT EXISTS userNotificationChannel (
  user_id              TEXT NOT NULL REFERENCES user(id),
  channel_code         TEXT NOT NULL REFERENCES notification_channel(code),
  address              TEXT NOT NULL,
  address_label        TEXT NOT NULL,
  is_enabled           INTEGER NOT NULL,
  verified_at          TEXT
);

CREATE TABLE IF NOT EXISTS userNotificationPreference (
  user_id              TEXT NOT NULL REFERENCES user(id),
  notification_type_code TEXT NOT NULL REFERENCES notification_type(code),
  channel_code         TEXT NOT NULL REFERENCES notification_channel(code),
  is_enabled           INTEGER NOT NULL
);
