import { OpenAPIGenerator } from "@orpc/openapi"
import { router } from "../../src/api/index.ts"
import { SCHEMA_CONVERTERS, SPEC_OPTIONS, withDomainTags } from "../../src/api/openapi.ts"
import { policyOf } from "../../src/api/base.ts"
import { originOf, resolveTarget } from "../lib/cloudflare.ts"

/**
 * The published OpenAPI document, generated from the router.
 *
 * **No server, and no fetch.** The generator is called directly, on the same
 * `router` the Worker serves and the same options object `src/api/openapi.ts`
 * hands its handler — so the committed snapshot and the deployed
 * `/api/openapi.json` are one description, not two that happen to agree.
 *
 * Fetching a deployment's spec would have been easier and wrong: the check
 * would then pass whenever the file matched whatever was last deployed, which
 * is a check reporting the state of a deploy rather than the state of the
 * tree. `tests/repo/manifest.test.ts` makes that mistake today and is on the
 * plan's follow-up list because of it.
 *
 *   bun run ops openapi                      print the public document
 *   bun run ops openapi --internal            print it with dev included
 *   bun run ops openapi --check --env staging compare a deployment to this tree
 *
 * **There is no `--write`, and no file.** The app publishes the document itself
 * at `/api/openapi.json`, so there is nothing to keep a copy of. The earlier
 * plan pointed a `--write` at `sites/help/schema/openapi.json`; that file is
 * the *help site's own* retrieval API — `/help-index.json` and
 * `/llms-full.txt` — and writing this document into it deleted both, measured
 * at 12,850 insertions against 5 deletions. A path to it left in this file is
 * how the next person makes the same mistake, so there is no path to it.
 *
 * `sites/help-tools/` keeps its curated six read-only operations at
 * `/application-openapi.json` on its own origin. Nothing at the app origin is
 * ever named that. Generating those six from this router instead of the
 * hand-kept list in `application.mjs` is F5's first task.
 */

/**
 * What the help site publishes: everything a reader outside this repo can call.
 *
 * The dev endpoints and the infrastructure ones are dropped. They are not
 * secrets — the deployed `/api/doc` shows them, which is the point, so whoever
 * is on call can see `dev.outbox` on staging — but a published reference that
 * lists a seed route reads as an invitation, and on production those
 * operations answer 404 anyway.
 *
 * The audience comes from the **policy**, which is the thing that already
 * decides whether the endpoint exists at all — `dev(capability)` and
 * `infrastructure(why)` both mark a procedure as not a domain object, and
 * `tests/repo/authz.test.ts` proves every procedure carries a mark. So nothing
 * can join this router without declaring which side of this line it is on, and
 * no tag has to be remembered.
 *
 * The domain tag is the other half and is added over the finished document by
 * `withDomainTags` — see src/api/openapi.ts for why that belongs to generation
 * rather than to the builder.
 */
export async function generate(audience: "public" | "internal" = "public") {
  const generator = new OpenAPIGenerator({ schemaConverters: SCHEMA_CONVERTERS })
  return withDomainTags(await generator.generate(router, {
    ...SPEC_OPTIONS,
    ...(audience === "public"
      ? {
          exclude: (procedure: unknown) => {
            const middlewares = ((procedure as { "~orpc"?: { middlewares?: unknown[] } })["~orpc"]
              ?.middlewares ?? []) as unknown[]
            return middlewares.map(policyOf).some((policy) => policy?.kind === "infrastructure")
          },
        }
      : {}),
  }))
}

/** Every operation a document describes, as "METHOD /path". */
export function operationsOf(document: { paths?: Record<string, unknown> }): string[] {
  return Object.entries(document.paths ?? {})
    .flatMap(([path, methods]) =>
      Object.keys((methods ?? {}) as Record<string, unknown>).map((m) => `${m.toUpperCase()} ${path}`),
    )
    .sort()
}

const argv = process.argv.slice(2)

if (argv.includes("--check")) {
  /**
   * Does the deployment describe what this tree describes?
   *
   * Compared as a set of operations rather than byte-for-byte. The served
   * document carries `servers` for its own origin and is generated by the
   * reference plugin, which does not run `withDomainTags`, so the bytes differ
   * for reasons that say nothing about the contract. What matters is whether
   * an operation exists in one and not the other — which is what "the
   * deployment is behind" and "somebody published something this tree does not
   * have" both look like.
   *
   * The edge is fetched here, and only here. The *document* is still generated
   * from the router — this compares a deployment against the tree, it does not
   * take a deployment's word for what the tree says.
   */
  const origin = originOf(resolveTarget(argv))
  const served = (await (await fetch(`${origin}/api/openapi.json`)).json()) as {
    paths?: Record<string, unknown>
  }
  // The served document is the internal one: the handler applies no audience
  // filter, so it describes everything the Worker will answer.
  const here = operationsOf(await generate("internal"))
  const there = operationsOf(served)

  const missing = here.filter((op) => !there.includes(op))
  const extra = there.filter((op) => !here.includes(op))
  const paths = new Set(here.map((op) => op.split(" ")[1]))
  if (missing.length || extra.length) {
    console.error(`openapi: ${origin} does not describe what this tree describes.\n`)
    for (const op of missing) console.error(`  – ${op}  in the tree, not on the deployment`)
    for (const op of extra) console.error(`  + ${op}  on the deployment, not in the tree`)
    console.error("\n  Usually this means the deployment is behind. Deploy, or say why not.")
    process.exit(1)
  }
  // Both numbers, because they are different things and one alone invites the
  // question: an operation is a method on a path, so /dev/outbox is two.
  console.log(
    `openapi: ${origin} describes the same ${here.length} operations ` +
      `across ${paths.size} paths as this tree (internal audience — the served ` +
      `document is unfiltered)`,
  )
} else {
  const audience = argv.includes("--internal") ? "internal" : "public"
  /**
   * Written, then awaited until it has actually gone.
   *
   * The document is half a megabyte and a pipe holds 64 KB. Both `console.log`
   * and a synchronous write to fd 1 delivered exactly 65,536 bytes through a
   * pipe while a redirect to a file delivered all 510,058 — the process was
   * exiting with the rest unflushed, so `ops openapi | jq` got truncated JSON
   * and a parse error rather than an answer. Awaiting the write callback is
   * what makes the process outlive its own output.
   */
  const document = JSON.stringify(await generate(audience), null, 2) + "\n"
  await new Promise<void>((resolve, reject) => {
    process.stdout.write(document, (error) => (error ? reject(error) : resolve()))
  })
}
