#!/usr/bin/env bun
// Codegen: read remy-sport-biz/data/seed/*.csv → emit src/generated/policies.ts.
//
// Grouping strategy: collapse permissions.csv rows by (action_code, event_type_code) so
// each unique (action, optional-subtype) pair becomes one `permit` with the granting
// relations OR'd together. This keeps the policy count proportional to actions × subtypes
// instead of raw permission rows.
//
// Relation → Cedar encoding:
//   PLATFORM relations  → `principal in PlatformRole::"<lower>"`
//   resource relations  → `principal in resource.<attr>` where attr is the lowercased relation code
//   PUBLIC              → no condition (open)
//   ANY_SIGNED_IN       → `principal is User`

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";

const SEED = resolve(import.meta.dir, "../../../../remy-sport-biz/data/seed");
const OUT = resolve(import.meta.dir, "../src/generated/policies.ts");

type Row = Record<string, string>;
function parseCsv(path: string): Row[] {
  const text = readFileSync(path, "utf8").trim();
  const [header, ...lines] = text.split("\n");
  const cols = header.split(",");
  return lines.map((line) => {
    const cells = line.split(",");
    return Object.fromEntries(cols.map((c, i) => [c, cells[i] ?? ""]));
  });
}

const actions = parseCsv(`${SEED}/actions.csv`);
const objectTypes = parseCsv(`${SEED}/object_types.csv`).map((r) => r.code);
const permissions = parseCsv(`${SEED}/permissions.csv`);

// action_code → object_type_code
const actionObjectType = new Map(actions.map((a) => [a.code, a.object_type_code]));

// Cedar entity type for each object_type_code
const cedarType: Record<string, string> = {
  EVENT: "Event", TEAM: "Team", PLAYER: "Player",
  ORG: "Org", DIVISION: "Division", PLATFORM: "Platform",
};

// PLATFORM relations encode as principal-in-role; resource relations encode as principal-in-attr.
const PLATFORM_RELATIONS = new Set([
  "PLATFORM_ADMIN", "ANY_ORGANIZER", "ANY_COACH", "ANY_PLAYER",
  "ANY_REFEREE", "ANY_SPECTATOR", "ANY_SIGNED_IN", "PUBLIC",
]);
const platformRoleSlug = (rel: string): string =>
  rel === "PLATFORM_ADMIN" ? "admin" :
  rel === "ANY_ORGANIZER"  ? "organizer" :
  rel === "ANY_COACH"      ? "coach" :
  rel === "ANY_PLAYER"     ? "player" :
  rel === "ANY_REFEREE"    ? "referee" :
  rel === "ANY_SPECTATOR"  ? "spectator" : "any";

// resource-attribute name for an object-relation (lowercased, simple pluralisation)
const attrName = (rel: string): string => {
  const lower = rel.toLowerCase();
  if (rel === "SELF") return ""; // SELF handled specially
  if (lower.endsWith("s") || lower.endsWith("er")) return lower + "s";
  return lower + "s";
};

function clauseFor(rel: string, objectType: string): string | null {
  if (rel === "PUBLIC") return "true";
  if (rel === "ANY_SIGNED_IN") return "principal is User";
  if (PLATFORM_RELATIONS.has(rel)) return `principal in PlatformRole::"${platformRoleSlug(rel)}"`;
  if (rel === "SELF") return "principal == resource.user";
  return `principal in resource.${attrName(rel)}`;
}

// Group permissions by (action, event_type)
const groups = new Map<string, { action: string; eventType: string; relations: string[] }>();
for (const p of permissions) {
  const key = `${p.action_code}|${p.event_type_code}`;
  let g = groups.get(key);
  if (!g) { g = { action: p.action_code, eventType: p.event_type_code, relations: [] }; groups.set(key, g); }
  if (!g.relations.includes(p.relation_code)) g.relations.push(p.relation_code);
}

const policies: string[] = [];
let nextId = 0;
for (const g of groups.values()) {
  const objType = actionObjectType.get(g.action) ?? "PLATFORM";
  const cedarObj = cedarType[objType] ?? "Platform";
  const clauses = g.relations.map((r) => clauseFor(r, objType)).filter((c): c is string => !!c);
  if (clauses.length === 0) continue;
  const containsTrue = clauses.includes("true");
  const condition = containsTrue ? "" : clauses.join(" ||\n    ");
  const subtypeGuard = g.eventType ? `\n  ${condition ? "&&" : ""} resource.type == "${g.eventType}"` : "";

  const id = `p${nextId++}_${g.action}${g.eventType ? "_" + g.eventType : ""}`;
  const whenBlock = condition || subtypeGuard
    ? ` when {\n    ${condition}${subtypeGuard}\n  }`
    : "";

  policies.push(
    `@id("${id}")\npermit (\n  principal,\n  action == Action::"${g.action}",\n  resource is ${cedarObj}\n)${whenBlock};`
  );
}

const out = `// AUTO-GENERATED by scripts/regen-cedar.ts — do not edit.
// Source: remy-sport-biz/data/seed/{actions,object_types,permissions,relations}.csv
// Permissions: ${permissions.length} CSV rows → ${policies.length} grouped permit policies.

export const POLICIES = \`
${policies.join("\n\n")}
\`.trim();

export const POLICY_COUNT = ${policies.length};
`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, out);
console.log(`Wrote ${OUT}`);
console.log(`Permissions: ${permissions.length} → Policies: ${policies.length}`);
console.log(`Bytes: ${out.length}`);
