import { sqliteTable, text, integer, primaryKey } from "drizzle-orm/sqlite-core"

/**
 * Controlled vocabularies (ADR 015), copied from remy-sport-biz/data/seed.
 *
 * These were Zod enums hand-written in src/routes/*.ts and nothing else. The
 * database accepted anything, so a bad code could arrive from the seed route, a
 * migration, or any future writer that did not go through those routes — and
 * the enum itself was an unchecked fork of the PO's data.
 *
 * Now they are tables with foreign keys, and `mise run test` asserts the API
 * enums still match their rows. Seeded in the migration rather than /api/seed,
 * because the foreign keys have to be satisfiable the moment they exist.
 */
import { user, organization } from "./auth-schema"

/**
 * Application tables — hand-written, and the only schema file that is.
 *
 * Better Auth's tables live in `auth-schema.ts`, which is generated by
 * `mise run auth:schema:generate` and must not be edited by hand. Keeping the
 * two apart is what makes regeneration safe: it can never clobber app tables,
 * and app tables can never silently drift from what Better Auth expects.
 */
/**
 * Columns follow the canonical `events` definition in
 * remy-sport-biz/data/seed/schema.md. Migration 0005 explains the two names
 * that deliberately differ (`name` for `name_en`, `created_by` for
 * `organizer_user_id`) and why `org_id` is absent.
 */
export const event = sqliteTable("event", {
  id: text("id").primaryKey(),
  // The English pivot. Other languages are `translation` rows keyed
  // ('event', id, 'name', locale) — see migration 0010 and domain/localized.ts.
  name: text("name").notNull(), // canonical: name_en
  type: text("type").notNull(), // tournament, league, camp, showcase
  format: text("format").notNull().default("5x5"), // 5x5 | 3x3
  description: text("description"),
  // ISO 8601 date strings (YYYY-MM-DD), per the biz schema's date convention.
  // Nullable because rows predating migration 0005 have no value; the API
  // defaults them on create.
  startDate: text("start_date"),
  endDate: text("end_date"),
  cityCode: text("city_code"), // canonical city code, e.g. BANGKOK
  provinceCode: text("province_code"), // canonical: 3-letter code, e.g. BKK
  isFibaCertified: integer("is_fiba_certified", { mode: "boolean" })
    .notNull()
    .default(false),
  createdBy: text("created_by") // canonical: organizer_user_id
    .notNull()
    .references(() => user.id),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
})

/**
 * Team profiles, following canonical `teams` in
 * remy-sport-biz/data/seed/schema.md. Migration 0006 explains why `org_id`
 * points at Better Auth's `organization` rather than a second orgs table, and
 * why the two `_code` columns are plain text validated at the API boundary.
 */
export const team = sqliteTable("team", {
  id: text("id").primaryKey(),
  // The English pivot. Other languages are `translation` rows keyed
  // ('team', id, 'name', locale) — see migration 0010 and domain/localized.ts.
  name: text("name").notNull(), // canonical: name_en
  orgId: text("org_id")
    .notNull()
    .references(() => organization.id),
  // Foreign keys as of migration 0009 — the database rejects a code outside the
  // vocabulary, which it previously accepted from any writer.
  ageGroupCode: text("age_group_code")
    .notNull()
    .references(() => ageGroup.code),
  genderCode: text("gender_code")
    .notNull()
    .references(() => gender.code),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
})

/** U10 … SENIOR. `sort` exists because age order is not code order. */
export const ageGroup = sqliteTable("age_group", {
  code: text("code").primaryKey(),
  nameEn: text("name_en").notNull(),
  minAge: integer("min_age"),
  maxAge: integer("max_age"),
  sort: integer("sort").notNull(),
})

export const gender = sqliteTable("gender", {
  code: text("code").primaryKey(),
  nameEn: text("name_en").notNull(),
  sort: integer("sort").notNull(),
})

export const orgType = sqliteTable("org_type", {
  code: text("code").primaryKey(),
  nameEn: text("name_en").notNull(),
  sort: integer("sort").notNull(),
})

/** Lowercase, unlike the biz fixtures — see migration 0005 and 0009. */
export const eventType = sqliteTable("event_type", {
  code: text("code").primaryKey(),
  nameEn: text("name_en").notNull(),
  sort: integer("sort").notNull(),
})

export const eventFormat = sqliteTable("event_format", {
  code: text("code").primaryKey(),
  nameEn: text("name_en").notNull(),
  sort: integer("sort").notNull(),
})

/** The PO's 15-province starter set, not all 77. */
export const province = sqliteTable("province", {
  code: text("code").primaryKey(),
  nameEn: text("name_en").notNull(),
})

/** Cities, keyed by code. A city belongs to exactly one province. */
export const city = sqliteTable("city", {
  code: text("code").primaryKey(),
  nameEn: text("name_en").notNull(),
  provinceCode: text("province_code")
    .notNull()
    .references(() => province.code),
})

/**
 * The languages the product ships in, from the PO's locales fixture.
 *
 * A language is a row here and rows in `translation` — never a column
 * anywhere. See migration 0009.
 */
export const locale = sqliteTable("locale", {
  code: text("code").primaryKey(),
  nameEn: text("name_en").notNull(),
})

/**
 * Display strings for the controlled vocabularies, one row per term per locale.
 *
 * Keyed exactly as the PO's translations fixture is, except that `recordKey`
 * holds this repo's code — event types are lowercase here. Every language
 * including English has a row, so rendering in a locale is one uniform join.
 */
export const translation = sqliteTable(
  "translation",
  {
    tableName: text("table_name").notNull(),
    recordKey: text("record_key").notNull(),
    fieldName: text("field_name").notNull(),
    localeCode: text("locale_code")
      .notNull()
      .references(() => locale.code),
    value: text("value").notNull(),
  },
  (t) => [primaryKey({ columns: [t.tableName, t.recordKey, t.fieldName, t.localeCode] })],
)
