import { relations } from "drizzle-orm"
import { sqliteTable, text, integer, index } from "drizzle-orm/sqlite-core"
import type { Names } from "../domain/names"
import { org } from "./fixtures-schema"
/**
 * The vocabularies are declared ON the columns, not restated at the boundary.
 *
 * `text("type_code")` yields `string`, so `createInsertSchema` would accept
 * "U99" and every read needed a cast back to the union. `{ enum }` narrows
 * `$inferSelect` to the literal codes and makes drizzle-zod derive a real
 * `z.enum`, so the vocabulary is enforced by the type system as well as by the
 * foreign keys. These constants are GENERATED from the PO's fixtures, so a code
 * added upstream appears here with nothing edited.
 *
 * TypeScript-level only: the emitted SQL is unchanged and no migration is
 * needed. It does not constrain SQLite — `event.type_code` still has no foreign
 * key, so a writer bypassing the API can still store nonsense.
 */
import {
  AGE_GROUP_CODES,
  CITY_CODES,
  EVENT_FORMAT_CODES,
  EVENT_TYPE_CODES,
  GENDER_CODES,
} from "../domain/vocabularies"

/**
 * Display names, keyed by locale: {"en":"Boys","th":"ชาย"}.
 *
 * One column, not one per language and not a join table. A name is a property
 * of the row, and keeping it one is what lets it cross the whole stack with no
 * mapping code: drizzle types it here, drizzle-zod derives the response schema
 * from this table, oRPC publishes that schema, and the client infers it.
 * Adding a language edits a value.
 *
 * Every table that has this also keeps a NOT NULL `name`/`name_en` pivot
 * beside it — the guaranteed fallback, and what SQL sorts by.
 */
const localeNames = () => text("names", { mode: "json" }).$type<Names>().notNull()

/**
 * Controlled vocabularies (ADR 015), copied from remy-sport-biz/domain/model.
 *
 * These were Zod enums hand-written in src/routes/*.ts and nothing else. The
 * database accepted anything, so a bad code could arrive from the seed route, a
 * migration, or any future writer that did not go through those routes — and
 * the enum itself was an unchecked fork of the PO's data.
 *
 * Now they are tables with foreign keys, and `mise run test` asserts the API
 * enums still match their rows. Seeded in the migration rather than /api/seed,
 * because the foreign keys have to be satisfiable the moment they exist.
 */
import { user } from "./auth-schema"

/**
 * Application tables — hand-written, and the only schema file that is.
 *
 * Better Auth's tables live in `auth-schema.ts`, which is generated by
 * `mise run auth:schema:generate` and must not be edited by hand. Keeping the
 * two apart is what makes regeneration safe: it can never clobber app tables,
 * and app tables can never silently drift from what Better Auth expects.
 */
/**
 * Columns follow the PO's canonical `events` shape — see the event entities in
 * [src/domain/model/entities.ts](../domain/model/entities.ts), copied verbatim
 * from remy-sport-biz. Migration 0005 explains the two names
 * that deliberately differ (`name` for `name_en`, `created_by` for
 * `organizer_user_id`) and why `org_id` is absent.
 */
export const event = sqliteTable("event", {
  id: text("id").primaryKey(),
  name: text("name").notNull(), // canonical: name_en — the pivot
  names: localeNames(),
  typeCode: text("type_code", { enum: EVENT_TYPE_CODES }).notNull(),
  formatCode: text("format_code", { enum: EVENT_FORMAT_CODES }).notNull().default("5x5"),
  description: text("description"),
  // ISO 8601 date strings (YYYY-MM-DD), per the biz schema's date convention.
  // Nullable because rows predating migration 0005 have no value; the API
  // defaults them on create.
  startDate: text("start_date"),
  endDate: text("end_date"),
  /**
   * The venue's clock, as an IANA name — "Asia/Bangkok".
   *
   * `starts_at` on a game is an instant in UTC, which is unambiguous but not
   * enough: a schedule has to say what time the game starts *where it is
   * played*, and only the event knows that. A viewer in another zone then sees
   * both, so neither is a guess.
   *
   * Not derived from `city_code`. A city is where an event is listed; the venue
   * is where it is played, and a federation running a fixture abroad breaks the
   * shortcut. Nullable for rows that predate this, which fall back to the
   * viewer's own zone rather than to a zone somebody assumed.
   */
  timezone: text("timezone"),
  cityCode: text("city_code", { enum: CITY_CODES }),
  provinceCode: text("province_code"), // canonical: 3-letter code, e.g. BKK
  isFibaCertified: integer("is_fiba_certified", { mode: "boolean" })
    .notNull()
    .default(false),
  /**
   * The organisation running this event, where one is.
   *
   * The model always carried it and this table had no column, so "Assumption
   * College runs the invitational" was dropped at seed time and the page could
   * only name the organiser as a person. Nullable because a league can be run by
   * an individual — evt_002 is, and its `orgId` is null in the fixtures.
   */
  orgId: text("org_id").references(() => org.id),
  organizerUserId: text("organizer_user_id")
    .notNull()
    .references(() => user.id),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
}, (t) => [
  // Created by migration 0005. Same reason as team_org_idx above.
  index("event_city_code_idx").on(t.cityCode),
  /**
   * The reminder sweep's only filter.
   *
   * `sendDueReminders` selects events whose `startDate` falls in a window,
   * twice per run, and the plan for that was `SCAN event` — a full table scan.
   * That costs nothing at four events, and the cron moved from hourly to every
   * five minutes in the same change: twelve times as many scans of a table that
   * only grows.
   *
   * Cheap now and awkward later. The sweep is the one query here whose
   * frequency is set by a schedule rather than by how many people are using the
   * app, so it is the one that degrades with nobody doing anything.
   */
  index("event_start_date_idx").on(t.startDate),
])

/**
 * Team profiles, following the PO's canonical `teams` shape in
 * [src/domain/model/entities.ts](../domain/model/entities.ts). Migration 0006
 * explains why `org_id`
 * points at Better Auth's `organization` rather than a second orgs table, and
 * why the two `_code` columns are plain text validated at the API boundary.
 */
export const team = sqliteTable("team", {
  id: text("id").primaryKey(),
  name: text("name").notNull(), // canonical: name_en — the pivot
  names: localeNames(),
  orgId: text("org_id")
    .notNull()
    .references(() => org.id),
  // Foreign keys as of migration 0009 — the database rejects a code outside the
  // vocabulary, which it previously accepted from any writer.
  ageGroupCode: text("age_group_code", { enum: AGE_GROUP_CODES })
    .notNull()
    .references(() => ageGroup.code),
  genderCode: text("gender_code", { enum: GENDER_CODES })
    .notNull()
    .references(() => gender.code),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
}, (t) => [
  // Declared because the schema is now the source drizzle-kit diffs against:
  // an index the database has and this file does not know about is one a
  // generated migration would quietly drop. Created by migration 0006.
  index("team_org_idx").on(t.orgId),
])


/** U10 … SENIOR. `sort` exists because age order is not code order. */
/**
 * The controlled vocabularies are GENERATED from the PO's fixtures.
 *
 * There were eight of them written out here by hand, which meant every new
 * vocabulary upstream needed a table typed out again, in step, by someone who
 * remembered to. There are twenty now and none of them are written here — see
 * scripts/domain-generate.ts and `mise run check:domain`.
 */
export * from "./vocabularies-schema"

// Imported as well as re-exported: `export *` publishes them but does not bind
// them here, and the relations and foreign keys below need the bindings.
import { ageGroup, city, gender, province } from "./vocabularies-schema"


/**
 * Relations, so reads are declarative.
 *
 * `drizzle(c.env.DB, { schema })` already passes the schema, so `db.query`
 * works the moment these exist — the routes were writing manual `leftJoin`s
 * and hand-picking columns only because nothing here declared the shape.
 */
export const teamRelations = relations(team, ({ one }) => ({
  org: one(org, { fields: [team.orgId], references: [org.id] }),
  ageGroup: one(ageGroup, { fields: [team.ageGroupCode], references: [ageGroup.code] }),
  gender: one(gender, { fields: [team.genderCode], references: [gender.code] }),
}))

export const eventRelations = relations(event, ({ one }) => ({
  organizer: one(user, { fields: [event.organizerUserId], references: [user.id] }),
  city: one(city, { fields: [event.cityCode], references: [city.code] }),
  province: one(province, { fields: [event.provinceCode], references: [province.code] }),
}))

export const cityRelations = relations(city, ({ one }) => ({
  province: one(province, { fields: [city.provinceCode], references: [province.code] }),
}))
