/**
 * Single import point for the Drizzle schema.
 *
 * Split in two on purpose:
 *   - `auth-schema.ts` — GENERATED by `mise run auth:schema:generate` from
 *     `src/auth.config.ts`. Never edit it; your changes will be overwritten.
 *   - `app-schema.ts`  — hand-written application tables.
 *
 * This file used to hold both, hand-maintained. That is how the schema drifted
 * from what Better Auth expects (see ADR 006 and AGENTS.md) — a class of bug
 * that only shows up as an authentication failure at runtime.
 */
export * from "./auth-schema"
export * from "./app-schema"
