/**
 * Single import point for the Drizzle schema.
 *
 * Split in two on purpose:
 *   - `auth-schema.ts` — GENERATED by `bun scripts/ops/auth-schema.ts --write` from
 *     `src/auth.config.ts`. Never edit it; your changes will be overwritten.
 *   - `app-schema.ts`  — hand-written application tables.
 *
 * This file used to hold both, hand-maintained. That is how the schema drifted
 * from what Better Auth expects (see ADR 006 and AGENTS.md) — a class of bug
 * that only shows up as an authentication failure at runtime.
 */
export * from "./auth-schema"
export * from "./app-schema"
// The Product Owner's domain model: players, divisions, venues and every join
// table between them. AUTHORED — these tables are the root of the chain, and
// everything above them is derived; see the header of fixtures-schema.ts.
//
// This line said "GENERATED", naming a domain-generate script until 2026-09-10.
// That script no longer exists, and the claim was the opposite of what the file
// it describes says in its first line. Generation stopped on 2026-08-27 because
// deriving the schema from the data inverted the dependency; the comment did
// not follow, and nothing could tell, because nothing type-checks a comment.
export * from "./fixtures-schema"

import type { SQLiteTable } from "drizzle-orm/sqlite-core"
import * as auth from "./auth-schema"
import * as app from "./app-schema"
import * as fixtures from "./fixtures-schema"
import { FIXTURE_TABLE } from "../domain/vocabularies"

/** The SQL name of every table a module exports. */
type TableNames<M> = { [K in keyof M]: M[K] extends SQLiteTable ? M[K]["_"]["name"] : never }[keyof M]
type SqlTable = TableNames<typeof auth> | TableNames<typeof app> | TableNames<typeof fixtures>

/**
 * Every SQL name the table map holds is a table this schema declares.
 *
 * A compile error, not a check. `ORG` once named `organizations` after the
 * organization plugin was removed and its table dropped, so every write to an
 * organisation answered 500 and only a test caught it; a repo test then
 * guarded it for a while. The map is literal and the model is literal, so the
 * type system can hold both ends: the model's side in src/domain/vocabularies.ts,
 * the schema's side here.
 */
FIXTURE_TABLE satisfies Record<keyof typeof FIXTURE_TABLE, SqlTable>
