-- GENERATED by `mise run seed:sql` — do not edit.
--
-- The Product Owner's model, as data rather than as an HTTP call. Applied by
-- the worker tests directly and by POST /api/seed at runtime, so both get the
-- same database. See scripts/seed-sql.ts for why that distinction matters.

-- Users. `role` is the platform role; `biz_id` bridges to the fixtures.
INSERT OR IGNORE INTO user (id, name, email, email_verified, created_at, updated_at, role, biz_id) VALUES ('usr_admin_001', 'System Admin', 'admin@remysport.test', 1, 1767225600000, 1767225600000, 'admin', 'usr_admin_001');
INSERT OR IGNORE INTO account (id, issuer, account_id, provider_id, user_id, created_at, updated_at) VALUES ('acc_usr_admin_001', 'local:credential', 'usr_admin_001', 'credential', 'usr_admin_001', 1767225600000, 1767225600000);
INSERT OR IGNORE INTO user (id, name, email, email_verified, created_at, updated_at, role, biz_id) VALUES ('usr_org_001', 'Somchai Phattanasakul', 'somchai.p@assumption.test', 1, 1767225600000, 1767225600000, 'organizer', 'usr_org_001');
INSERT OR IGNORE INTO account (id, issuer, account_id, provider_id, user_id, created_at, updated_at) VALUES ('acc_usr_org_001', 'local:credential', 'usr_org_001', 'credential', 'usr_org_001', 1767225600000, 1767225600000);
INSERT OR IGNORE INTO user (id, name, email, email_verified, created_at, updated_at, role, biz_id) VALUES ('usr_org_002', 'Niran Wongthai', 'niran.w@bsbl.test', 1, 1767225600000, 1767225600000, 'organizer', 'usr_org_002');
INSERT OR IGNORE INTO account (id, issuer, account_id, provider_id, user_id, created_at, updated_at) VALUES ('acc_usr_org_002', 'local:credential', 'usr_org_002', 'credential', 'usr_org_002', 1767225600000, 1767225600000);
INSERT OR IGNORE INTO user (id, name, email, email_verified, created_at, updated_at, role, biz_id) VALUES ('usr_org_003', 'Apinya Khampha', 'apinya.k@cmcamp.test', 1, 1767225600000, 1767225600000, 'organizer', 'usr_org_003');
INSERT OR IGNORE INTO account (id, issuer, account_id, provider_id, user_id, created_at, updated_at) VALUES ('acc_usr_org_003', 'local:credential', 'usr_org_003', 'credential', 'usr_org_003', 1767225600000, 1767225600000);
INSERT OR IGNORE INTO user (id, name, email, email_verified, created_at, updated_at, role, biz_id) VALUES ('usr_coach_001', 'Wichai Srisuk', 'wichai.s@assumption.test', 1, 1767225600000, 1767225600000, 'coach', 'usr_coach_001');
INSERT OR IGNORE INTO account (id, issuer, account_id, provider_id, user_id, created_at, updated_at) VALUES ('acc_usr_coach_001', 'local:credential', 'usr_coach_001', 'credential', 'usr_coach_001', 1767225600000, 1767225600000);
INSERT OR IGNORE INTO user (id, name, email, email_verified, created_at, updated_at, role, biz_id) VALUES ('usr_coach_002', 'Pranom Chaiyo', 'pranom.c@triamudom.test', 1, 1767225600000, 1767225600000, 'coach', 'usr_coach_002');
INSERT OR IGNORE INTO account (id, issuer, account_id, provider_id, user_id, created_at, updated_at) VALUES ('acc_usr_coach_002', 'local:credential', 'usr_coach_002', 'credential', 'usr_coach_002', 1767225600000, 1767225600000);
INSERT OR IGNORE INTO user (id, name, email, email_verified, created_at, updated_at, role, biz_id) VALUES ('usr_coach_003', 'Sutee Kaewjai', 'sutee.k@montfort.test', 1, 1767225600000, 1767225600000, 'coach', 'usr_coach_003');
INSERT OR IGNORE INTO account (id, issuer, account_id, provider_id, user_id, created_at, updated_at) VALUES ('acc_usr_coach_003', 'local:credential', 'usr_coach_003', 'credential', 'usr_coach_003', 1767225600000, 1767225600000);
INSERT OR IGNORE INTO user (id, name, email, email_verified, created_at, updated_at, role, biz_id) VALUES ('usr_player_001', 'Thanakorn Suksai', 'thanakorn.s@example.test', 1, 1767225600000, 1767225600000, 'player', 'usr_player_001');
INSERT OR IGNORE INTO account (id, issuer, account_id, provider_id, user_id, created_at, updated_at) VALUES ('acc_usr_player_001', 'local:credential', 'usr_player_001', 'credential', 'usr_player_001', 1767225600000, 1767225600000);
INSERT OR IGNORE INTO user (id, name, email, email_verified, created_at, updated_at, role, biz_id) VALUES ('usr_player_002', 'Kanya Thongdee', 'kanya.t@example.test', 1, 1767225600000, 1767225600000, 'player', 'usr_player_002');
INSERT OR IGNORE INTO account (id, issuer, account_id, provider_id, user_id, created_at, updated_at) VALUES ('acc_usr_player_002', 'local:credential', 'usr_player_002', 'credential', 'usr_player_002', 1767225600000, 1767225600000);
INSERT OR IGNORE INTO user (id, name, email, email_verified, created_at, updated_at, role, biz_id) VALUES ('usr_spectator_001', 'Pim Suksai', 'pim.s@example.test', 1, 1767225600000, 1767225600000, 'spectator', 'usr_spectator_001');
INSERT OR IGNORE INTO account (id, issuer, account_id, provider_id, user_id, created_at, updated_at) VALUES ('acc_usr_spectator_001', 'local:credential', 'usr_spectator_001', 'credential', 'usr_spectator_001', 1767225600000, 1767225600000);
INSERT OR IGNORE INTO user (id, name, email, email_verified, created_at, updated_at, role, biz_id) VALUES ('usr_referee_001', 'Adisorn Boonchai', 'adisorn.b@bat.test', 1, 1767225600000, 1767225600000, 'referee', 'usr_referee_001');
INSERT OR IGNORE INTO account (id, issuer, account_id, provider_id, user_id, created_at, updated_at) VALUES ('acc_usr_referee_001', 'local:credential', 'usr_referee_001', 'credential', 'usr_referee_001', 1767225600000, 1767225600000);
INSERT OR IGNORE INTO user (id, name, email, email_verified, created_at, updated_at, role, biz_id) VALUES ('usr_referee_002', 'Waraporn Jaingam', 'waraporn.j@bat.test', 1, 1767225600000, 1767225600000, 'referee', 'usr_referee_002');
INSERT OR IGNORE INTO account (id, issuer, account_id, provider_id, user_id, created_at, updated_at) VALUES ('acc_usr_referee_002', 'local:credential', 'usr_referee_002', 'credential', 'usr_referee_002', 1767225600000, 1767225600000);

-- Organisations. Better Auth's table; the extra columns are additionalFields.
INSERT OR IGNORE INTO organization (id, name, slug, created_at, names, org_type_code, city_code, province_code) VALUES ('org_001', 'Assumption College', 'assumption-college', 1767225600000, '{"th":"โรงเรียนอัสสัมชัญ","en":"Assumption College"}', 'SCHOOL', 'BANGKOK', 'BKK');
INSERT OR IGNORE INTO organization (id, name, slug, created_at, names, org_type_code, city_code, province_code) VALUES ('org_002', 'Triam Udom Suksa School', 'triam-udom-suksa', 1767225600000, '{"th":"โรงเรียนเตรียมอุดมศึกษา","en":"Triam Udom Suksa School"}', 'SCHOOL', 'BANGKOK', 'BKK');
INSERT OR IGNORE INTO organization (id, name, slug, created_at, names, org_type_code, city_code, province_code) VALUES ('org_003', 'Montfort College', 'montfort-college', 1767225600000, '{"th":"โรงเรียนมงฟอร์ตวิทยาลัย","en":"Montfort College"}', 'SCHOOL', 'CHIANG_MAI', 'CMI');
INSERT OR IGNORE INTO organization (id, name, slug, created_at, names, org_type_code, city_code, province_code) VALUES ('org_004', 'Basketball Sport Association of Thailand', 'basketball-sport-association-thailand', 1767225600000, '{"th":"สมาคมกีฬาบาสเกตบอลแห่งประเทศไทย","en":"Basketball Sport Association of Thailand"}', 'FEDERATION', 'BANGKOK', 'BKK');
INSERT OR IGNORE INTO organization (id, name, slug, created_at, names, org_type_code, city_code, province_code) VALUES ('org_005', 'Bangkok Basketball Club', 'bangkok-basketball-club', 1767225600000, '{"th":"สโมสรบาสเกตบอลกรุงเทพ","en":"Bangkok Basketball Club"}', 'CLUB', 'BANGKOK', 'BKK');

-- Memberships — who may write for which school.
INSERT OR IGNORE INTO member (id, organization_id, user_id, role, created_at) VALUES ('mem_usr_coach_001', 'org_001', 'usr_coach_001', 'admin', 1767225600000);
INSERT OR IGNORE INTO member (id, organization_id, user_id, role, created_at) VALUES ('mem_usr_org_002', 'org_002', 'usr_org_002', 'member', 1767225600000);

-- Rosters. `name` is the English pivot beside the locale-keyed `names`.
INSERT OR IGNORE INTO team (id, name, names, org_id, age_group_code, gender_code, created_at, updated_at) VALUES ('team_001', 'Assumption College U16 Boys', '{"th":"ทีมบาสเกตบอลอัสสัมชัญ U16 ชาย","en":"Assumption College U16 Boys"}', 'org_001', 'U16', 'M', 1767225600000, 1767225600000);
INSERT OR IGNORE INTO team (id, name, names, org_id, age_group_code, gender_code, created_at, updated_at) VALUES ('team_002', 'Triam Udom U18 Girls', '{"th":"ทีมบาสเกตบอลเตรียมอุดมศึกษา U18 หญิง","en":"Triam Udom U18 Girls"}', 'org_002', 'U18', 'F', 1767225600000, 1767225600000);
INSERT OR IGNORE INTO team (id, name, names, org_id, age_group_code, gender_code, created_at, updated_at) VALUES ('team_003', 'Montfort U16 Boys', '{"th":"ทีมบาสเกตบอลมงฟอร์ต U16 ชาย","en":"Montfort U16 Boys"}', 'org_003', 'U16', 'M', 1767225600000, 1767225600000);
INSERT OR IGNORE INTO team (id, name, names, org_id, age_group_code, gender_code, created_at, updated_at) VALUES ('team_004', 'Assumption College U18 Boys', '{"th":"ทีมบาสเกตบอลอัสสัมชัญ U18 ชาย","en":"Assumption College U18 Boys"}', 'org_001', 'U18', 'M', 1767225600000, 1767225600000);

-- Events. `created_by` is the organiser (canonical `organizer_user_id`).
INSERT OR IGNORE INTO event (id, name, names, type_code, format_code, start_date, end_date, city_code, province_code, is_fiba_certified, created_by, created_at, updated_at) VALUES ('evt_001', 'Sponsor Thailand Basketball League 2026 — Bangkok Round', '{"th":"การแข่งขัน Sponsor Thailand Basketball League 2026 รอบกรุงเทพ","en":"Sponsor Thailand Basketball League 2026 — Bangkok Round"}', 'TOURNAMENT', '5x5', '2026-06-10', '2026-06-15', 'BANGKOK', 'BKK', 0, 'usr_org_001', 1767225600000, 1767225600000);
INSERT OR IGNORE INTO event (id, name, names, type_code, format_code, start_date, end_date, city_code, province_code, is_fiba_certified, created_by, created_at, updated_at) VALUES ('evt_002', 'Bangkok Schools Basketball League 2026', '{"th":"ลีกบาสเกตบอลโรงเรียนกรุงเทพ ฤดูกาล 2026","en":"Bangkok Schools Basketball League 2026"}', 'LEAGUE', '5x5', '2026-05-01', '2026-09-30', 'BANGKOK', 'BKK', 0, 'usr_org_002', 1767225600000, 1767225600000);
INSERT OR IGNORE INTO event (id, name, names, type_code, format_code, start_date, end_date, city_code, province_code, is_fiba_certified, created_by, created_at, updated_at) VALUES ('evt_003', 'Chiang Mai Summer Basketball Camp 2026', '{"th":"ค่ายฝึกบาสเกตบอลภาคฤดูร้อน เชียงใหม่ 2026","en":"Chiang Mai Summer Basketball Camp 2026"}', 'CAMP', '5x5', '2026-04-15', '2026-04-19', 'CHIANG_MAI', 'CMI', 0, 'usr_org_003', 1767225600000, 1767225600000);
INSERT OR IGNORE INTO event (id, name, names, type_code, format_code, start_date, end_date, city_code, province_code, is_fiba_certified, created_by, created_at, updated_at) VALUES ('evt_004', 'Thailand Basketball Showcase 2026', '{"th":"การโชว์ผู้เล่นบาสเกตบอลประเทศไทย 2026","en":"Thailand Basketball Showcase 2026"}', 'SHOWCASE', '5x5', '2026-08-01', '2026-08-02', 'BANGKOK', 'BKK', 1, 'usr_org_001', 1767225600000, 1767225600000);

-- divisions
INSERT OR IGNORE INTO division (id, age_group_code, gender_code, skill_tier_code, names) VALUES ('div_001', 'U16', 'M', NULL, '{"th":"U16 ชาย","en":"U16 Boys"}');
INSERT OR IGNORE INTO division (id, age_group_code, gender_code, skill_tier_code, names) VALUES ('div_002', 'U18', 'M', NULL, '{"th":"U18 ชาย","en":"U18 Boys"}');
INSERT OR IGNORE INTO division (id, age_group_code, gender_code, skill_tier_code, names) VALUES ('div_003', 'U16', 'F', NULL, '{"th":"U16 หญิง","en":"U16 Girls"}');
INSERT OR IGNORE INTO division (id, age_group_code, gender_code, skill_tier_code, names) VALUES ('div_004', 'U18', 'F', NULL, '{"th":"U18 หญิง","en":"U18 Girls"}');
INSERT OR IGNORE INTO division (id, age_group_code, gender_code, skill_tier_code, names) VALUES ('div_005', 'U18', 'M', 'PREMIER', '{"th":"U18 ชาย ระดับสูง","en":"U18 Boys Premier"}');
INSERT OR IGNORE INTO division (id, age_group_code, gender_code, skill_tier_code, names) VALUES ('div_006', 'U16', 'M', 'PREMIER', '{"th":"U16 ชาย ระดับสูง","en":"U16 Boys Premier"}');

-- players
INSERT OR IGNORE INTO player (id, user_id, jersey_number, position_code, dob, names) VALUES ('ply_001', 'usr_player_001', 4, 'PG', '2009-03-15', '{"th":"ธนกร สุขใส","en":"Thanakorn Suksai"}');
INSERT OR IGNORE INTO player (id, user_id, jersey_number, position_code, dob, names) VALUES ('ply_002', NULL, 7, 'SF', '2009-08-22', '{"th":"ภูริพัฒน์ จันทรา","en":"Phuripat Chantra"}');
INSERT OR IGNORE INTO player (id, user_id, jersey_number, position_code, dob, names) VALUES ('ply_003', NULL, 11, 'C', '2009-01-10', '{"th":"ณัฐวุฒิ บุญรอด","en":"Nattawut Boonrod"}');
INSERT OR IGNORE INTO player (id, user_id, jersey_number, position_code, dob, names) VALUES ('ply_004', 'usr_player_002', 8, 'SG', '2008-06-30', '{"th":"กันยา ทองดี","en":"Kanya Thongdee"}');
INSERT OR IGNORE INTO player (id, user_id, jersey_number, position_code, dob, names) VALUES ('ply_005', NULL, 14, 'PF', '2008-11-05', '{"th":"อรอุมา ศรีทอง","en":"Onuma Srithong"}');
INSERT OR IGNORE INTO player (id, user_id, jersey_number, position_code, dob, names) VALUES ('ply_006', NULL, 5, 'PG', '2009-04-18', '{"th":"เจษฎา ใจดี","en":"Jessada Jaidee"}');
INSERT OR IGNORE INTO player (id, user_id, jersey_number, position_code, dob, names) VALUES ('ply_007', NULL, 9, 'SF', '2009-09-12', '{"th":"สิทธิชัย พรหมมา","en":"Sittichai Phromma"}');

-- venues
INSERT OR IGNORE INTO venue (id, address, city_code, province_code, names) VALUES ('ven_001', '26 Charoen Krung Rd', 'BANGKOK', 'BKK', '{"th":"สนามกีฬาในร่ม โรงเรียนอัสสัมชัญ","en":"Assumption College Indoor Court"}');
INSERT OR IGNORE INTO venue (id, address, city_code, province_code, names) VALUES ('ven_002', 'National Stadium Complex Rama I Rd', 'BANGKOK', 'BKK', '{"th":"สนามกีฬานิมิบุตร","en":"Nimibutr Stadium"}');
INSERT OR IGNORE INTO venue (id, address, city_code, province_code, names) VALUES ('ven_003', 'Mae Rim Rd', 'CHIANG_MAI', 'CMI', '{"th":"สนามกีฬากลาง 700 ปี","en":"700th Anniversary Sports Complex"}');
INSERT OR IGNORE INTO venue (id, address, city_code, province_code, names) VALUES ('ven_004', '227 Phaya Thai Rd', 'BANGKOK', 'BKK', '{"th":"สนามกีฬาในร่ม โรงเรียนเตรียมอุดมศึกษา","en":"Triam Udom Indoor Court"}');

-- eventCoOrganizers
INSERT OR IGNORE INTO eventCoOrganizer (event_id, user_id, added_at) VALUES ('evt_001', 'usr_org_002', '2026-04-05');

-- eventPlayers
INSERT OR IGNORE INTO eventPlayer (event_id, player_id, registered_at) VALUES ('evt_003', 'ply_001', '2026-03-20');
INSERT OR IGNORE INTO eventPlayer (event_id, player_id, registered_at) VALUES ('evt_003', 'ply_004', '2026-03-22');
INSERT OR IGNORE INTO eventPlayer (event_id, player_id, registered_at) VALUES ('evt_003', 'ply_006', '2026-03-25');
INSERT OR IGNORE INTO eventPlayer (event_id, player_id, registered_at) VALUES ('evt_004', 'ply_001', '2026-07-10');
INSERT OR IGNORE INTO eventPlayer (event_id, player_id, registered_at) VALUES ('evt_004', 'ply_004', '2026-07-12');

-- eventTeams
INSERT OR IGNORE INTO eventTeam (event_id, team_id, division_id, registered_at) VALUES ('evt_001', 'team_001', 'div_001', '2026-04-01');
INSERT OR IGNORE INTO eventTeam (event_id, team_id, division_id, registered_at) VALUES ('evt_001', 'team_003', 'div_001', '2026-04-02');
INSERT OR IGNORE INTO eventTeam (event_id, team_id, division_id, registered_at) VALUES ('evt_001', 'team_004', 'div_002', '2026-04-03');
INSERT OR IGNORE INTO eventTeam (event_id, team_id, division_id, registered_at) VALUES ('evt_002', 'team_001', 'div_001', '2026-04-15');
INSERT OR IGNORE INTO eventTeam (event_id, team_id, division_id, registered_at) VALUES ('evt_002', 'team_002', 'div_004', '2026-04-16');
INSERT OR IGNORE INTO eventTeam (event_id, team_id, division_id, registered_at) VALUES ('evt_002', 'team_004', 'div_002', '2026-04-17');
INSERT OR IGNORE INTO eventTeam (event_id, team_id, division_id, registered_at) VALUES ('evt_004', 'team_001', 'div_001', '2026-07-01');
INSERT OR IGNORE INTO eventTeam (event_id, team_id, division_id, registered_at) VALUES ('evt_004', 'team_002', 'div_004', '2026-07-02');

-- eventVenues
INSERT OR IGNORE INTO eventVenue (event_id, venue_id, is_primary) VALUES ('evt_001', 'ven_002', 1);
INSERT OR IGNORE INTO eventVenue (event_id, venue_id, is_primary) VALUES ('evt_001', 'ven_001', 0);
INSERT OR IGNORE INTO eventVenue (event_id, venue_id, is_primary) VALUES ('evt_002', 'ven_001', 1);
INSERT OR IGNORE INTO eventVenue (event_id, venue_id, is_primary) VALUES ('evt_003', 'ven_003', 1);
INSERT OR IGNORE INTO eventVenue (event_id, venue_id, is_primary) VALUES ('evt_004', 'ven_002', 1);

-- guardians
INSERT OR IGNORE INTO guardian (user_id, player_id, relationship_code) VALUES ('usr_spectator_001', 'ply_001', 'PARENT');

-- playerTeams
INSERT OR IGNORE INTO playerTeam (player_id, team_id, from_date, to_date) VALUES ('ply_001', 'team_001', '2026-01-01', NULL);
INSERT OR IGNORE INTO playerTeam (player_id, team_id, from_date, to_date) VALUES ('ply_001', 'team_004', '2026-03-01', NULL);
INSERT OR IGNORE INTO playerTeam (player_id, team_id, from_date, to_date) VALUES ('ply_002', 'team_001', '2026-01-01', NULL);
INSERT OR IGNORE INTO playerTeam (player_id, team_id, from_date, to_date) VALUES ('ply_003', 'team_001', '2026-01-01', NULL);
INSERT OR IGNORE INTO playerTeam (player_id, team_id, from_date, to_date) VALUES ('ply_004', 'team_002', '2026-01-01', NULL);
INSERT OR IGNORE INTO playerTeam (player_id, team_id, from_date, to_date) VALUES ('ply_005', 'team_002', '2026-01-01', NULL);
INSERT OR IGNORE INTO playerTeam (player_id, team_id, from_date, to_date) VALUES ('ply_006', 'team_003', '2026-01-01', NULL);
INSERT OR IGNORE INTO playerTeam (player_id, team_id, from_date, to_date) VALUES ('ply_007', 'team_003', '2026-01-01', NULL);

-- subscriptions
INSERT OR IGNORE INTO subscription (user_id, object_type_code, object_id, subscribed_at) VALUES ('usr_spectator_001', 'TEAM', 'team_002', '2026-04-15');
INSERT OR IGNORE INTO subscription (user_id, object_type_code, object_id, subscribed_at) VALUES ('usr_player_001', 'TEAM', 'team_002', '2026-03-20');
INSERT OR IGNORE INTO subscription (user_id, object_type_code, object_id, subscribed_at) VALUES ('usr_coach_001', 'EVENT', 'evt_001', '2026-04-01');
INSERT OR IGNORE INTO subscription (user_id, object_type_code, object_id, subscribed_at) VALUES ('usr_admin_001', 'PLAYER', 'ply_004', '2026-04-10');

-- teamCoaches
INSERT OR IGNORE INTO teamCoach (team_id, user_id, coach_role_code) VALUES ('team_001', 'usr_coach_001', 'HEAD');
INSERT OR IGNORE INTO teamCoach (team_id, user_id, coach_role_code) VALUES ('team_001', 'usr_coach_002', 'ASSISTANT');
INSERT OR IGNORE INTO teamCoach (team_id, user_id, coach_role_code) VALUES ('team_002', 'usr_coach_002', 'HEAD');
INSERT OR IGNORE INTO teamCoach (team_id, user_id, coach_role_code) VALUES ('team_003', 'usr_coach_003', 'HEAD');
INSERT OR IGNORE INTO teamCoach (team_id, user_id, coach_role_code) VALUES ('team_004', 'usr_coach_001', 'HEAD');

-- userNotificationChannels
INSERT OR IGNORE INTO userNotificationChannel (user_id, channel_code, address, address_label, is_enabled, verified_at) VALUES ('usr_admin_001', 'EMAIL', 'admin@remysport.test', 'primary', 1, '2026-01-15');
INSERT OR IGNORE INTO userNotificationChannel (user_id, channel_code, address, address_label, is_enabled, verified_at) VALUES ('usr_admin_001', 'LINE', 'remy_admin', 'primary', 1, '2026-01-15');
INSERT OR IGNORE INTO userNotificationChannel (user_id, channel_code, address, address_label, is_enabled, verified_at) VALUES ('usr_org_001', 'LINE', 'somchai_ad', 'primary', 1, '2026-02-10');
INSERT OR IGNORE INTO userNotificationChannel (user_id, channel_code, address, address_label, is_enabled, verified_at) VALUES ('usr_org_001', 'EMAIL', 'somchai.p@assumption.test', 'primary', 1, '2026-02-10');
INSERT OR IGNORE INTO userNotificationChannel (user_id, channel_code, address, address_label, is_enabled, verified_at) VALUES ('usr_coach_001', 'LINE', 'coach_wichai', 'primary', 1, '2026-03-01');
INSERT OR IGNORE INTO userNotificationChannel (user_id, channel_code, address, address_label, is_enabled, verified_at) VALUES ('usr_coach_001', 'EMAIL', 'wichai.s@assumption.test', 'primary', 0, '2026-03-01');
INSERT OR IGNORE INTO userNotificationChannel (user_id, channel_code, address, address_label, is_enabled, verified_at) VALUES ('usr_player_001', 'LINE', 'thanakorn_b', 'primary', 1, '2026-03-15');
INSERT OR IGNORE INTO userNotificationChannel (user_id, channel_code, address, address_label, is_enabled, verified_at) VALUES ('usr_player_002', 'LINE', 'kanya_g', 'primary', 1, '2026-03-20');
INSERT OR IGNORE INTO userNotificationChannel (user_id, channel_code, address, address_label, is_enabled, verified_at) VALUES ('usr_spectator_001', 'LINE', 'pim_mom', 'primary', 1, '2026-04-01');
INSERT OR IGNORE INTO userNotificationChannel (user_id, channel_code, address, address_label, is_enabled, verified_at) VALUES ('usr_spectator_001', 'LINE', 'suksai_family_group', 'family_group', 1, '2026-04-05');
INSERT OR IGNORE INTO userNotificationChannel (user_id, channel_code, address, address_label, is_enabled, verified_at) VALUES ('usr_spectator_001', 'EMAIL', 'pim.s@example.test', 'primary', 1, '2026-04-01');
INSERT OR IGNORE INTO userNotificationChannel (user_id, channel_code, address, address_label, is_enabled, verified_at) VALUES ('usr_referee_001', 'LINE', 'ref_adisorn', 'primary', 1, '2026-03-10');
INSERT OR IGNORE INTO userNotificationChannel (user_id, channel_code, address, address_label, is_enabled, verified_at) VALUES ('usr_referee_002', 'LINE', 'ref_waraporn', 'primary', 1, NULL);

-- userNotificationPreferences
INSERT OR IGNORE INTO userNotificationPreference (user_id, notification_type_code, channel_code, is_enabled) VALUES ('usr_spectator_001', 'SCORE_UPDATE', 'LINE', 1);
INSERT OR IGNORE INTO userNotificationPreference (user_id, notification_type_code, channel_code, is_enabled) VALUES ('usr_spectator_001', 'SCORE_UPDATE', 'EMAIL', 0);
INSERT OR IGNORE INTO userNotificationPreference (user_id, notification_type_code, channel_code, is_enabled) VALUES ('usr_spectator_001', 'WEEKLY_DIGEST', 'LINE', 0);
INSERT OR IGNORE INTO userNotificationPreference (user_id, notification_type_code, channel_code, is_enabled) VALUES ('usr_spectator_001', 'WEEKLY_DIGEST', 'EMAIL', 1);
INSERT OR IGNORE INTO userNotificationPreference (user_id, notification_type_code, channel_code, is_enabled) VALUES ('usr_coach_001', 'APPROVAL_REQUEST', 'LINE', 1);
INSERT OR IGNORE INTO userNotificationPreference (user_id, notification_type_code, channel_code, is_enabled) VALUES ('usr_coach_001', 'ROSTER_CHANGE', 'LINE', 1);
INSERT OR IGNORE INTO userNotificationPreference (user_id, notification_type_code, channel_code, is_enabled) VALUES ('usr_player_001', 'MATCH_START', 'LINE', 1);
INSERT OR IGNORE INTO userNotificationPreference (user_id, notification_type_code, channel_code, is_enabled) VALUES ('usr_player_001', 'DAILY_DIGEST', 'LINE', 0);
