import seedSql from "./seed.sql"

/**
 * The seed, ready to execute.
 *
 * `seed.sql` is generated by `mise run seed:sql` from the PO's fixtures. It is
 * imported as text (the [[rules]] block in wrangler.toml) so the Worker and the
 * worker tests run the same bytes — see scripts/seed-sql.ts for why the seed is
 * data rather than an HTTP call.
 */
export const SEED_STATEMENTS = statements(seedSql)

/**
 * Split a SQL file into executable statements.
 *
 * One statement per line, which is what the generator emits — so the line IS the
 * unit, and comment lines are dropped rather than split around.
 *
 * It used to split on `;`, with a note claiming the generated literals contained
 * none. They do: a notification channel is described as "Reliable delivery; costs
 * per message", and moving the vocabularies into this file cut that statement in
 * half. Splitting on the separator inside your data is a classic, and the note
 * asserting it could not happen is why nobody looked.
 */
function statements(sql: string): string[] {
  return sql
    .split("\n")
    .map((l) => l.trim())
    .filter((l) => l && !l.startsWith("--"))
    .map((l) => (l.endsWith(";") ? l.slice(0, -1) : l))
}
