import seedSql from "./seed.sql"

/**
 * The seed, ready to execute.
 *
 * `seed.sql` is generated by `mise run seed:sql` from the PO's fixtures. It is
 * imported as text (the [[rules]] block in wrangler.toml) so the Worker and the
 * worker tests run the same bytes — see scripts/seed-sql.ts for why the seed is
 * data rather than an HTTP call.
 */
export const SEED_STATEMENTS = statements(seedSql)

/**
 * Split a SQL file into executable statements.
 *
 * Strip comment lines **first**, then split on `;`. Splitting first glues each
 * block's `-- header` onto the statement under it, so the first INSERT of every
 * section silently becomes part of a comment — which showed up as a foreign-key
 * failure three tables later, not as a parse error.
 *
 * Adequate because this file is generated: one statement per line, no semicolons
 * inside the string literals it emits.
 */
export function statements(sql: string): string[] {
  return sql
    .split("\n")
    .filter((l) => !l.trim().startsWith("--"))
    .join("\n")
    .split(";")
    .map((s) => s.trim())
    .filter(Boolean)
}
