// GENERATED by `mise run domain:generate` — do not edit.
//
// Drizzle tables for every reference vocabulary in remy-sport-biz. Add a file to the
// fixtures' reference/ folder and regenerate; nothing here is hand-maintained,
// and `mise run domain:check` fails when this goes stale.
//
// Display names live in JSON columns keyed by locale — `names`, `descriptions`
// — never a column per language. Each keeps its `*_en` pivot beside it: NOT
// NULL, so there is always something renderable, and sortable without reaching
// into JSON.
//

import { sqliteTable, text, integer } from "drizzle-orm/sqlite-core"
import { createSelectSchema } from "drizzle-zod"
import { z } from "zod"
import type { Names } from "../domain/names"

export const objectType = sqliteTable("object_type", {
  code: text("code").primaryKey(),
  nameEn: text("name_en").notNull(),
  names: text("names", { mode: "json" }).$type<Names>().notNull(),
  descriptionEn: text("description_en").notNull(),
  descriptions: text("descriptions", { mode: "json" }).$type<Names>().notNull(),
  sort: integer("sort").notNull(),
})

export const action = sqliteTable("action", {
  code: text("code").primaryKey(),
  objectTypeCode: text("object_type_code").notNull().references(() => objectType.code),
  category: text("category").notNull(),
  nameEn: text("name_en").notNull(),
  names: text("names", { mode: "json" }).$type<Names>().notNull(),
  sort: integer("sort").notNull(),
})

export const ageGroup = sqliteTable("age_group", {
  code: text("code").primaryKey(),
  nameEn: text("name_en").notNull(),
  names: text("names", { mode: "json" }).$type<Names>().notNull(),
  minAge: integer("min_age"),
  maxAge: integer("max_age"),
  sort: integer("sort").notNull(),
})

export const province = sqliteTable("province", {
  code: text("code").primaryKey(),
  nameEn: text("name_en").notNull(),
  names: text("names", { mode: "json" }).$type<Names>().notNull(),
  sort: integer("sort").notNull(),
})

export const city = sqliteTable("city", {
  code: text("code").primaryKey(),
  nameEn: text("name_en").notNull(),
  names: text("names", { mode: "json" }).$type<Names>().notNull(),
  provinceCode: text("province_code").notNull().references(() => province.code),
  sort: integer("sort").notNull(),
})

export const coachRole = sqliteTable("coach_role", {
  code: text("code").primaryKey(),
  nameEn: text("name_en").notNull(),
  names: text("names", { mode: "json" }).$type<Names>().notNull(),
  sort: integer("sort").notNull(),
})

export const eventFormat = sqliteTable("event_format", {
  code: text("code").primaryKey(),
  nameEn: text("name_en").notNull(),
  names: text("names", { mode: "json" }).$type<Names>().notNull(),
  sort: integer("sort").notNull(),
})

export const eventType = sqliteTable("event_type", {
  code: text("code").primaryKey(),
  nameEn: text("name_en").notNull(),
  names: text("names", { mode: "json" }).$type<Names>().notNull(),
  descriptionEn: text("description_en").notNull(),
  descriptions: text("descriptions", { mode: "json" }).$type<Names>().notNull(),
  sort: integer("sort").notNull(),
})

export const gender = sqliteTable("gender", {
  code: text("code").primaryKey(),
  nameEn: text("name_en").notNull(),
  names: text("names", { mode: "json" }).$type<Names>().notNull(),
  sort: integer("sort").notNull(),
})

export const locale = sqliteTable("locale", {
  code: text("code").primaryKey(),
  nameEn: text("name_en").notNull(),
  names: text("names", { mode: "json" }).$type<Names>().notNull(),
  sort: integer("sort").notNull(),
})

export const notificationCategory = sqliteTable("notification_category", {
  code: text("code").primaryKey(),
  nameEn: text("name_en").notNull(),
  names: text("names", { mode: "json" }).$type<Names>().notNull(),
  sort: integer("sort").notNull(),
})

export const notificationChannel = sqliteTable("notification_channel", {
  code: text("code").primaryKey(),
  nameEn: text("name_en").notNull(),
  names: text("names", { mode: "json" }).$type<Names>().notNull(),
  addressFormat: text("address_format").notNull(),
  descriptionEn: text("description_en").notNull(),
  descriptions: text("descriptions", { mode: "json" }).$type<Names>().notNull(),
  sort: integer("sort").notNull(),
})

export const notificationType = sqliteTable("notification_type", {
  code: text("code").primaryKey(),
  categoryCode: text("category_code").notNull().references(() => notificationCategory.code),
  nameEn: text("name_en").notNull(),
  names: text("names", { mode: "json" }).$type<Names>().notNull(),
  descriptionEn: text("description_en").notNull(),
  descriptions: text("descriptions", { mode: "json" }).$type<Names>().notNull(),
  sort: integer("sort").notNull(),
})

export const orgType = sqliteTable("org_type", {
  code: text("code").primaryKey(),
  nameEn: text("name_en").notNull(),
  names: text("names", { mode: "json" }).$type<Names>().notNull(),
  sort: integer("sort").notNull(),
})

export const position = sqliteTable("position", {
  code: text("code").primaryKey(),
  nameEn: text("name_en").notNull(),
  names: text("names", { mode: "json" }).$type<Names>().notNull(),
  fullNameEn: text("full_name_en").notNull(),
  fullNames: text("full_names", { mode: "json" }).$type<Names>().notNull(),
  sort: integer("sort").notNull(),
})

export const relation = sqliteTable("relation", {
  code: text("code").primaryKey(),
  objectTypeCode: text("object_type_code").notNull().references(() => objectType.code),
  nameEn: text("name_en").notNull(),
  names: text("names", { mode: "json" }).$type<Names>().notNull(),
  derivedFrom: text("derived_from").notNull(),
  sort: integer("sort").notNull(),
})

export const relationship = sqliteTable("relationship", {
  code: text("code").primaryKey(),
  nameEn: text("name_en").notNull(),
  names: text("names", { mode: "json" }).$type<Names>().notNull(),
  sort: integer("sort").notNull(),
})

export const role = sqliteTable("role", {
  code: text("code").primaryKey(),
  nameEn: text("name_en").notNull(),
  names: text("names", { mode: "json" }).$type<Names>().notNull(),
  descriptionEn: text("description_en").notNull(),
  descriptions: text("descriptions", { mode: "json" }).$type<Names>().notNull(),
  sort: integer("sort").notNull(),
})

export const skillTier = sqliteTable("skill_tier", {
  code: text("code").primaryKey(),
  nameEn: text("name_en").notNull(),
  names: text("names", { mode: "json" }).$type<Names>().notNull(),
  sort: integer("sort").notNull(),
})

export const userStatus = sqliteTable("user_status", {
  code: text("code").primaryKey(),
  nameEn: text("name_en").notNull(),
  names: text("names", { mode: "json" }).$type<Names>().notNull(),
  descriptionEn: text("description_en").notNull(),
  descriptions: text("descriptions", { mode: "json" }).$type<Names>().notNull(),
  sort: integer("sort").notNull(),
})

/**
 * Every vocabulary, keyed as the API exposes it.
 *
 * This is what lets /api/reference serve all of them without listing any: the
 * contract derives its response schema by mapping over this, and the handler
 * derives its queries the same way. Adding a fixture upstream adds a key here
 * and therefore a field on the endpoint, with nothing else to edit.
 */
export const VOCABULARY_TABLES = {
  objectTypes: objectType,
  actions: action,
  ageGroups: ageGroup,
  provinces: province,
  cities: city,
  coachRoles: coachRole,
  eventFormats: eventFormat,
  eventTypes: eventType,
  genders: gender,
  locales: locale,
  notificationCategories: notificationCategory,
  notificationChannels: notificationChannel,
  notificationTypes: notificationType,
  orgTypes: orgType,
  positions: position,
  relations: relation,
  relationships: relationship,
  roles: role,
  skillTiers: skillTier,
  userStatuses: userStatus,
} as const

/**
 * Each vocabulary's response schema, derived from its table.
 *
 * Emitted rather than built with Object.fromEntries at runtime, because that
 * erases the key literals and the API would lose its field types — the one
 * thing this whole arrangement exists to keep.
 */
export const VOCABULARY_SCHEMAS = {
  objectTypes: z.array(createSelectSchema(objectType)),
  actions: z.array(createSelectSchema(action)),
  ageGroups: z.array(createSelectSchema(ageGroup)),
  provinces: z.array(createSelectSchema(province)),
  cities: z.array(createSelectSchema(city)),
  coachRoles: z.array(createSelectSchema(coachRole)),
  eventFormats: z.array(createSelectSchema(eventFormat)),
  eventTypes: z.array(createSelectSchema(eventType)),
  genders: z.array(createSelectSchema(gender)),
  locales: z.array(createSelectSchema(locale)),
  notificationCategories: z.array(createSelectSchema(notificationCategory)),
  notificationChannels: z.array(createSelectSchema(notificationChannel)),
  notificationTypes: z.array(createSelectSchema(notificationType)),
  orgTypes: z.array(createSelectSchema(orgType)),
  positions: z.array(createSelectSchema(position)),
  relations: z.array(createSelectSchema(relation)),
  relationships: z.array(createSelectSchema(relationship)),
  roles: z.array(createSelectSchema(role)),
  skillTiers: z.array(createSelectSchema(skillTier)),
  userStatuses: z.array(createSelectSchema(userStatus)),
} as const

/** The column each vocabulary is ordered by when the API returns it. */
export const VOCABULARY_ORDER = {
  objectTypes: objectType.sort,
  actions: action.sort,
  ageGroups: ageGroup.sort,
  provinces: province.sort,
  cities: city.sort,
  coachRoles: coachRole.sort,
  eventFormats: eventFormat.sort,
  eventTypes: eventType.sort,
  genders: gender.sort,
  locales: locale.sort,
  notificationCategories: notificationCategory.sort,
  notificationChannels: notificationChannel.sort,
  notificationTypes: notificationType.sort,
  orgTypes: orgType.sort,
  positions: position.sort,
  relations: relation.sort,
  relationships: relationship.sort,
  roles: role.sort,
  skillTiers: skillTier.sort,
  userStatuses: userStatus.sort,
} as const
