// The Product Owner's people, schools, teams and events, as data.
//
// AUTHORED HERE, and copied verbatim into remy-sport. Ids are the model's own —
// `usr_admin_001`, `org_001` — and they are the ids the database uses, so a
// fixture row joins to a Better Auth user on the same column rather than through
// a bridge. Stable ids are the whole reason a re-seed is safe.
//
// Names here are proper nouns — a person, a school, a venue, an event — so they
// are written once and are not translated. The one exception was divisions,
// whose names are not proper nouns at all but labels assembled out of
// vocabulary values, and which had drifted: every division carried Thai and
// English and no Japanese, while `data:check` reported the model fully
// translated. `divisionName` composes them instead, so the three locales cannot
// disagree and a fourth arrives already done.
import { AGE_GROUP, GENDER, SKILL_TIER, ALL_LOCALES } from "./vocabularies"
import type { Names } from "./names"

function divisionName(
  ageGroupCode: string,
  genderCode: string,
  skillTierCode: string | null,
): Names {
  const part = (rows: readonly { code: string; names: Names }[], code: string | null) =>
    code === null ? null : rows.find((r) => r.code === code)?.names ?? null

  // The age group is the code, not its name: it reads "Under 16" on its own,
  // but every flyer in research/events-raw prints "U16" in a division label.
  // Asserting it exists is still worth it — a typo'd code would otherwise
  // produce a plausible-looking label for a division that cannot be joined.
  if (!AGE_GROUP.some((a) => a.code === ageGroupCode)) throw new Error(`unknown age group ${ageGroupCode}`)

  const gender = part(GENDER, genderCode)
  const tier = part(SKILL_TIER, skillTierCode)
  const names: Names = {}
  for (const locale of ALL_LOCALES) {
    names[locale] = [ageGroupCode, gender?.[locale] ?? genderCode, tier?.[locale]]
      .filter(Boolean)
      .join(" ")
  }
  return names
}


export const SEED_ENTITIES = {
  divisions: [
    {"id":"div_001","ageGroupCode":"U16","genderCode":"M","skillTierCode":null,"names":divisionName("U16","M",null)},
    {"id":"div_002","ageGroupCode":"U18","genderCode":"M","skillTierCode":null,"names":divisionName("U18","M",null)},
    {"id":"div_003","ageGroupCode":"U16","genderCode":"F","skillTierCode":null,"names":divisionName("U16","F",null)},
    {"id":"div_004","ageGroupCode":"U18","genderCode":"F","skillTierCode":null,"names":divisionName("U18","F",null)},
    {"id":"div_005","ageGroupCode":"U18","genderCode":"M","skillTierCode":"PREMIER","names":divisionName("U18","M","PREMIER")},
    {"id":"div_006","ageGroupCode":"U16","genderCode":"M","skillTierCode":"PREMIER","names":divisionName("U16","M","PREMIER")},
  ],
  events: [
    {"id":"evt_001","typeCode":"TOURNAMENT","timezone":"Asia/Bangkok","formatCode":"5x5","organizerUserId":"usr_org_001","orgId":"org_001","startDate":"2026-06-10","endDate":"2026-06-15","cityCode":"BANGKOK","provinceCode":"BKK","isFibaCertified":false,"names":{"th":"การแข่งขัน Sponsor Thailand Basketball League 2026 รอบกรุงเทพ","en":"Sponsor Thailand Basketball League 2026 — Bangkok Round"}},
    {"id":"evt_002","typeCode":"LEAGUE","timezone":"Asia/Bangkok","formatCode":"5x5","organizerUserId":"usr_org_002","orgId":null,"startDate":"2026-05-01","endDate":"2026-09-30","cityCode":"BANGKOK","provinceCode":"BKK","isFibaCertified":false,"names":{"th":"ลีกบาสเกตบอลโรงเรียนกรุงเทพ ฤดูกาล 2026","en":"Bangkok Schools Basketball League 2026"}},
    {"id":"evt_003","typeCode":"CAMP","timezone":"Asia/Bangkok","formatCode":"5x5","organizerUserId":"usr_org_003","orgId":"org_003","startDate":"2026-04-15","endDate":"2026-04-19","cityCode":"CHIANG_MAI","provinceCode":"CMI","isFibaCertified":false,"names":{"th":"ค่ายฝึกบาสเกตบอลภาคฤดูร้อน เชียงใหม่ 2026","en":"Chiang Mai Summer Basketball Camp 2026"}},
    {"id":"evt_004","typeCode":"SHOWCASE","timezone":"Asia/Bangkok","formatCode":"5x5","organizerUserId":"usr_org_001","orgId":"org_004","startDate":"2026-08-01","endDate":"2026-08-02","cityCode":"BANGKOK","provinceCode":"BKK","isFibaCertified":true,"names":{"th":"การโชว์ผู้เล่นบาสเกตบอลประเทศไทย 2026","en":"Thailand Basketball Showcase 2026"}},
  ],
  orgs: [
    {"id":"org_001","slug":"assumption-college","orgTypeCode":"SCHOOL","cityCode":"BANGKOK","provinceCode":"BKK","names":{"th":"โรงเรียนอัสสัมชัญ","en":"Assumption College"}},
    {"id":"org_002","slug":"triam-udom-suksa","orgTypeCode":"SCHOOL","cityCode":"BANGKOK","provinceCode":"BKK","names":{"th":"โรงเรียนเตรียมอุดมศึกษา","en":"Triam Udom Suksa School"}},
    {"id":"org_003","slug":"montfort-college","orgTypeCode":"SCHOOL","cityCode":"CHIANG_MAI","provinceCode":"CMI","names":{"th":"โรงเรียนมงฟอร์ตวิทยาลัย","en":"Montfort College"}},
    {"id":"org_004","slug":"basketball-sport-association-thailand","orgTypeCode":"FEDERATION","cityCode":"BANGKOK","provinceCode":"BKK","names":{"th":"สมาคมกีฬาบาสเกตบอลแห่งประเทศไทย","en":"Basketball Sport Association of Thailand"}},
    {"id":"org_005","slug":"bangkok-basketball-club","orgTypeCode":"CLUB","cityCode":"BANGKOK","provinceCode":"BKK","names":{"th":"สโมสรบาสเกตบอลกรุงเทพ","en":"Bangkok Basketball Club"}},

    {"id":"org_006","slug":"saint-gabriels-college","orgTypeCode":"SCHOOL","cityCode":"BANGKOK","provinceCode":"BKK","names":{"th":"โรงเรียนเซนต์คาเบรียล","en":"Saint Gabriel's College"}},
    {"id":"org_007","slug":"suankularb-wittayalai","orgTypeCode":"SCHOOL","cityCode":"BANGKOK","provinceCode":"BKK","names":{"th":"โรงเรียนสวนกุหลาบวิทยาลัย","en":"Suankularb Wittayalai School"}},
    {"id":"org_008","slug":"bangkok-christian-college","orgTypeCode":"SCHOOL","cityCode":"BANGKOK","provinceCode":"BKK","names":{"th":"โรงเรียนกรุงเทพคริสเตียนวิทยาลัย","en":"Bangkok Christian College"}},
    {"id":"org_009","slug":"satriwitthaya-school","orgTypeCode":"SCHOOL","cityCode":"BANGKOK","provinceCode":"BKK","names":{"th":"โรงเรียนสตรีวิทยา","en":"Satriwitthaya School"}},
    {"id":"org_010","slug":"assumption-convent","orgTypeCode":"SCHOOL","cityCode":"BANGKOK","provinceCode":"BKK","names":{"th":"โรงเรียนอัสสัมชัญคอนแวนต์","en":"Assumption Convent School"}},
  ],
  players: [
    {"id":"ply_001","userId":"usr_player_001","jerseyNumber":4,"positionCode":"PG","dob":"2009-03-15","names":{"th":"ธนกร สุขใส","en":"Thanakorn Suksai"}},
    {"id":"ply_002","userId":null,"jerseyNumber":7,"positionCode":"SF","dob":"2009-08-22","names":{"th":"ภูริพัฒน์ จันทรา","en":"Phuripat Chantra"}},
    {"id":"ply_003","userId":null,"jerseyNumber":11,"positionCode":"C","dob":"2009-01-10","names":{"th":"ณัฐวุฒิ บุญรอด","en":"Nattawut Boonrod"}},
    {"id":"ply_004","userId":"usr_player_002","jerseyNumber":8,"positionCode":"SG","dob":"2008-06-30","names":{"th":"กันยา ทองดี","en":"Kanya Thongdee"}},
    {"id":"ply_005","userId":null,"jerseyNumber":14,"positionCode":"PF","dob":"2008-11-05","names":{"th":"อรอุมา ศรีทอง","en":"Onuma Srithong"}},
    {"id":"ply_006","userId":null,"jerseyNumber":5,"positionCode":"PG","dob":"2009-04-18","names":{"th":"เจษฎา ใจดี","en":"Jessada Jaidee"}},
    {"id":"ply_007","userId":null,"jerseyNumber":9,"positionCode":"SF","dob":"2009-09-12","names":{"th":"สิทธิชัย พรหมมา","en":"Sittichai Phromma"}},

    {"id":"ply_008","userId":null,"jerseyNumber":25,"positionCode":"PG","dob":"2010-12-24","names":{"th":"ปุณณวิช อินทรีย์","en":"Punnawit Insi"}},
    {"id":"ply_009","userId":null,"jerseyNumber":10,"positionCode":"SG","dob":"2009-01-26","names":{"th":"ศิวกร พงษ์ไพบูลย์","en":"Siwakorn Phongphaiboon"}},
    {"id":"ply_010","userId":null,"jerseyNumber":32,"positionCode":"SF","dob":"2010-05-20","names":{"th":"อัครเดช ศรีสุวรรณ","en":"Akkaradet Srisuwan"}},
    {"id":"ply_011","userId":null,"jerseyNumber":29,"positionCode":"PF","dob":"2009-10-19","names":{"th":"กิตติพงศ์ แสงทอง","en":"Kittiphong Saengthong"}},
    {"id":"ply_012","userId":null,"jerseyNumber":6,"positionCode":"C","dob":"2009-01-22","names":{"th":"วีรภัทร ดีเลิศ","en":"Weeraphat Deelert"}},
    {"id":"ply_013","userId":null,"jerseyNumber":9,"positionCode":"PG","dob":"2009-08-17","names":{"th":"ศิวกร ทองสุข","en":"Siwakorn Thongsuk"}},
    {"id":"ply_014","userId":null,"jerseyNumber":11,"positionCode":"SG","dob":"2009-08-18","names":{"th":"กฤษณะ อินทรีย์","en":"Kritsana Insi"}},
    {"id":"ply_015","userId":null,"jerseyNumber":21,"positionCode":"SF","dob":"2009-03-15","names":{"th":"ธีรภัทร อินทรีย์","en":"Teeraphat Insi"}},
    {"id":"ply_016","userId":null,"jerseyNumber":23,"positionCode":"PF","dob":"2009-06-07","names":{"th":"วรินทร สุขสมบัติ","en":"Warinthorn Suksombat"}},
    {"id":"ply_017","userId":null,"jerseyNumber":19,"positionCode":"C","dob":"2010-05-05","names":{"th":"ธนวัฒน์ ศรีสุวรรณ","en":"Thanawat Srisuwan"}},
    {"id":"ply_018","userId":null,"jerseyNumber":22,"positionCode":"SG","dob":"2010-07-07","names":{"th":"กฤษณะ แสงทอง","en":"Kritsana Saengthong"}},
    {"id":"ply_019","userId":null,"jerseyNumber":8,"positionCode":"SF","dob":"2010-12-27","names":{"th":"ปุณณวิช นาคเจริญ","en":"Punnawit Nakcharoen"}},
    {"id":"ply_020","userId":null,"jerseyNumber":16,"positionCode":"PF","dob":"2010-11-28","names":{"th":"ศุภกร ดีเลิศ","en":"Supakorn Deelert"}},
    {"id":"ply_021","userId":null,"jerseyNumber":15,"positionCode":"PG","dob":"2010-09-27","names":{"th":"วรินทร สมบูรณ์","en":"Warinthorn Somboon"}},
    {"id":"ply_022","userId":null,"jerseyNumber":28,"positionCode":"SG","dob":"2010-01-18","names":{"th":"รัชชานนท์ ศรีสุวรรณ","en":"Ratchanon Srisuwan"}},
    {"id":"ply_023","userId":null,"jerseyNumber":32,"positionCode":"SF","dob":"2009-10-12","names":{"th":"ศิวกร ดีเลิศ","en":"Siwakorn Deelert"}},
    {"id":"ply_024","userId":null,"jerseyNumber":9,"positionCode":"PF","dob":"2010-05-23","names":{"th":"อัครเดช พูนสุข","en":"Akkaradet Poonsuk"}},
    {"id":"ply_025","userId":null,"jerseyNumber":20,"positionCode":"C","dob":"2010-11-23","names":{"th":"ภานุวัฒน์ พูนสุข","en":"Phanuwat Poonsuk"}},
    {"id":"ply_026","userId":null,"jerseyNumber":3,"positionCode":"SG","dob":"2010-07-07","names":{"th":"ปกรณ์ แก้วมณี","en":"Pakorn Kaewmanee"}},
    {"id":"ply_027","userId":null,"jerseyNumber":25,"positionCode":"SF","dob":"2009-06-23","names":{"th":"วีรภัทร แก้วมณี","en":"Weeraphat Kaewmanee"}},
    {"id":"ply_028","userId":null,"jerseyNumber":23,"positionCode":"PF","dob":"2009-05-11","names":{"th":"อนุชา ชัยวัฒน์","en":"Anucha Chaiwat"}},
    {"id":"ply_029","userId":null,"jerseyNumber":9,"positionCode":"PG","dob":"2010-08-10","names":{"th":"อดิศร เจริญสุข","en":"Adisorn Charoensuk"}},
    {"id":"ply_030","userId":null,"jerseyNumber":32,"positionCode":"SG","dob":"2009-07-01","names":{"th":"อัครเดช วงศ์ใหญ่","en":"Akkaradet Wongyai"}},
    {"id":"ply_031","userId":null,"jerseyNumber":29,"positionCode":"SF","dob":"2009-01-19","names":{"th":"นฤเบศร์ นาคเจริญ","en":"Naruebet Nakcharoen"}},
    {"id":"ply_032","userId":null,"jerseyNumber":5,"positionCode":"PF","dob":"2010-01-28","names":{"th":"ศิวกร นาคเจริญ","en":"Siwakorn Nakcharoen"}},
    {"id":"ply_033","userId":null,"jerseyNumber":20,"positionCode":"C","dob":"2010-01-09","names":{"th":"ภานุวัฒน์ อินทรีย์","en":"Phanuwat Insi"}},
    {"id":"ply_034","userId":null,"jerseyNumber":30,"positionCode":"SG","dob":"2009-07-17","names":{"th":"รัชชานนท์ อินทรีย์","en":"Ratchanon Insi"}},
    {"id":"ply_035","userId":null,"jerseyNumber":14,"positionCode":"SF","dob":"2009-03-23","names":{"th":"ปกรณ์ บุญมาก","en":"Pakorn Boonmak"}},
    {"id":"ply_036","userId":null,"jerseyNumber":24,"positionCode":"PF","dob":"2010-02-19","names":{"th":"ธนดล แก้วมณี","en":"Thanadon Kaewmanee"}},
    {"id":"ply_037","userId":null,"jerseyNumber":34,"positionCode":"PG","dob":"2010-11-01","names":{"th":"กฤษณะ ทองสุข","en":"Kritsana Thongsuk"}},
    {"id":"ply_038","userId":null,"jerseyNumber":5,"positionCode":"SG","dob":"2010-10-24","names":{"th":"ศุภกร รัตนพงษ์","en":"Supakorn Rattanaphong"}},
    {"id":"ply_039","userId":null,"jerseyNumber":13,"positionCode":"SF","dob":"2010-02-15","names":{"th":"กิตติพงศ์ ศรีสุวรรณ","en":"Kittiphong Srisuwan"}},
    {"id":"ply_040","userId":null,"jerseyNumber":26,"positionCode":"PF","dob":"2009-05-17","names":{"th":"ธนดล แสงทอง","en":"Thanadon Saengthong"}},
    {"id":"ply_041","userId":null,"jerseyNumber":11,"positionCode":"C","dob":"2009-10-06","names":{"th":"พีรพัฒน์ ดีเลิศ","en":"Peeraphat Deelert"}},
    {"id":"ply_042","userId":null,"jerseyNumber":8,"positionCode":"SG","dob":"2010-08-24","names":{"th":"ปกรณ์ นาคเจริญ","en":"Pakorn Nakcharoen"}},
    {"id":"ply_043","userId":null,"jerseyNumber":15,"positionCode":"SF","dob":"2009-07-02","names":{"th":"อนุชา อินทรีย์","en":"Anucha Insi"}},
    {"id":"ply_044","userId":null,"jerseyNumber":10,"positionCode":"PF","dob":"2009-12-21","names":{"th":"วรินทร ดีเลิศ","en":"Warinthorn Deelert"}},
    {"id":"ply_045","userId":null,"jerseyNumber":34,"positionCode":"PG","dob":"2009-12-16","names":{"th":"ศิวกร อินทรีย์","en":"Siwakorn Insi"}},
    {"id":"ply_046","userId":null,"jerseyNumber":4,"positionCode":"SG","dob":"2009-10-06","names":{"th":"ธนวัฒน์ ชัยวัฒน์","en":"Thanawat Chaiwat"}},
    {"id":"ply_047","userId":null,"jerseyNumber":12,"positionCode":"SF","dob":"2009-12-16","names":{"th":"ธนวัฒน์ วงศ์ใหญ่","en":"Thanawat Wongyai"}},
    {"id":"ply_048","userId":null,"jerseyNumber":16,"positionCode":"PF","dob":"2010-06-02","names":{"th":"ศุภกร มั่งมี","en":"Supakorn Mangmee"}},
    {"id":"ply_049","userId":null,"jerseyNumber":13,"positionCode":"C","dob":"2010-08-19","names":{"th":"ศุภกร เจริญสุข","en":"Supakorn Charoensuk"}},
    {"id":"ply_050","userId":null,"jerseyNumber":18,"positionCode":"SG","dob":"2009-09-01","names":{"th":"สรวิชญ์ พูนสุข","en":"Sorawit Poonsuk"}},
    {"id":"ply_051","userId":null,"jerseyNumber":13,"positionCode":"PG","dob":"2007-07-23","names":{"th":"ธัญชนก มั่งมี","en":"Thanchanok Mangmee"}},
    {"id":"ply_052","userId":null,"jerseyNumber":10,"positionCode":"SG","dob":"2007-09-24","names":{"th":"ชลธิชา เจริญสุข","en":"Chonthicha Charoensuk"}},
    {"id":"ply_053","userId":null,"jerseyNumber":24,"positionCode":"SF","dob":"2007-10-02","names":{"th":"กมลชนก ศรีสุวรรณ","en":"Kamonchanok Srisuwan"}},
    {"id":"ply_054","userId":null,"jerseyNumber":9,"positionCode":"PF","dob":"2007-11-25","names":{"th":"ณัฐชา วงศ์ใหญ่","en":"Natcha Wongyai"}},
    {"id":"ply_055","userId":null,"jerseyNumber":34,"positionCode":"C","dob":"2007-06-21","names":{"th":"พิมพ์ชนก บุญมาก","en":"Pimchanok Boonmak"}},
    {"id":"ply_056","userId":null,"jerseyNumber":18,"positionCode":"SG","dob":"2008-10-06","names":{"th":"ปาลิตา รัตนพงษ์","en":"Palita Rattanaphong"}},
    {"id":"ply_057","userId":null,"jerseyNumber":5,"positionCode":"PG","dob":"2008-08-16","names":{"th":"ปาลิตา อินทรีย์","en":"Palita Insi"}},
    {"id":"ply_058","userId":null,"jerseyNumber":18,"positionCode":"SG","dob":"2008-04-10","names":{"th":"พรรณิภา ชัยวัฒน์","en":"Phannipha Chaiwat"}},
    {"id":"ply_059","userId":null,"jerseyNumber":12,"positionCode":"SF","dob":"2007-01-14","names":{"th":"กมลชนก พูนสุข","en":"Kamonchanok Poonsuk"}},
    {"id":"ply_060","userId":null,"jerseyNumber":35,"positionCode":"PF","dob":"2008-02-24","names":{"th":"วรรณิดา มั่งมี","en":"Wannida Mangmee"}},
    {"id":"ply_061","userId":null,"jerseyNumber":6,"positionCode":"C","dob":"2008-11-18","names":{"th":"รัตนาภรณ์ มั่งมี","en":"Rattanaporn Mangmee"}},
    {"id":"ply_062","userId":null,"jerseyNumber":4,"positionCode":"SG","dob":"2007-03-17","names":{"th":"พิมพ์ชนก แก้วมณี","en":"Pimchanok Kaewmanee"}},
    {"id":"ply_063","userId":null,"jerseyNumber":8,"positionCode":"SF","dob":"2007-01-28","names":{"th":"สุพิชญา แสงทอง","en":"Supitchaya Saengthong"}},
    {"id":"ply_064","userId":null,"jerseyNumber":33,"positionCode":"PF","dob":"2008-08-19","names":{"th":"ณิชากร ชัยวัฒน์","en":"Nichakorn Chaiwat"}},
    {"id":"ply_065","userId":null,"jerseyNumber":33,"positionCode":"PG","dob":"2007-10-15","names":{"th":"พิมพ์ชนก พูนสุข","en":"Pimchanok Poonsuk"}},
    {"id":"ply_066","userId":null,"jerseyNumber":14,"positionCode":"SG","dob":"2008-10-09","names":{"th":"ณัฐชา ประเสริฐ","en":"Natcha Prasert"}},
    {"id":"ply_067","userId":null,"jerseyNumber":22,"positionCode":"SF","dob":"2007-04-09","names":{"th":"ธัญชนก เจริญสุข","en":"Thanchanok Charoensuk"}},
    {"id":"ply_068","userId":null,"jerseyNumber":17,"positionCode":"PF","dob":"2008-02-09","names":{"th":"ณัฐชา มั่งมี","en":"Natcha Mangmee"}},
    {"id":"ply_069","userId":null,"jerseyNumber":26,"positionCode":"C","dob":"2007-10-14","names":{"th":"สุพิชญา พงษ์ไพบูลย์","en":"Supitchaya Phongphaiboon"}},
    {"id":"ply_070","userId":null,"jerseyNumber":19,"positionCode":"SG","dob":"2007-12-10","names":{"th":"ธัญชนก สุขสมบัติ","en":"Thanchanok Suksombat"}},
    {"id":"ply_071","userId":null,"jerseyNumber":24,"positionCode":"SF","dob":"2007-10-05","names":{"th":"ชนิกานต์ ทองสุข","en":"Chanikan Thongsuk"}},
    {"id":"ply_072","userId":null,"jerseyNumber":29,"positionCode":"PF","dob":"2007-05-05","names":{"th":"วรรณิดา ชัยวัฒน์","en":"Wannida Chaiwat"}},
    {"id":"ply_073","userId":null,"jerseyNumber":23,"positionCode":"PG","dob":"2008-01-20","names":{"th":"ปาลิตา มั่งมี","en":"Palita Mangmee"}},
    {"id":"ply_074","userId":null,"jerseyNumber":24,"positionCode":"SG","dob":"2007-12-02","names":{"th":"ชลธิชา ศรีสุวรรณ","en":"Chonthicha Srisuwan"}},
    {"id":"ply_075","userId":null,"jerseyNumber":10,"positionCode":"SF","dob":"2008-07-21","names":{"th":"ศิริพร ทองสุข","en":"Siriporn Thongsuk"}},
    {"id":"ply_076","userId":null,"jerseyNumber":14,"positionCode":"PF","dob":"2008-06-01","names":{"th":"วรรณิดา แก้วมณี","en":"Wannida Kaewmanee"}},
    {"id":"ply_077","userId":null,"jerseyNumber":7,"positionCode":"C","dob":"2007-09-13","names":{"th":"เบญจวรรณ เจริญสุข","en":"Benjawan Charoensuk"}},
    {"id":"ply_078","userId":null,"jerseyNumber":17,"positionCode":"SG","dob":"2008-10-18","names":{"th":"จิดาภา วงศ์ใหญ่","en":"Jidapa Wongyai"}},
    {"id":"ply_079","userId":null,"jerseyNumber":19,"positionCode":"SF","dob":"2008-07-17","names":{"th":"ธัญชนก พงษ์ไพบูลย์","en":"Thanchanok Phongphaiboon"}},
    {"id":"ply_080","userId":null,"jerseyNumber":5,"positionCode":"PF","dob":"2008-11-24","names":{"th":"วรรณิดา สุขสมบัติ","en":"Wannida Suksombat"}},
    {"id":"ply_081","userId":null,"jerseyNumber":20,"positionCode":"PG","dob":"2007-02-01","names":{"th":"นฤเบศร์ ดีเลิศ","en":"Naruebet Deelert"}},
    {"id":"ply_082","userId":null,"jerseyNumber":34,"positionCode":"SG","dob":"2008-01-23","names":{"th":"ธีรภัทร ศรีสุวรรณ","en":"Teeraphat Srisuwan"}},
    {"id":"ply_083","userId":null,"jerseyNumber":10,"positionCode":"SF","dob":"2008-11-10","names":{"th":"รัชชานนท์ เจริญสุข","en":"Ratchanon Charoensuk"}},
    {"id":"ply_084","userId":null,"jerseyNumber":26,"positionCode":"PF","dob":"2007-10-04","names":{"th":"รัชชานนท์ มั่งมี","en":"Ratchanon Mangmee"}},
    {"id":"ply_085","userId":null,"jerseyNumber":12,"positionCode":"C","dob":"2007-05-24","names":{"th":"ธนกฤต สมบูรณ์","en":"Thanakrit Somboon"}},
    {"id":"ply_086","userId":null,"jerseyNumber":21,"positionCode":"SG","dob":"2007-07-22","names":{"th":"วีรภัทร อินทรีย์","en":"Weeraphat Insi"}},
    {"id":"ply_087","userId":null,"jerseyNumber":7,"positionCode":"SF","dob":"2008-08-17","names":{"th":"อนุชา พงษ์ไพบูลย์","en":"Anucha Phongphaiboon"}},
    {"id":"ply_088","userId":null,"jerseyNumber":32,"positionCode":"PG","dob":"2007-06-20","names":{"th":"สรวิชญ์ ดีเลิศ","en":"Sorawit Deelert"}},
    {"id":"ply_089","userId":null,"jerseyNumber":14,"positionCode":"SG","dob":"2007-08-14","names":{"th":"อดิศร บุญมาก","en":"Adisorn Boonmak"}},
    {"id":"ply_090","userId":null,"jerseyNumber":27,"positionCode":"SF","dob":"2008-09-08","names":{"th":"อัครเดช อินทรีย์","en":"Akkaradet Insi"}},
    {"id":"ply_091","userId":null,"jerseyNumber":16,"positionCode":"PF","dob":"2007-10-04","names":{"th":"ชนาธิป ทองสุข","en":"Chanathip Thongsuk"}},
    {"id":"ply_092","userId":null,"jerseyNumber":13,"positionCode":"C","dob":"2007-12-09","names":{"th":"วรินทร บุญมาก","en":"Warinthorn Boonmak"}},
    {"id":"ply_093","userId":null,"jerseyNumber":17,"positionCode":"SG","dob":"2007-12-10","names":{"th":"ปกรณ์ ทองสุข","en":"Pakorn Thongsuk"}},
    {"id":"ply_094","userId":null,"jerseyNumber":28,"positionCode":"SF","dob":"2008-11-06","names":{"th":"ปกรณ์ ชัยวัฒน์","en":"Pakorn Chaiwat"}},
    {"id":"ply_095","userId":null,"jerseyNumber":8,"positionCode":"PF","dob":"2007-05-07","names":{"th":"ธนดล วงศ์ใหญ่","en":"Thanadon Wongyai"}},
    {"id":"ply_096","userId":null,"jerseyNumber":35,"positionCode":"PG","dob":"2008-12-07","names":{"th":"ปุณณวิช ศรีสุวรรณ","en":"Punnawit Srisuwan"}},
    {"id":"ply_097","userId":null,"jerseyNumber":13,"positionCode":"SG","dob":"2008-12-08","names":{"th":"ปิยะพงษ์ ศรีสุวรรณ","en":"Piyapong Srisuwan"}},
    {"id":"ply_098","userId":null,"jerseyNumber":33,"positionCode":"SF","dob":"2008-07-05","names":{"th":"ปิยะพงษ์ แก้วมณี","en":"Piyapong Kaewmanee"}},
    {"id":"ply_099","userId":null,"jerseyNumber":7,"positionCode":"PF","dob":"2008-01-19","names":{"th":"ธนวัฒน์ ดีเลิศ","en":"Thanawat Deelert"}},
    {"id":"ply_100","userId":null,"jerseyNumber":31,"positionCode":"C","dob":"2008-12-23","names":{"th":"สรวิชญ์ เจริญสุข","en":"Sorawit Charoensuk"}},
    {"id":"ply_101","userId":null,"jerseyNumber":34,"positionCode":"SG","dob":"2008-12-19","names":{"th":"ปุณณวิช รัตนพงษ์","en":"Punnawit Rattanaphong"}},
    {"id":"ply_102","userId":null,"jerseyNumber":26,"positionCode":"SF","dob":"2007-08-23","names":{"th":"ธนดล รัตนพงษ์","en":"Thanadon Rattanaphong"}},
    {"id":"ply_103","userId":null,"jerseyNumber":17,"positionCode":"PF","dob":"2008-03-16","names":{"th":"จิรายุ ประเสริฐ","en":"Jirayu Prasert"}},
    {"id":"ply_104","userId":null,"jerseyNumber":7,"positionCode":"PG","dob":"2008-12-11","names":{"th":"นฤเบศร์ พงษ์ไพบูลย์","en":"Naruebet Phongphaiboon"}},
    {"id":"ply_105","userId":null,"jerseyNumber":32,"positionCode":"SG","dob":"2008-04-15","names":{"th":"อดิศร ศรีสุวรรณ","en":"Adisorn Srisuwan"}},
    {"id":"ply_106","userId":null,"jerseyNumber":6,"positionCode":"SF","dob":"2008-09-05","names":{"th":"อนุชา ประเสริฐ","en":"Anucha Prasert"}},
    {"id":"ply_107","userId":null,"jerseyNumber":21,"positionCode":"PF","dob":"2007-07-09","names":{"th":"ธนวัฒน์ สุขสมบัติ","en":"Thanawat Suksombat"}},
    {"id":"ply_108","userId":null,"jerseyNumber":19,"positionCode":"C","dob":"2008-01-10","names":{"th":"กฤษณะ สุขสมบัติ","en":"Kritsana Suksombat"}},
    {"id":"ply_109","userId":null,"jerseyNumber":11,"positionCode":"SG","dob":"2008-07-10","names":{"th":"ธนกฤต พูนสุข","en":"Thanakrit Poonsuk"}},
    {"id":"ply_110","userId":null,"jerseyNumber":9,"positionCode":"SF","dob":"2008-07-07","names":{"th":"ธนดล ชัยวัฒน์","en":"Thanadon Chaiwat"}},
    {"id":"ply_111","userId":null,"jerseyNumber":31,"positionCode":"PF","dob":"2008-07-27","names":{"th":"นฤเบศร์ ชัยวัฒน์","en":"Naruebet Chaiwat"}},
    {"id":"ply_112","userId":null,"jerseyNumber":35,"positionCode":"PG","dob":"2008-08-08","names":{"th":"รัชชานนท์ แสงทอง","en":"Ratchanon Saengthong"}},
    {"id":"ply_113","userId":null,"jerseyNumber":24,"positionCode":"SG","dob":"2007-06-25","names":{"th":"กิตติพงศ์ อินทรีย์","en":"Kittiphong Insi"}},
    {"id":"ply_114","userId":null,"jerseyNumber":25,"positionCode":"SF","dob":"2008-10-03","names":{"th":"ศิวกร ชัยวัฒน์","en":"Siwakorn Chaiwat"}},
    {"id":"ply_115","userId":null,"jerseyNumber":30,"positionCode":"PF","dob":"2008-01-23","names":{"th":"วีรภัทร สมบูรณ์","en":"Weeraphat Somboon"}},
    {"id":"ply_116","userId":null,"jerseyNumber":31,"positionCode":"C","dob":"2008-01-14","names":{"th":"ปกรณ์ พูนสุข","en":"Pakorn Poonsuk"}},
    {"id":"ply_117","userId":null,"jerseyNumber":22,"positionCode":"SG","dob":"2008-08-28","names":{"th":"ภานุวัฒน์ บุญมาก","en":"Phanuwat Boonmak"}},
    {"id":"ply_118","userId":null,"jerseyNumber":11,"positionCode":"SF","dob":"2008-09-12","names":{"th":"วีรภัทร ชัยวัฒน์","en":"Weeraphat Chaiwat"}},
    {"id":"ply_119","userId":null,"jerseyNumber":7,"positionCode":"PF","dob":"2008-10-05","names":{"th":"ชนาธิป ประเสริฐ","en":"Chanathip Prasert"}},
  ],
  teams: [
    {"id":"team_001","orgId":"org_001","ageGroupCode":"U16","genderCode":"M","names":{"th":"ทีมบาสเกตบอลอัสสัมชัญ U16 ชาย","en":"Assumption College U16 Boys"}},
    {"id":"team_002","orgId":"org_002","ageGroupCode":"U18","genderCode":"F","names":{"th":"ทีมบาสเกตบอลเตรียมอุดมศึกษา U18 หญิง","en":"Triam Udom U18 Girls"}},
    {"id":"team_003","orgId":"org_003","ageGroupCode":"U16","genderCode":"M","names":{"th":"ทีมบาสเกตบอลมงฟอร์ต U16 ชาย","en":"Montfort U16 Boys"}},
    {"id":"team_004","orgId":"org_001","ageGroupCode":"U18","genderCode":"M","names":{"th":"ทีมบาสเกตบอลอัสสัมชัญ U18 ชาย","en":"Assumption College U18 Boys"}},

    {"id":"team_005","orgId":"org_006","ageGroupCode":"U16","genderCode":"M","names":{"th":"ทีมบาสเกตบอลเซนต์คาเบรียล U16 ชาย","en":"Saint Gabriel's U16 Boys"}},
    {"id":"team_006","orgId":"org_007","ageGroupCode":"U16","genderCode":"M","names":{"th":"ทีมบาสเกตบอลสวนกุหลาบ U16 ชาย","en":"Suankularb U16 Boys"}},
    {"id":"team_007","orgId":"org_008","ageGroupCode":"U16","genderCode":"M","names":{"th":"ทีมบาสเกตบอลกรุงเทพคริสเตียน U16 ชาย","en":"Bangkok Christian U16 Boys"}},
    {"id":"team_008","orgId":"org_005","ageGroupCode":"U16","genderCode":"M","names":{"th":"ทีมบาสเกตบอลสโมสรกรุงเทพ U16 ชาย","en":"Bangkok BC U16 Boys"}},
    {"id":"team_009","orgId":"org_009","ageGroupCode":"U18","genderCode":"F","names":{"th":"ทีมบาสเกตบอลสตรีวิทยา U18 หญิง","en":"Satriwitthaya U18 Girls"}},
    {"id":"team_010","orgId":"org_010","ageGroupCode":"U18","genderCode":"F","names":{"th":"ทีมบาสเกตบอลอัสสัมชัญคอนแวนต์ U18 หญิง","en":"Assumption Convent U18 Girls"}},
    {"id":"team_011","orgId":"org_005","ageGroupCode":"U18","genderCode":"F","names":{"th":"ทีมบาสเกตบอลสโมสรกรุงเทพ U18 หญิง","en":"Bangkok BC U18 Girls"}},
    {"id":"team_012","orgId":"org_006","ageGroupCode":"U18","genderCode":"M","names":{"th":"ทีมบาสเกตบอลเซนต์คาเบรียล U18 ชาย","en":"Saint Gabriel's U18 Boys"}},
    {"id":"team_013","orgId":"org_007","ageGroupCode":"U18","genderCode":"M","names":{"th":"ทีมบาสเกตบอลสวนกุหลาบ U18 ชาย","en":"Suankularb U18 Boys"}},
    {"id":"team_014","orgId":"org_008","ageGroupCode":"U18","genderCode":"M","names":{"th":"ทีมบาสเกตบอลกรุงเทพคริสเตียน U18 ชาย","en":"Bangkok Christian U18 Boys"}},
    {"id":"team_015","orgId":"org_003","ageGroupCode":"U18","genderCode":"M","names":{"th":"ทีมบาสเกตบอลมงฟอร์ต U18 ชาย","en":"Montfort U18 Boys"}},
  ],
  users: [
    {"id":"usr_admin_001","roleCode":"ADMIN","statusCode":"ACTIVE","email":"admin@remysport.test","phone":"+66812340000","lineId":"remy_admin","localeCode":"en","names":{"th":"ผู้ดูแลระบบ","en":"System Admin"}},
    {"id":"usr_org_001","roleCode":"ORGANIZER","statusCode":"ACTIVE","email":"somchai.p@assumption.test","phone":"+66812340001","lineId":"somchai_ad","localeCode":"th","names":{"th":"สมชาย พัฒนสกุล","en":"Somchai Phattanasakul"}},
    {"id":"usr_org_002","roleCode":"ORGANIZER","statusCode":"ACTIVE","email":"niran.w@bsbl.test","phone":"+66812340002","lineId":"niran_bsbl","localeCode":"th","names":{"th":"นิรันดร์ วงศ์ไทย","en":"Niran Wongthai"}},
    {"id":"usr_org_003","roleCode":"ORGANIZER","statusCode":"ACTIVE","email":"apinya.k@cmcamp.test","phone":"+66812340003","lineId":"apinya_cm","localeCode":"th","names":{"th":"อภิญญา คำผา","en":"Apinya Khampha"}},
    {"id":"usr_coach_001","roleCode":"COACH","statusCode":"ACTIVE","email":"wichai.s@assumption.test","phone":"+66812340011","lineId":"coach_wichai","localeCode":"th","names":{"th":"วิชัย ศรีสุข","en":"Wichai Srisuk"}},
    {"id":"usr_coach_002","roleCode":"COACH","statusCode":"ACTIVE","email":"pranom.c@triamudom.test","phone":"+66812340012","lineId":"coach_pranom","localeCode":"th","names":{"th":"ประนอม ไชโย","en":"Pranom Chaiyo"}},
    {"id":"usr_coach_003","roleCode":"COACH","statusCode":"ACTIVE","email":"sutee.k@montfort.test","phone":"+66812340013","lineId":"coach_sutee","localeCode":"th","names":{"th":"สุธี แก้วใจ","en":"Sutee Kaewjai"}},
    {"id":"usr_player_001","roleCode":"PLAYER","statusCode":"ACTIVE","email":"thanakorn.s@example.test","phone":"+66812340021","lineId":"thanakorn_b","localeCode":"th","names":{"th":"ธนกร สุขใส","en":"Thanakorn Suksai"}},
    {"id":"usr_player_002","roleCode":"PLAYER","statusCode":"ACTIVE","email":"kanya.t@example.test","phone":"+66812340022","lineId":"kanya_g","localeCode":"th","names":{"th":"กันยา ทองดี","en":"Kanya Thongdee"}},
    {"id":"usr_spectator_001","roleCode":"SPECTATOR","statusCode":"ACTIVE","email":"pim.s@example.test","phone":"+66812340031","lineId":"pim_mom","localeCode":"ja","names":{"th":"พิมพ์ สุขใส","en":"Pim Suksai"}},
    {"id":"usr_referee_001","roleCode":"REFEREE","statusCode":"ACTIVE","email":"adisorn.b@bat.test","phone":"+66812340041","lineId":"ref_adisorn","localeCode":"th","names":{"th":"อดิศร บุญชัย","en":"Adisorn Boonchai"}},
    {"id":"usr_referee_002","roleCode":"REFEREE","statusCode":"PENDING_APPROVAL","email":"waraporn.j@bat.test","phone":"+66812340042","lineId":"ref_waraporn","localeCode":"th","names":{"th":"วราภรณ์ ใจงาม","en":"Waraporn Jaingam"}},

    {"id":"usr_spectator_002","roleCode":"SPECTATOR","statusCode":"SUSPENDED","email":"suspended.s@example.test","phone":"+66812340041","lineId":"suspended_s","localeCode":"th","names":{"th":"สมพร ระงับ","en":"Somporn Rangap"}},
    {"id":"usr_spectator_003","roleCode":"SPECTATOR","statusCode":"DEACTIVATED","email":"closed.c@example.test","phone":"+66812340042","lineId":"closed_c","localeCode":"en","names":{"th":"ชนิดา ปิดบัญชี","en":"Chanida Pidbanchi"}},
  ],
  /**
   * Three games, in the three states that matter: played, in progress, and
   * still to come.
   *
   * Only team_001 and team_003 can meet — they are the two U16 boys' teams, and
   * a fixture between teams of different age groups or genders would be a
   * fixture nobody would ever schedule. team_003 is registered to evt_002 below
   * so the league has an opponent to field.
   *
   * gam_003 has no scores and no venue: a game that has not been played has no
   * result, and 0–0 is a result. The product already renders "Venue TBC".
   */
  games: [
    {"id":"gam_001","eventId":"evt_001","homeTeamId":"team_001","awayTeamId":"team_003","venueId":"ven_002","startsAt":"2026-06-10T10:00:00Z","statusCode":"FINISHED","homeScore":68,"awayScore":54},
    {"id":"gam_002","eventId":"evt_002","homeTeamId":"team_001","awayTeamId":"team_003","venueId":"ven_001","startsAt":"2026-08-27T13:00:00Z","statusCode":"LIVE","homeScore":41,"awayScore":38},
    {"id":"gam_003","eventId":"evt_002","homeTeamId":"team_003","awayTeamId":"team_001","venueId":null,"startsAt":"2026-09-15T10:00:00Z","statusCode":"SCHEDULED","homeScore":null,"awayScore":null},

    {"id":"gam_004","eventId":"evt_002","homeTeamId":"team_001","awayTeamId":"team_005","venueId":"ven_001","startsAt":"2026-05-09T10:00:00Z","statusCode":"FINISHED","homeScore":84,"awayScore":61},
    {"id":"gam_005","eventId":"evt_002","homeTeamId":"team_001","awayTeamId":"team_006","venueId":"ven_004","startsAt":"2026-05-20T10:00:00Z","statusCode":"FINISHED","homeScore":60,"awayScore":71},
    {"id":"gam_006","eventId":"evt_002","homeTeamId":"team_001","awayTeamId":"team_007","venueId":"ven_002","startsAt":"2026-05-31T10:00:00Z","statusCode":"FINISHED","homeScore":69,"awayScore":56},
    {"id":"gam_007","eventId":"evt_002","homeTeamId":"team_001","awayTeamId":"team_008","venueId":"ven_002","startsAt":"2026-06-10T10:00:00Z","statusCode":"FINISHED","homeScore":82,"awayScore":72},
    {"id":"gam_008","eventId":"evt_002","homeTeamId":"team_003","awayTeamId":"team_005","venueId":"ven_004","startsAt":"2026-06-21T10:00:00Z","statusCode":"FINISHED","homeScore":52,"awayScore":50},
    {"id":"gam_009","eventId":"evt_002","homeTeamId":"team_003","awayTeamId":"team_006","venueId":"ven_001","startsAt":"2026-07-02T10:00:00Z","statusCode":"FINISHED","homeScore":88,"awayScore":80},
    {"id":"gam_010","eventId":"evt_002","homeTeamId":"team_003","awayTeamId":"team_007","venueId":"ven_001","startsAt":"2026-07-13T10:00:00Z","statusCode":"FINISHED","homeScore":60,"awayScore":88},
    {"id":"gam_011","eventId":"evt_002","homeTeamId":"team_003","awayTeamId":"team_008","venueId":"ven_002","startsAt":"2026-07-23T10:00:00Z","statusCode":"FINISHED","homeScore":53,"awayScore":75},
    {"id":"gam_012","eventId":"evt_002","homeTeamId":"team_005","awayTeamId":"team_006","venueId":"ven_002","startsAt":"2026-08-03T10:00:00Z","statusCode":"FINISHED","homeScore":79,"awayScore":67},
    {"id":"gam_013","eventId":"evt_002","homeTeamId":"team_005","awayTeamId":"team_007","venueId":"ven_002","startsAt":"2026-08-14T10:00:00Z","statusCode":"FINISHED","homeScore":51,"awayScore":58},
    {"id":"gam_014","eventId":"evt_002","homeTeamId":"team_005","awayTeamId":"team_008","venueId":"ven_001","startsAt":"2026-08-28T10:00:00Z","statusCode":"LIVE","homeScore":52,"awayScore":40},
    {"id":"gam_015","eventId":"evt_002","homeTeamId":"team_006","awayTeamId":"team_007","venueId":"ven_002","startsAt":"2026-09-04T10:00:00Z","statusCode":"SCHEDULED","homeScore":null,"awayScore":null},
    {"id":"gam_016","eventId":"evt_002","homeTeamId":"team_006","awayTeamId":"team_008","venueId":"ven_004","startsAt":"2026-09-15T10:00:00Z","statusCode":"SCHEDULED","homeScore":null,"awayScore":null},
    {"id":"gam_017","eventId":"evt_002","homeTeamId":"team_007","awayTeamId":"team_008","venueId":"ven_002","startsAt":"2026-09-26T10:00:00Z","statusCode":"SCHEDULED","homeScore":null,"awayScore":null},
    {"id":"gam_018","eventId":"evt_002","homeTeamId":"team_002","awayTeamId":"team_009","venueId":"ven_001","startsAt":"2026-05-16T12:00:00Z","statusCode":"FINISHED","homeScore":72,"awayScore":66},
    {"id":"gam_019","eventId":"evt_002","homeTeamId":"team_002","awayTeamId":"team_010","venueId":"ven_001","startsAt":"2026-06-12T12:00:00Z","statusCode":"FINISHED","homeScore":76,"awayScore":66},
    {"id":"gam_020","eventId":"evt_002","homeTeamId":"team_002","awayTeamId":"team_011","venueId":"ven_001","startsAt":"2026-07-08T12:00:00Z","statusCode":"FINISHED","homeScore":71,"awayScore":77},
    {"id":"gam_021","eventId":"evt_002","homeTeamId":"team_009","awayTeamId":"team_010","venueId":"ven_001","startsAt":"2026-08-04T12:00:00Z","statusCode":"FINISHED","homeScore":87,"awayScore":80},
    {"id":"gam_022","eventId":"evt_002","homeTeamId":"team_009","awayTeamId":"team_011","venueId":"ven_004","startsAt":"2026-08-28T12:00:00Z","statusCode":"LIVE","homeScore":48,"awayScore":45},
    {"id":"gam_023","eventId":"evt_002","homeTeamId":"team_010","awayTeamId":"team_011","venueId":"ven_004","startsAt":"2026-09-26T12:00:00Z","statusCode":"SCHEDULED","homeScore":null,"awayScore":null},
    {"id":"gam_024","eventId":"evt_002","homeTeamId":"team_004","awayTeamId":"team_012","venueId":"ven_001","startsAt":"2026-05-23T14:00:00Z","statusCode":"FINISHED","homeScore":60,"awayScore":61},
    {"id":"gam_025","eventId":"evt_002","homeTeamId":"team_004","awayTeamId":"team_013","venueId":"ven_001","startsAt":"2026-06-17T14:00:00Z","statusCode":"FINISHED","homeScore":84,"awayScore":79},
    {"id":"gam_026","eventId":"evt_002","homeTeamId":"team_004","awayTeamId":"team_014","venueId":"ven_001","startsAt":"2026-07-12T14:00:00Z","statusCode":"FINISHED","homeScore":51,"awayScore":84},
    {"id":"gam_027","eventId":"evt_002","homeTeamId":"team_012","awayTeamId":"team_013","venueId":"ven_002","startsAt":"2026-08-28T14:00:00Z","statusCode":"HALF_TIME","homeScore":28,"awayScore":46},
    {"id":"gam_028","eventId":"evt_002","homeTeamId":"team_012","awayTeamId":"team_014","venueId":"ven_002","startsAt":"2026-09-01T14:00:00Z","statusCode":"SCHEDULED","homeScore":null,"awayScore":null},
    {"id":"gam_029","eventId":"evt_002","homeTeamId":"team_013","awayTeamId":"team_014","venueId":"ven_001","startsAt":"2026-09-26T14:00:00Z","statusCode":"SCHEDULED","homeScore":null,"awayScore":null},
  ],
  venues: [
    {"id":"ven_001","address":"26 Charoen Krung Rd","cityCode":"BANGKOK","provinceCode":"BKK","names":{"th":"สนามกีฬาในร่ม โรงเรียนอัสสัมชัญ","en":"Assumption College Indoor Court"}},
    {"id":"ven_002","address":"National Stadium Complex Rama I Rd","cityCode":"BANGKOK","provinceCode":"BKK","names":{"th":"สนามกีฬานิมิบุตร","en":"Nimibutr Stadium"}},
    {"id":"ven_003","address":"Mae Rim Rd","cityCode":"CHIANG_MAI","provinceCode":"CMI","names":{"th":"สนามกีฬากลาง 700 ปี","en":"700th Anniversary Sports Complex"}},
    {"id":"ven_004","address":"227 Phaya Thai Rd","cityCode":"BANGKOK","provinceCode":"BKK","names":{"th":"สนามกีฬาในร่ม โรงเรียนเตรียมอุดมศึกษา","en":"Triam Udom Indoor Court"}},
  ],
} as const

/** The join rows between them: rosters, registrations, guardians, follows. */
export const SEED_RELATIONSHIPS = {
  eventCoOrganizers: [
    {"eventId":"evt_001","userId":"usr_org_002","addedAt":"2026-04-05","statusCode":"ACCEPTED"},

    {"eventId":"evt_002","userId":"usr_org_001","addedAt":"2026-08-20","statusCode":"PENDING"},
  ],
  eventPlayers: [
    {"eventId":"evt_003","playerId":"ply_001","registeredAt":"2026-03-20"},
    {"eventId":"evt_003","playerId":"ply_004","registeredAt":"2026-03-22"},
    {"eventId":"evt_003","playerId":"ply_006","registeredAt":"2026-03-25"},
    {"eventId":"evt_004","playerId":"ply_001","registeredAt":"2026-07-10"},
    {"eventId":"evt_004","playerId":"ply_004","registeredAt":"2026-07-12"},
  ],
  eventTeams: [
    {"eventId":"evt_001","teamId":"team_001","divisionId":"div_001","registeredAt":"2026-04-01"},
    {"eventId":"evt_001","teamId":"team_003","divisionId":"div_001","registeredAt":"2026-04-02"},
    {"eventId":"evt_001","teamId":"team_004","divisionId":"div_002","registeredAt":"2026-04-03"},
    {"eventId":"evt_002","teamId":"team_001","divisionId":"div_001","registeredAt":"2026-04-15"},
    {"eventId":"evt_002","teamId":"team_002","divisionId":"div_004","registeredAt":"2026-04-16"},
    {"eventId":"evt_002","teamId":"team_004","divisionId":"div_002","registeredAt":"2026-04-17"},
    // The league's second U16 boys' team — without an opponent in its division,
    // team_001 would have nobody to play and the games below could not exist.
    {"eventId":"evt_002","teamId":"team_003","divisionId":"div_001","registeredAt":"2026-04-18"},
    {"eventId":"evt_004","teamId":"team_001","divisionId":"div_001","registeredAt":"2026-07-01"},
    {"eventId":"evt_004","teamId":"team_002","divisionId":"div_004","registeredAt":"2026-07-02"},

    {"eventId":"evt_002","teamId":"team_005","divisionId":"div_001","registeredAt":"2026-04-20"},
    {"eventId":"evt_002","teamId":"team_006","divisionId":"div_001","registeredAt":"2026-04-20"},
    {"eventId":"evt_002","teamId":"team_007","divisionId":"div_001","registeredAt":"2026-04-20"},
    {"eventId":"evt_002","teamId":"team_008","divisionId":"div_001","registeredAt":"2026-04-20"},
    {"eventId":"evt_002","teamId":"team_009","divisionId":"div_004","registeredAt":"2026-04-20"},
    {"eventId":"evt_002","teamId":"team_010","divisionId":"div_004","registeredAt":"2026-04-20"},
    {"eventId":"evt_002","teamId":"team_011","divisionId":"div_004","registeredAt":"2026-04-20"},
    {"eventId":"evt_002","teamId":"team_012","divisionId":"div_002","registeredAt":"2026-04-20"},
    {"eventId":"evt_002","teamId":"team_013","divisionId":"div_002","registeredAt":"2026-04-20"},
    {"eventId":"evt_002","teamId":"team_014","divisionId":"div_002","registeredAt":"2026-04-20"},
    {"eventId":"evt_002","teamId":"team_015","divisionId":"div_002","registeredAt":"2026-04-20"},
  ],
  eventVenues: [
    {"eventId":"evt_001","venueId":"ven_002","isPrimary":true},
    {"eventId":"evt_001","venueId":"ven_001","isPrimary":false},
    {"eventId":"evt_002","venueId":"ven_001","isPrimary":true},
    {"eventId":"evt_003","venueId":"ven_003","isPrimary":true},
    {"eventId":"evt_004","venueId":"ven_002","isPrimary":true},
  ],
  /**
   * Which referee is on which game.
   *
   * This is what `GAME_REFEREE` reads, and the reason it exists: `ENTER_SCORES`
   * used to be granted to `ANY_REFEREE`, the platform role, so every referee
   * could enter a score for every game in every event. Adisorn is on the two
   * Bangkok games; Waraporn has the September fixture and no others.
   */
  gameReferees: [
    {"gameId":"gam_001","userId":"usr_referee_001"},
    {"gameId":"gam_002","userId":"usr_referee_001"},
    {"gameId":"gam_003","userId":"usr_referee_002"},

    {"gameId":"gam_004","userId":"usr_referee_001"},
    {"gameId":"gam_005","userId":"usr_referee_002"},
    {"gameId":"gam_006","userId":"usr_referee_002"},
    {"gameId":"gam_007","userId":"usr_referee_002"},
    {"gameId":"gam_008","userId":"usr_referee_001"},
    {"gameId":"gam_009","userId":"usr_referee_002"},
    {"gameId":"gam_010","userId":"usr_referee_002"},
    {"gameId":"gam_011","userId":"usr_referee_001"},
    {"gameId":"gam_012","userId":"usr_referee_002"},
    {"gameId":"gam_013","userId":"usr_referee_001"},
    {"gameId":"gam_014","userId":"usr_referee_001"},
    {"gameId":"gam_015","userId":"usr_referee_001"},
    {"gameId":"gam_016","userId":"usr_referee_002"},
    {"gameId":"gam_017","userId":"usr_referee_002"},
    {"gameId":"gam_018","userId":"usr_referee_002"},
    {"gameId":"gam_019","userId":"usr_referee_002"},
    {"gameId":"gam_020","userId":"usr_referee_002"},
    {"gameId":"gam_021","userId":"usr_referee_001"},
    {"gameId":"gam_022","userId":"usr_referee_002"},
    {"gameId":"gam_023","userId":"usr_referee_001"},
    {"gameId":"gam_024","userId":"usr_referee_002"},
    {"gameId":"gam_025","userId":"usr_referee_002"},
    {"gameId":"gam_026","userId":"usr_referee_001"},
    {"gameId":"gam_027","userId":"usr_referee_001"},
    {"gameId":"gam_028","userId":"usr_referee_001"},
    {"gameId":"gam_029","userId":"usr_referee_002"},
  ],
  guardians: [
    {"userId":"usr_spectator_001","playerId":"ply_001","guardianTypeCode":"PARENT"},

    {"playerId":"ply_002","userId":"usr_spectator_001","guardianTypeCode":"GRANDPARENT"},
    {"playerId":"ply_003","userId":"usr_spectator_001","guardianTypeCode":"LEGAL_GUARDIAN"},
    {"playerId":"ply_006","userId":"usr_spectator_001","guardianTypeCode":"OTHER"},
  ],
  orgMembers: [
    {"orgId":"org_001","userId":"usr_org_001","orgRoleCode":"OWNER"},
    {"orgId":"org_001","userId":"usr_coach_001","orgRoleCode":"ADMIN"},
    {"orgId":"org_002","userId":"usr_org_002","orgRoleCode":"MEMBER"},
  ],
  playerTeams: [
    {"playerId":"ply_001","teamId":"team_001","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_001","teamId":"team_004","fromDate":"2026-03-01","toDate":null},
    {"playerId":"ply_002","teamId":"team_001","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_003","teamId":"team_001","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_004","teamId":"team_002","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_005","teamId":"team_002","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_006","teamId":"team_003","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_007","teamId":"team_003","fromDate":"2026-01-01","toDate":null},

    {"playerId":"ply_008","teamId":"team_001","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_009","teamId":"team_001","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_010","teamId":"team_001","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_011","teamId":"team_001","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_012","teamId":"team_001","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_013","teamId":"team_005","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_014","teamId":"team_005","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_015","teamId":"team_005","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_016","teamId":"team_005","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_017","teamId":"team_005","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_018","teamId":"team_005","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_019","teamId":"team_005","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_020","teamId":"team_005","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_021","teamId":"team_006","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_022","teamId":"team_006","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_023","teamId":"team_006","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_024","teamId":"team_006","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_025","teamId":"team_006","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_026","teamId":"team_006","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_027","teamId":"team_006","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_028","teamId":"team_006","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_029","teamId":"team_007","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_030","teamId":"team_007","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_031","teamId":"team_007","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_032","teamId":"team_007","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_033","teamId":"team_007","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_034","teamId":"team_007","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_035","teamId":"team_007","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_036","teamId":"team_007","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_037","teamId":"team_008","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_038","teamId":"team_008","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_039","teamId":"team_008","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_040","teamId":"team_008","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_041","teamId":"team_008","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_042","teamId":"team_008","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_043","teamId":"team_008","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_044","teamId":"team_008","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_045","teamId":"team_003","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_046","teamId":"team_003","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_047","teamId":"team_003","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_048","teamId":"team_003","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_049","teamId":"team_003","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_050","teamId":"team_003","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_051","teamId":"team_002","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_052","teamId":"team_002","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_053","teamId":"team_002","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_054","teamId":"team_002","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_055","teamId":"team_002","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_056","teamId":"team_002","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_057","teamId":"team_009","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_058","teamId":"team_009","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_059","teamId":"team_009","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_060","teamId":"team_009","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_061","teamId":"team_009","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_062","teamId":"team_009","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_063","teamId":"team_009","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_064","teamId":"team_009","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_065","teamId":"team_010","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_066","teamId":"team_010","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_067","teamId":"team_010","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_068","teamId":"team_010","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_069","teamId":"team_010","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_070","teamId":"team_010","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_071","teamId":"team_010","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_072","teamId":"team_010","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_073","teamId":"team_011","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_074","teamId":"team_011","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_075","teamId":"team_011","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_076","teamId":"team_011","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_077","teamId":"team_011","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_078","teamId":"team_011","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_079","teamId":"team_011","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_080","teamId":"team_011","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_081","teamId":"team_004","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_082","teamId":"team_004","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_083","teamId":"team_004","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_084","teamId":"team_004","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_085","teamId":"team_004","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_086","teamId":"team_004","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_087","teamId":"team_004","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_088","teamId":"team_012","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_089","teamId":"team_012","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_090","teamId":"team_012","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_091","teamId":"team_012","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_092","teamId":"team_012","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_093","teamId":"team_012","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_094","teamId":"team_012","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_095","teamId":"team_012","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_096","teamId":"team_013","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_097","teamId":"team_013","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_098","teamId":"team_013","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_099","teamId":"team_013","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_100","teamId":"team_013","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_101","teamId":"team_013","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_102","teamId":"team_013","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_103","teamId":"team_013","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_104","teamId":"team_014","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_105","teamId":"team_014","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_106","teamId":"team_014","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_107","teamId":"team_014","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_108","teamId":"team_014","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_109","teamId":"team_014","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_110","teamId":"team_014","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_111","teamId":"team_014","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_112","teamId":"team_015","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_113","teamId":"team_015","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_114","teamId":"team_015","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_115","teamId":"team_015","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_116","teamId":"team_015","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_117","teamId":"team_015","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_118","teamId":"team_015","fromDate":"2026-01-01","toDate":null},
    {"playerId":"ply_119","teamId":"team_015","fromDate":"2026-01-01","toDate":null},
  ],
  subscriptions: [
    {"userId":"usr_spectator_001","objectTypeCode":"TEAM","objectId":"team_002","subscribedAt":"2026-04-15"},
    {"userId":"usr_player_001","objectTypeCode":"TEAM","objectId":"team_002","subscribedAt":"2026-03-20"},
    {"userId":"usr_coach_001","objectTypeCode":"EVENT","objectId":"evt_001","subscribedAt":"2026-04-01"},
    {"userId":"usr_admin_001","objectTypeCode":"PLAYER","objectId":"ply_004","subscribedAt":"2026-04-10"},

    {"userId":"usr_spectator_001","objectTypeCode":"TEAM","objectId":"team_001","subscribedAt":"2026-05-02"},
    {"userId":"usr_spectator_001","objectTypeCode":"EVENT","objectId":"evt_002","subscribedAt":"2026-05-02"},
    {"userId":"usr_coach_001","objectTypeCode":"TEAM","objectId":"team_003","subscribedAt":"2026-05-10"},
    {"userId":"usr_player_001","objectTypeCode":"EVENT","objectId":"evt_002","subscribedAt":"2026-05-11"},
  ],
  teamCoaches: [
    {"teamId":"team_001","userId":"usr_coach_001","coachRoleCode":"HEAD"},
    {"teamId":"team_001","userId":"usr_coach_002","coachRoleCode":"ASSISTANT"},
    {"teamId":"team_002","userId":"usr_coach_002","coachRoleCode":"HEAD"},
    {"teamId":"team_003","userId":"usr_coach_003","coachRoleCode":"HEAD"},
    {"teamId":"team_004","userId":"usr_coach_001","coachRoleCode":"HEAD"},
    {"teamId":"team_002","userId":"usr_coach_003","coachRoleCode":"MANAGER"},
  ],
  userNotificationChannels: [
    {"userId":"usr_admin_001","channelCode":"EMAIL","address":"admin@remysport.test","addressLabel":"primary","isEnabled":true,"verifiedAt":"2026-01-15"},
    {"userId":"usr_admin_001","channelCode":"LINE","address":"remy_admin","addressLabel":"primary","isEnabled":true,"verifiedAt":"2026-01-15"},
    {"userId":"usr_org_001","channelCode":"LINE","address":"somchai_ad","addressLabel":"primary","isEnabled":true,"verifiedAt":"2026-02-10"},
    {"userId":"usr_org_001","channelCode":"EMAIL","address":"somchai.p@assumption.test","addressLabel":"primary","isEnabled":true,"verifiedAt":"2026-02-10"},
    {"userId":"usr_coach_001","channelCode":"LINE","address":"coach_wichai","addressLabel":"primary","isEnabled":true,"verifiedAt":"2026-03-01"},
    {"userId":"usr_coach_001","channelCode":"EMAIL","address":"wichai.s@assumption.test","addressLabel":"primary","isEnabled":false,"verifiedAt":"2026-03-01"},
    {"userId":"usr_player_001","channelCode":"LINE","address":"thanakorn_b","addressLabel":"primary","isEnabled":true,"verifiedAt":"2026-03-15"},
    {"userId":"usr_player_002","channelCode":"LINE","address":"kanya_g","addressLabel":"primary","isEnabled":true,"verifiedAt":"2026-03-20"},
    {"userId":"usr_spectator_001","channelCode":"LINE","address":"pim_mom","addressLabel":"primary","isEnabled":true,"verifiedAt":"2026-04-01"},
    {"userId":"usr_spectator_001","channelCode":"LINE","address":"suksai_family_group","addressLabel":"family_group","isEnabled":true,"verifiedAt":"2026-04-05"},
    {"userId":"usr_spectator_001","channelCode":"EMAIL","address":"pim.s@example.test","addressLabel":"primary","isEnabled":true,"verifiedAt":"2026-04-01"},
    {"userId":"usr_referee_001","channelCode":"LINE","address":"ref_adisorn","addressLabel":"primary","isEnabled":true,"verifiedAt":"2026-03-10"},
    {"userId":"usr_referee_002","channelCode":"LINE","address":"ref_waraporn","addressLabel":"primary","isEnabled":true,"verifiedAt":null},

    {"userId":"usr_spectator_001","channelCode":"SMS","address":"+66812340031","addressLabel":"mobile","isEnabled":true,"verifiedAt":"2026-04-12"},
    {"userId":"usr_coach_002","channelCode":"IN_APP","address":"usr_coach_002","addressLabel":"in-app","isEnabled":true,"verifiedAt":"2026-03-05"},
  ],
  userNotificationPreferences: [
    {"userId":"usr_spectator_001","notificationTypeCode":"SCORE_UPDATE","channelCode":"LINE","isEnabled":true},
    {"userId":"usr_spectator_001","notificationTypeCode":"SCORE_UPDATE","channelCode":"EMAIL","isEnabled":false},
    {"userId":"usr_spectator_001","notificationTypeCode":"WEEKLY_DIGEST","channelCode":"LINE","isEnabled":false},
    {"userId":"usr_spectator_001","notificationTypeCode":"WEEKLY_DIGEST","channelCode":"EMAIL","isEnabled":true},
    {"userId":"usr_coach_001","notificationTypeCode":"APPROVAL_REQUEST","channelCode":"LINE","isEnabled":true},
    {"userId":"usr_coach_001","notificationTypeCode":"ROSTER_CHANGE","channelCode":"LINE","isEnabled":true},
    {"userId":"usr_player_001","notificationTypeCode":"MATCH_START","channelCode":"LINE","isEnabled":true},
    {"userId":"usr_player_001","notificationTypeCode":"DAILY_DIGEST","channelCode":"LINE","isEnabled":false},

    {"userId":"usr_spectator_001","notificationTypeCode":"MATCH_END","channelCode":"LINE","isEnabled":true},
    {"userId":"usr_spectator_001","notificationTypeCode":"EVENT_REMINDER","channelCode":"EMAIL","isEnabled":true},
    {"userId":"usr_player_001","notificationTypeCode":"EVENT_CREATED","channelCode":"LINE","isEnabled":false},
    {"userId":"usr_coach_001","notificationTypeCode":"REGISTRATION_OPEN","channelCode":"EMAIL","isEnabled":true},
    {"userId":"usr_coach_001","notificationTypeCode":"REGISTRATION_CLOSING","channelCode":"EMAIL","isEnabled":true},
    {"userId":"usr_org_001","notificationTypeCode":"ANNOUNCEMENT","channelCode":"EMAIL","isEnabled":true},
    {"userId":"usr_org_002","notificationTypeCode":"APPROVAL_GRANTED","channelCode":"LINE","isEnabled":true},
    {"userId":"usr_org_002","notificationTypeCode":"INVITATION","channelCode":"EMAIL","isEnabled":true},
  ],
} as const
