/**
 * Emit the seed as SQL, so a database can be seeded without a running Worker.
 *
 * The vocabularies already work this way: `mise run domain:generate` turns the
 * PO's fixtures into migration 0009, and any database applies it offline and
 * deterministically. The *entities* — users, orgs, teams, memberships — did
 * not. They went through `POST /api/seed`, which calls Better Auth's
 * `createUser` per user over HTTP.
 *
 * That single inconsistency is behind most of this repo's test flakiness. An
 * HTTP seed needs a server, so every spec has to share one database and one set
 * of actors, and Better Auth invalidates an OTP the moment a newer one is
 * requested for the same address — so two specs signing in as the same person
 * make one of them fail. Chaining specs, allocating actors and tuning worker
 * counts all treat that symptom.
 *
 * As SQL it is data, not a runtime operation: every test file can apply it to
 * its own database, in milliseconds, with no server and no shared state.
 *
 * Two details make this possible rather than a fork of Better Auth's logic:
 *
 *   - Nothing here needs a password. `emailAndPassword` is off (ADR 012), and
 *     `account.password` is nullable — these accounts sign in by emailed code.
 *   - `account.issuer` must be `local:credential`. Migration 0007 established
 *     that; 1.7 matches `sign-in/email` on it, and a row without it fails with
 *     "User not found" while /api/seed still reports the user as existing.
 *
 * Ids are the fixtures' own (`usr_admin_001`, `org_001`), so a row is traceable
 * to the PO's data and the same every run. Better Auth does not mind what the
 * id is, only that the rows are well formed.
 */
import { writeFileSync } from "fs"
import { resolve } from "path"
import { SEED_ENTITIES } from "../src/db/seed-data"

const ROOT = resolve(import.meta.dir, "..")

/** SQLite string literal. */
const q = (v: string | null | undefined) =>
  v === null || v === undefined ? "NULL" : `'${v.replace(/'/g, "''")}'`

const json = (v: unknown) => q(JSON.stringify(v))

/** Fixed, so a seeded database is byte-identical between runs. */
const AT = 1_767_225_600_000 // 2026-01-01T00:00:00Z

/**
 * Who belongs to which organisation.
 *
 * Mirrors the MEMBERSHIPS list in src/routes/seed.ts. It is written out in both
 * places today because the PO's fixtures do not yet model membership — when
 * `data/seed/relationships/` grows one, both should read it instead.
 */
const MEMBERSHIPS = [
  { userId: "usr_coach_001", orgId: "org_001", role: "admin" },
  { userId: "usr_org_002", orgId: "org_002", role: "member" },
]

const lines: string[] = [
  "-- GENERATED by `mise run seed:sql` — do not edit.",
  "--",
  "-- The Product Owner's people, schools and teams, as data rather than as an",
  "-- HTTP call. See scripts/seed-sql.ts for why that distinction matters.",
  "",
]

lines.push("-- Users. `role` is the platform role; `biz_id` bridges to the fixtures.")
for (const u of SEED_ENTITIES.users) {
  lines.push(
    `INSERT OR IGNORE INTO user (id, name, email, email_verified, created_at, updated_at, role, biz_id) VALUES ` +
      `(${q(u.id)}, ${q(u.names.en)}, ${q(u.email)}, 1, ${AT}, ${AT}, ${q(u.roleCode.toLowerCase())}, ${q(u.id)});`,
  )
  // One credential account per user, with the issuer 1.7 matches sign-in on.
  lines.push(
    `INSERT OR IGNORE INTO account (id, issuer, account_id, provider_id, user_id, created_at, updated_at) VALUES ` +
      `(${q(`acc_${u.id}`)}, 'local:credential', ${q(u.id)}, 'credential', ${q(u.id)}, ${AT}, ${AT});`,
  )
}

lines.push("", "-- Organisations. Better Auth's table; the extra columns are additionalFields.")
for (const o of SEED_ENTITIES.orgs) {
  lines.push(
    `INSERT OR IGNORE INTO organization (id, name, slug, created_at, names, org_type_code, city_code, province_code) VALUES ` +
      `(${q(o.id)}, ${q(o.names.en)}, ${q(o.slug)}, ${AT}, ${json(o.names)}, ${q(o.orgTypeCode)}, ${q(o.cityCode)}, ${q(o.provinceCode)});`,
  )
}

lines.push("", "-- Memberships — who may write for which school (ADR 009).")
for (const m of MEMBERSHIPS) {
  lines.push(
    `INSERT OR IGNORE INTO member (id, organization_id, user_id, role, created_at) VALUES ` +
      `(${q(`mem_${m.userId}`)}, ${q(m.orgId)}, ${q(m.userId)}, ${q(m.role)}, ${AT});`,
  )
}

lines.push("", "-- Rosters. `name` is the English pivot beside the locale-keyed `names`.")
for (const t of SEED_ENTITIES.teams) {
  lines.push(
    `INSERT OR IGNORE INTO team (id, name, names, org_id, age_group_code, gender_code, created_at, updated_at) VALUES ` +
      `(${q(t.id)}, ${q(t.names.en)}, ${json(t.names)}, ${q(t.orgId)}, ${q(t.ageGroupCode)}, ${q(t.genderCode)}, ${AT}, ${AT});`,
  )
}

lines.push("", "-- Events. `created_by` is the organiser (canonical `organizer_user_id`).")
for (const e of SEED_ENTITIES.events) {
  lines.push(
    `INSERT OR IGNORE INTO event (id, name, names, type_code, format_code, start_date, end_date, city_code, province_code, is_fiba_certified, created_by, created_at, updated_at) VALUES ` +
      `(${q(e.id)}, ${q(e.names.en)}, ${json(e.names)}, ${q(e.typeCode)}, ${q(e.formatCode)}, ${q(e.startDate)}, ${q(e.endDate)}, ${q(e.cityCode)}, ${q(e.provinceCode)}, ${e.isFibaCertified ? 1 : 0}, ${q(e.organizerUserId)}, ${AT}, ${AT});`,
  )
}

writeFileSync(resolve(ROOT, "src/db/seed.sql"), lines.join("\n") + "\n")
console.log(
  `seed.sql: ${SEED_ENTITIES.users.length} users, ${SEED_ENTITIES.orgs.length} orgs, ` +
    `${MEMBERSHIPS.length} memberships, ${SEED_ENTITIES.teams.length} teams, ` +
    `${SEED_ENTITIES.events.length} events`,
)
