/**
 * Emit the seed as SQL, so a database can be seeded without a running Worker.
 *
 * The vocabularies already work this way: `mise run domain:sync` turns the
 * PO's fixtures into migration 0009, and any database applies it offline and
 * deterministically. The *entities* — users, orgs, teams, players, the join
 * tables — did not. They went through `POST /api/seed`, which called Better
 * Auth's `createUser` and `createOrganization` per row over HTTP.
 *
 * That single inconsistency is behind most of this repo's test flakiness. An
 * HTTP seed needs a server, so every spec has to share one database and one set
 * of actors, and Better Auth invalidates an OTP the moment a newer one is
 * requested for the same address — so two specs signing in as the same person
 * make one of them fail. Chaining specs, allocating actors and tuning worker
 * counts all treat that symptom.
 *
 * As SQL it is data, not a runtime operation: every test file can apply it to
 * its own database, in milliseconds, with no server and no shared state.
 * `/api/seed` now executes this file rather than reimplementing it, so there is
 * one definition of what "seeded" means and two callers.
 *
 * Two details make this possible rather than a fork of Better Auth's logic:
 *
 *   - Nothing here needs a password. `emailAndPassword` is off, and
 *     `account.password` is nullable — these accounts sign in by emailed code.
 *   - `account.issuer` must be `local:credential`. Migration 0007 established
 *     that; 1.7 matches `sign-in/email` on it, and a row without it fails with
 *     "User not found" while the seed still reports the user as created.
 *
 * Ids are the fixtures' own (`usr_admin_001`, `org_001`) rather than generated,
 * which is what removed the `biz_id`/`slug` translation the route used to carry.
 * Better Auth does not mind what an id is, only that the rows are well formed.
 */
import { writeFileSync } from "fs"
import { resolve } from "path"
import { getTableColumns, getTableName } from "drizzle-orm"
import type { SQLiteTable } from "drizzle-orm/sqlite-core"
import { FIXTURE_TABLES } from "../src/db/fixtures-schema"
import { VOCABULARY_TABLES } from "../src/db/vocabularies-schema"
import { VOCABULARY } from "../src/domain/vocabularies"
import * as schema from "../src/db/schema"
import { SEED_ENTITIES, SEED_RELATIONSHIPS } from "../src/domain/model/entities"
import { clean, pivot } from "../src/domain/names"
import { STORED_ROLE } from "../src/domain/vocabularies"
import type { Names } from "../src/domain/names"

const ROOT = resolve(import.meta.dir, "..")

/** SQLite string literal. */
const q = (v: string | null | undefined) =>
  v === null || v === undefined ? "NULL" : `'${v.replace(/'/g, "''")}'`

/**
 * A fixture value as SQL.
 *
 * `clean()` on the way in, because the route applied it too and it orders the
 * keys by LOCALES — a `names` column written `{"th":…,"en":…}` by one path and
 * `{"en":…,"th":…}` by the other holds different bytes for the same name.
 */
const lit = (v: unknown): string => {
  if (v === null || v === undefined) return "NULL"
  if (v instanceof Date) return String(v.getTime())
  if (typeof v === "boolean") return v ? "1" : "0"
  if (typeof v === "number") return String(v)
  if (typeof v === "object") return q(JSON.stringify(clean(v as Names)))
  return q(String(v))
}

const json = (v: Names) => q(JSON.stringify(clean(v)))

/** Fixed, so a seeded database is byte-identical between runs. */
const AT = 1_767_225_600_000 // 2026-01-01T00:00:00Z


const lines: string[] = [
  "-- GENERATED by `mise run seed:sql` — do not edit.",
  "--",
  "-- The Product Owner's model, as data rather than as an HTTP call. Applied by",
  "-- the worker tests directly and by POST /api/seed at runtime, so both get the",
  "-- same database. See scripts/seed-sql.ts for why that distinction matters.",
  "",
  "-- The whole file is one transaction, so foreign keys are checked once at the",
  "-- end rather than statement by statement. Vocabularies reference each other —",
  "-- a relation names an object type, a city names a province — and ordering",
  "-- twenty-one of them by dependency would be a second model of the same",
  "-- references the columns already declare.",
  "PRAGMA defer_foreign_keys = true;",
  "",
]

/**
 * One row, as an INSERT, with the column names taken from the drizzle table.
 *
 * The six tables below used to have their column lists typed out in the SQL
 * string — sixty-odd names that nothing checked. Renaming `event.created_by` to
 * `organizer_user_id` in migration 0016 meant editing one of those strings by
 * hand, and getting it wrong would have produced a seed that failed at runtime
 * or, worse, wrote to the wrong column.
 *
 * `$inferInsert` at each call site is what makes that a compile error instead:
 * the row is typed against the table, so a renamed or removed column stops the
 * build here rather than surfacing as a broken database later.
 */
function insertOf<T extends SQLiteTable>(
  table: T,
  row: Record<string, unknown>,
  /**
   * `upsertOn` names the conflict column. Without it the statement is
   * `INSERT OR IGNORE`, which is right for rows that only ever need to exist —
   * and wrong for any row the model later gives a new column, because IGNORE
   * cannot repair what is already there.
   *
   * That is not hypothetical. `status_code` arrived in migration 0008 and the
   * generator writes it, but every user row predating it kept a null: on the
   * development database 15 of 17 users had no lifecycle status at all,
   * including both referees, so `PENDING_APPROVAL` did not exist anywhere and
   * the approval console had nothing to show. Re-seeding never fixed it and
   * never said why.
   */
  opts: { upsertOn?: string } = {},
): string {
  const cols = getTableColumns(table)
  const present = Object.keys(cols).filter((k) => k in row)
  const head =
    `INSERT INTO ${getTableName(table)} ` +
    `(${present.map((k) => cols[k]!.name).join(", ")}) VALUES ` +
    `(${present.map((k) => lit(row[k])).join(", ")})`

  const key = opts.upsertOn
  if (!key) return `INSERT OR IGNORE${head.slice("INSERT".length)};`

  // Update in place rather than replace: the key is a foreign key, and
  // INSERT OR REPLACE deletes the row first, which would take its children with
  // it or fail outright.
  const set = present
    .filter((k) => cols[k]!.name !== key)
    .map((k) => `${cols[k]!.name} = excluded.${cols[k]!.name}`)
    .join(", ")
  return `${head} ON CONFLICT(${key}) DO UPDATE SET ${set};`
}

/**
 * The controlled vocabularies, first — everything below has a foreign key into
 * one of them.
 *
 * These lived in migration 0009, emitted whole on every run, which is what made
 * a vocabulary impossible to rename: regenerating rewrote a migration deployed
 * databases had already applied. Schema is drizzle-kit's job now and data is
 * this file's, so a vocabulary that gains, loses or renames a row is a re-seed
 * rather than a migration.
 */
let vocabRows = 0
for (const [name, table] of Object.entries(VOCABULARY_TABLES) as [string, SQLiteTable][]) {
  const rows = (VOCABULARY as Record<string, readonly Record<string, unknown>[]>)[name]
  if (!rows?.length) continue
  lines.push("", `-- ${name}`)
  for (const [i, row] of rows.entries()) {
    // `sort` is the fixtures' own order, which is how /api/reference returns
    // them — a vocabulary the PO ordered deliberately must not come back
    // alphabetical.
    // The `*_en` pivots are columns in the database and JSON keys in the
    // compiled constants, so they have to be materialised back out. Omitting
    // them is not an error you get told about: they are NOT NULL, and
    // `INSERT OR IGNORE` swallows a NOT NULL violation exactly as quietly as a
    // duplicate — twenty-one vocabularies silently inserted nothing.
    // The model spells its keys exactly as drizzle names its columns, which is
    // what lets this loop be a straight copy. A key that did not match would be
    // a column left out of the INSERT, and `INSERT OR IGNORE` reports that as
    // nothing at all.
    const values: Record<string, unknown> = { sort: i + 1 }
    for (const [key, v] of Object.entries(row)) {
      values[key] = v
      // Every locale-keyed JSON column has a NOT NULL `*_en` pivot beside it.
      if (v && typeof v === "object") values[`${key.replace(/s$/, "")}En`] = pivot(v as Names) ?? ""
    }
    // Vocabularies upsert; everything below does not.
    //
    // The PO owns these absolutely — a renamed city is a correction, and with
    // INSERT OR IGNORE no database that had already been seeded would ever see
    // it. Entities are different: an event's name can be edited in the product,
    // and re-seeding must not overwrite what somebody changed.
    lines.push(insertOf(table, values, { upsertOn: "code" }))
    vocabRows++
  }
}

lines.push(
  "",
  "-- Users. `role` is the platform role; `biz_id` bridges to the fixtures.",
  "-- `names`, `locale_code` and `status_code` are the model's own, and were",
  "-- dropped here until migration 0008 gave them columns.",
)
for (const u of SEED_ENTITIES.users) {
  lines.push(
    insertOf(
      schema.user,
      {
      id: u.id,
      name: pivot(u.names)!,
      email: u.email,
      emailVerified: true,
      createdAt: AT,
      updatedAt: AT,
      role: STORED_ROLE[u.roleCode],
      bizId: u.id,
      // JSON in a text column, not drizzle's `mode: "json"`: this table is
      // generated by Better Auth's CLI from `additionalFields`, which only
      // speaks scalars. The value is the same `Names` shape every other table
      // stores, and src/domain/names.ts reads it either way.
      names: JSON.stringify(u.names),
      localeCode: u.localeCode,
      statusCode: u.statusCode,
      } satisfies Partial<typeof schema.user.$inferInsert>,
      // Upserted, not ignored. These rows outlive the schema — `status_code`
      // was added by migration 0008 and every existing row kept a null,
      // silently, through every re-seed.
      { upsertOn: "id" },
    ),
  )
  // One credential account per user, with the issuer 1.7 matches sign-in on.
  lines.push(
    insertOf(schema.account, {
      id: `acc_${u.id}`,
      issuer: "local:credential",
      accountId: u.id,
      providerId: "credential",
      userId: u.id,
      createdAt: AT,
      updatedAt: AT,
    } satisfies Partial<typeof schema.account.$inferInsert>),
  )
}

// Memberships are not here: `org_member` is a link table like any other now, so
// the generic loop below emits it. It needed a block of its own only while the
// rows went into a table Better Auth owned, with that library's column names and
// its lowercased roles.

/**
 * The fixture tables that must be written BEFORE the entity blocks below.
 *
 * `org` is the whole list, and it has to be: `team.org_id` and
 * `org_member.org_id` are NOT NULL foreign keys into it, and both were being
 * written first. That only ever worked against a database that already had the
 * orgs — every one we had, until staging became the first remote database this
 * repo built from nothing, and `seed:remote` failed on it with
 * FOREIGN KEY constraint failed.
 *
 * Not solved by reordering FIXTURE_TABLES alone: the graph interleaves. `team`
 * needs `org`, while `player` and `eventTeam` need `team`, so neither block can
 * sit wholly before the other. Two passes over the same list is what expresses
 * that. `check:seed:fresh` is what stops it drifting again.
 */
const BEFORE_ENTITIES = new Set(["orgs"])

let fixtureRows = 0

emitFixtures((n) => BEFORE_ENTITIES.has(n))

lines.push("", "-- Rosters. `name` is the English pivot beside the locale-keyed `names`.")
for (const t of SEED_ENTITIES.teams) {
  lines.push(
    insertOf(schema.team, {
      id: t.id,
      name: pivot(t.names)!,
      names: clean(t.names),
      orgId: t.orgId,
      ageGroupCode: t.ageGroupCode,
      genderCode: t.genderCode,
      createdAt: AT,
      updatedAt: AT,
    } satisfies Partial<typeof schema.team.$inferInsert>),
  )
}

lines.push("", "-- Events. `organizer_user_id` is the organiser, named as the fixtures name it.")
for (const e of SEED_ENTITIES.events) {
  lines.push(
    insertOf(schema.event, {
      id: e.id,
      name: pivot(e.names)!,
      names: clean(e.names),
      typeCode: e.typeCode,
      formatCode: e.formatCode,
      timezone: e.timezone,
      startDate: e.startDate,
      endDate: e.endDate,
      cityCode: e.cityCode,
      provinceCode: e.provinceCode,
      isFibaCertified: e.isFibaCertified,
      // The organisation the event belongs to, where the model names one. It had
      // no column until migration 0008, so a page could only say who organises
      // an event and never which school or federation runs it.
      orgId: e.orgId,
      organizerUserId: e.organizerUserId,
      createdAt: AT,
      updatedAt: AT,
    } satisfies Partial<typeof schema.event.$inferInsert>),
  )
}

/**
 * The rest of the model: players, divisions, venues and every join table.
 *
 * Columns come from the drizzle table rather than being typed out, so adding a
 * field upstream cannot leave this emitting an INSERT the schema has outgrown.
 * Only columns the fixture row actually carries are named, which lets column
 * defaults apply to the ones it does not.
 *
 * FIXTURE_TABLES is in dependency order — divisions, players and venues before
 * the joins that point at them — and the four tables above come first because
 * every one of these has a foreign key into them.
 */
function emitFixtures(wanted: (name: string) => boolean): void {
  for (const [name, table] of Object.entries(FIXTURE_TABLES) as [string, SQLiteTable][]) {
    if (!wanted(name)) continue
    const source = SEED_ENTITIES as Record<string, readonly Record<string, unknown>[] | undefined>
    const rows = source[name] ?? (SEED_RELATIONSHIPS as Record<string, readonly Record<string, unknown>[]>)[name]
    if (!rows?.length) continue

    const cols = getTableColumns(table)
    lines.push("", `-- ${name}`)
    for (const row of rows) {
      const present = Object.keys(cols).filter((k) => k in row)
      lines.push(
        `INSERT OR IGNORE INTO ${getTableName(table)} (${present.map((k) => cols[k]!.name).join(", ")}) VALUES ` +
          `(${present.map((k) => lit(row[k])).join(", ")});`,
      )
      fixtureRows++
    }
  }
}

emitFixtures((n) => !BEFORE_ENTITIES.has(n))

/**
 * Which divisions each event runs, derived from the teams already in it.
 *
 * `eventDivision` is this repo's table, not one of the Product Owner's
 * fixtures — the model has no `eventDivisions` list, so the loop above skips it
 * and it is filled here instead.
 *
 * Derived rather than typed out, which is what makes this migration invisible:
 * every seeded event ends up running exactly the divisions its seeded teams are
 * registered in, so nothing that worked before behaves differently after.
 */
const eventDivisions = new Set(
  SEED_RELATIONSHIPS.eventTeams.map((t) => `${t.eventId}|${t.divisionId}`),
)
lines.push("", "-- eventDivisions (derived from eventTeams — see the note in seed-sql.ts)")
for (const key of [...eventDivisions].sort()) {
  const [eventId, divisionId] = key.split("|") as [string, string]
  lines.push(
    insertOf(schema.eventDivision, { eventId, divisionId } satisfies Partial<
      typeof schema.eventDivision.$inferInsert
    >),
  )
  fixtureRows++
}

writeFileSync(resolve(ROOT, "src/db/seed.sql"), lines.join("\n") + "\n")
console.log(
  `seed.sql: ${SEED_ENTITIES.users.length} users, ${SEED_ENTITIES.orgs.length} orgs, ` +
    `${SEED_RELATIONSHIPS.orgMembers.length} memberships, ${SEED_ENTITIES.teams.length} teams, ` +
    `${SEED_ENTITIES.events.length} events, ${fixtureRows} rows across ` +
    `${Object.keys(FIXTURE_TABLES).length} fixture tables`,
)
