/**
 * Emit the seed as SQL, so a database can be seeded without a running Worker.
 *
 * The vocabularies already work this way: `mise run domain:generate` turns the
 * PO's fixtures into migration 0009, and any database applies it offline and
 * deterministically. The *entities* — users, orgs, teams, players, the join
 * tables — did not. They went through `POST /api/seed`, which called Better
 * Auth's `createUser` and `createOrganization` per row over HTTP.
 *
 * That single inconsistency is behind most of this repo's test flakiness. An
 * HTTP seed needs a server, so every spec has to share one database and one set
 * of actors, and Better Auth invalidates an OTP the moment a newer one is
 * requested for the same address — so two specs signing in as the same person
 * make one of them fail. Chaining specs, allocating actors and tuning worker
 * counts all treat that symptom.
 *
 * As SQL it is data, not a runtime operation: every test file can apply it to
 * its own database, in milliseconds, with no server and no shared state.
 * `/api/seed` now executes this file rather than reimplementing it, so there is
 * one definition of what "seeded" means and two callers.
 *
 * Two details make this possible rather than a fork of Better Auth's logic:
 *
 *   - Nothing here needs a password. `emailAndPassword` is off, and
 *     `account.password` is nullable — these accounts sign in by emailed code.
 *   - `account.issuer` must be `local:credential`. Migration 0007 established
 *     that; 1.7 matches `sign-in/email` on it, and a row without it fails with
 *     "User not found" while the seed still reports the user as created.
 *
 * Ids are the fixtures' own (`usr_admin_001`, `org_001`) rather than generated,
 * which is what removed the `biz_id`/`slug` translation the route used to carry.
 * Better Auth does not mind what an id is, only that the rows are well formed.
 */
import { writeFileSync } from "fs"
import { resolve } from "path"
import { getTableColumns, getTableName } from "drizzle-orm"
import type { SQLiteTable } from "drizzle-orm/sqlite-core"
import { FIXTURE_TABLES } from "../src/db/fixtures-schema"
import { SEED_ENTITIES, SEED_RELATIONSHIPS } from "../src/db/seed-data"
import { clean, pivot } from "../src/domain/names"
import { STORED_ROLE } from "../src/domain/vocabularies"
import type { Names } from "../src/domain/names"

const ROOT = resolve(import.meta.dir, "..")

/** SQLite string literal. */
const q = (v: string | null | undefined) =>
  v === null || v === undefined ? "NULL" : `'${v.replace(/'/g, "''")}'`

/**
 * A fixture value as SQL.
 *
 * `clean()` on the way in, because the route applied it too and it orders the
 * keys by LOCALES — a `names` column written `{"th":…,"en":…}` by one path and
 * `{"en":…,"th":…}` by the other holds different bytes for the same name.
 */
const lit = (v: unknown): string => {
  if (v === null || v === undefined) return "NULL"
  if (typeof v === "boolean") return v ? "1" : "0"
  if (typeof v === "number") return String(v)
  if (typeof v === "object") return q(JSON.stringify(clean(v as Names)))
  return q(String(v))
}

const json = (v: Names) => q(JSON.stringify(clean(v)))

/** Fixed, so a seeded database is byte-identical between runs. */
const AT = 1_767_225_600_000 // 2026-01-01T00:00:00Z

/**
 * Who may act for which organisation.
 *
 * These two rows used to be invented here, because the PO's model declared an
 * `ORG` object type and then attached nothing to it — no relations, no actions —
 * so the app filled the gap itself. They are upstream data now
 * (`links/org_members.jsonl`), and the `ORG_ADMIN`/`ORG_MEMBER` relations derive
 * from the rows this writes.
 *
 * Better Auth owns the `member` table, so its column names are used rather than
 * the fixtures' — the same translation `user` and `organization` already get
 * above. `org_role_code` is lowercased into `role` for the same reason the
 * platform role is: the fixtures say ADMIN, Better Auth stores admin.
 */

const lines: string[] = [
  "-- GENERATED by `mise run seed:sql` — do not edit.",
  "--",
  "-- The Product Owner's model, as data rather than as an HTTP call. Applied by",
  "-- the worker tests directly and by POST /api/seed at runtime, so both get the",
  "-- same database. See scripts/seed-sql.ts for why that distinction matters.",
  "",
]

lines.push("-- Users. `role` is the platform role; `biz_id` bridges to the fixtures.")
for (const u of SEED_ENTITIES.users) {
  lines.push(
    `INSERT OR IGNORE INTO user (id, name, email, email_verified, created_at, updated_at, role, biz_id) VALUES ` +
      `(${q(u.id)}, ${q(pivot(u.names))}, ${q(u.email)}, 1, ${AT}, ${AT}, ${q(STORED_ROLE[u.roleCode])}, ${q(u.id)});`,
  )
  // One credential account per user, with the issuer 1.7 matches sign-in on.
  lines.push(
    `INSERT OR IGNORE INTO account (id, issuer, account_id, provider_id, user_id, created_at, updated_at) VALUES ` +
      `(${q(`acc_${u.id}`)}, 'local:credential', ${q(u.id)}, 'credential', ${q(u.id)}, ${AT}, ${AT});`,
  )
}

lines.push("", "-- Organisations. Better Auth's table; the extra columns are additionalFields.")
for (const o of SEED_ENTITIES.orgs) {
  lines.push(
    `INSERT OR IGNORE INTO organization (id, name, slug, created_at, names, org_type_code, city_code, province_code) VALUES ` +
      `(${q(o.id)}, ${q(pivot(o.names))}, ${q(o.slug)}, ${AT}, ${json(o.names)}, ${q(o.orgTypeCode)}, ${q(o.cityCode)}, ${q(o.provinceCode)});`,
  )
}

lines.push("", "-- Memberships — who may act for which school (biz links/org_members.jsonl).")
for (const m of SEED_RELATIONSHIPS.orgMembers) {
  lines.push(
    `INSERT OR IGNORE INTO member (id, organization_id, user_id, role, created_at) VALUES ` +
      `(${q(`mem_${m.userId}`)}, ${q(m.orgId)}, ${q(m.userId)}, ${q(m.orgRoleCode.toLowerCase())}, ${AT});`,
  )
}

lines.push("", "-- Rosters. `name` is the English pivot beside the locale-keyed `names`.")
for (const t of SEED_ENTITIES.teams) {
  lines.push(
    `INSERT OR IGNORE INTO team (id, name, names, org_id, age_group_code, gender_code, created_at, updated_at) VALUES ` +
      `(${q(t.id)}, ${q(pivot(t.names))}, ${json(t.names)}, ${q(t.orgId)}, ${q(t.ageGroupCode)}, ${q(t.genderCode)}, ${AT}, ${AT});`,
  )
}

lines.push("", "-- Events. `organizer_user_id` is the organiser, named as the fixtures name it.")
for (const e of SEED_ENTITIES.events) {
  lines.push(
    `INSERT OR IGNORE INTO event (id, name, names, type_code, format_code, start_date, end_date, city_code, province_code, is_fiba_certified, organizer_user_id, created_at, updated_at) VALUES ` +
      `(${q(e.id)}, ${q(pivot(e.names))}, ${json(e.names)}, ${q(e.typeCode)}, ${q(e.formatCode)}, ${q(e.startDate)}, ${q(e.endDate)}, ${q(e.cityCode)}, ${q(e.provinceCode)}, ${e.isFibaCertified ? 1 : 0}, ${q(e.organizerUserId)}, ${AT}, ${AT});`,
  )
}

/**
 * The rest of the model: players, divisions, venues and every join table.
 *
 * Columns come from the drizzle table rather than being typed out, so adding a
 * field upstream cannot leave this emitting an INSERT the schema has outgrown.
 * Only columns the fixture row actually carries are named, which lets column
 * defaults apply to the ones it does not.
 *
 * FIXTURE_TABLES is in dependency order — divisions, players and venues before
 * the joins that point at them — and the four tables above come first because
 * every one of these has a foreign key into them.
 */
let fixtureRows = 0
for (const [name, table] of Object.entries(FIXTURE_TABLES) as [string, SQLiteTable][]) {
  const source = SEED_ENTITIES as Record<string, readonly Record<string, unknown>[] | undefined>
  const rows = source[name] ?? (SEED_RELATIONSHIPS as Record<string, readonly Record<string, unknown>[]>)[name]
  if (!rows?.length) continue

  const cols = getTableColumns(table)
  lines.push("", `-- ${name}`)
  for (const row of rows) {
    const present = Object.keys(cols).filter((k) => k in row)
    lines.push(
      `INSERT OR IGNORE INTO ${getTableName(table)} (${present.map((k) => cols[k]!.name).join(", ")}) VALUES ` +
        `(${present.map((k) => lit(row[k])).join(", ")});`,
    )
    fixtureRows++
  }
}

writeFileSync(resolve(ROOT, "src/db/seed.sql"), lines.join("\n") + "\n")
console.log(
  `seed.sql: ${SEED_ENTITIES.users.length} users, ${SEED_ENTITIES.orgs.length} orgs, ` +
    `${SEED_RELATIONSHIPS.orgMembers.length} memberships, ${SEED_ENTITIES.teams.length} teams, ` +
    `${SEED_ENTITIES.events.length} events, ${fixtureRows} rows across ` +
    `${Object.keys(FIXTURE_TABLES).length} fixture tables`,
)
