// GENERATED from docs/matrix.json — do not edit manually.
// Regenerate: mise run matrix:generate

import { createAccessControl } from "better-auth/plugins/access"

export const ac = createAccessControl({
  event       : ["create","read","update","delete"],
  division    : ["create","read","update","delete"],
  registration: ["register-team","register-player","read"],
  team        : ["create","read","update","delete"],
  player      : ["create","read","update"],
  roster      : ["manage"],
  "find-team": ["read"],
  bracket     : ["generate","read"],
  "consolation-bracket": ["generate","read"],
  fixture     : ["generate","read"],
  session     : ["define","read"],
  court       : ["assign","read"],
  score       : ["enter","read"],
  attendance  : ["record","read"],
  "results-archive": ["read"],
  spoiler     : ["toggle","read"],
  standings   : ["read"],
  "player-stats": ["read"],
  "season-records": ["read"],
  "live-scores": ["read"],
  notifications: ["subscribe","read"],
  "live-stream": ["manage","read"],
  "court-status": ["read"],
  "ai-assistant": ["create-event","suggest-bracket","qa"],
  user        : ["manage"],
  moderation  : ["manage"],
})

export const adminRole = ac.newRole({
  event       : ["create","read","update","delete"],
  division    : ["create","read","update","delete"],
  registration: ["register-team","register-player","read"],
  team        : ["create","read","update","delete"],
  player      : ["create","read","update"],
  roster      : ["manage"],
  "find-team": ["read"],
  bracket     : ["generate","read"],
  "consolation-bracket": ["generate","read"],
  fixture     : ["generate","read"],
  session     : ["define","read"],
  court       : ["assign","read"],
  score       : ["enter","read"],
  attendance  : ["record","read"],
  "results-archive": ["read"],
  standings   : ["read"],
  "player-stats": ["read"],
  "season-records": ["read"],
  "live-scores": ["read"],
  "live-stream": ["manage","read"],
  "court-status": ["read"],
  "ai-assistant": ["create-event","suggest-bracket","qa"],
  user        : ["manage"],
  moderation  : ["manage"],
})

export const organizer = ac.newRole({
  event       : ["create","read","update","delete"],
  division    : ["create","read","update","delete"],
  registration: ["read"],
  team        : ["read"],
  player      : ["read"],
  bracket     : ["generate","read"],
  "consolation-bracket": ["generate","read"],
  fixture     : ["generate","read"],
  session     : ["define","read"],
  court       : ["assign","read"],
  score       : ["enter","read"],
  attendance  : ["record","read"],
  "results-archive": ["read"],
  standings   : ["read"],
  "player-stats": ["read"],
  "season-records": ["read"],
  "live-scores": ["read"],
  "live-stream": ["manage","read"],
  "court-status": ["read"],
  "ai-assistant": ["create-event","suggest-bracket","qa"],
})

export const coach = ac.newRole({
  event       : ["read"],
  division    : ["read"],
  registration: ["register-team","read"],
  team        : ["create","read","update"],
  player      : ["create","read","update"],
  roster      : ["manage"],
  bracket     : ["read"],
  "consolation-bracket": ["read"],
  fixture     : ["read"],
  session     : ["read"],
  court       : ["read"],
  score       : ["read"],
  attendance  : ["record","read"],
  "results-archive": ["read"],
  spoiler     : ["toggle","read"],
  standings   : ["read"],
  "player-stats": ["read"],
  "season-records": ["read"],
  "live-scores": ["read"],
  notifications: ["subscribe","read"],
  "live-stream": ["read"],
  "court-status": ["read"],
  "ai-assistant": ["qa"],
})

export const player = ac.newRole({
  event       : ["read"],
  division    : ["read"],
  registration: ["register-player","read"],
  team        : ["read"],
  player      : ["create","read","update"],
  "find-team": ["read"],
  bracket     : ["read"],
  "consolation-bracket": ["read"],
  fixture     : ["read"],
  session     : ["read"],
  court       : ["read"],
  score       : ["read"],
  "results-archive": ["read"],
  spoiler     : ["toggle","read"],
  standings   : ["read"],
  "player-stats": ["read"],
  "season-records": ["read"],
  "live-scores": ["read"],
  notifications: ["subscribe","read"],
  "live-stream": ["read"],
  "court-status": ["read"],
  "ai-assistant": ["qa"],
})

export const spectator = ac.newRole({
  event       : ["read"],
  division    : ["read"],
  registration: ["read"],
  team        : ["read"],
  player      : ["read"],
  bracket     : ["read"],
  "consolation-bracket": ["read"],
  fixture     : ["read"],
  session     : ["read"],
  court       : ["read"],
  score       : ["read"],
  "results-archive": ["read"],
  spoiler     : ["toggle","read"],
  standings   : ["read"],
  "player-stats": ["read"],
  "season-records": ["read"],
  "live-scores": ["read"],
  notifications: ["subscribe","read"],
  "live-stream": ["read"],
  "court-status": ["read"],
  "ai-assistant": ["qa"],
})

export const referee = ac.newRole({
  event       : ["read"],
  division    : ["read"],
  bracket     : ["read"],
  "consolation-bracket": ["read"],
  fixture     : ["read"],
  court       : ["read"],
  score       : ["enter","read"],
  "results-archive": ["read"],
  standings   : ["read"],
  "live-scores": ["read"],
  "court-status": ["read"],
  "ai-assistant": ["qa"],
})

export const roles = {
  admin: adminRole,
  organizer,
  coach,
  player,
  spectator,
  referee,
}
