// GENERATED from docs/matrix.json — do not edit manually.
// Regenerate: mise run matrix:generate

/** Typed matrix data from docs/matrix.json for runtime use. */

export const RESOURCES = ["event","division","registration","team","player","roster","find-team","bracket","consolation-bracket","fixture","session","court","score","attendance","results-archive","spoiler","standings","player-stats","season-records","live-scores","notifications","live-stream","court-status","ai-assistant","user","moderation"] as const
export type Resource = typeof RESOURCES[number]

/** Which event types each resource applies to. */
export const EVENT_TYPE_SCOPE: Record<Resource, string[]> = {
  "event": ["tournament","league","camp","showcase"],
  "division": ["tournament","league","showcase"],
  "registration": ["tournament","league","camp","showcase"],
  "team": ["tournament","league","showcase"],
  "player": ["tournament","league","camp","showcase"],
  "roster": ["tournament","league","showcase"],
  "find-team": ["tournament","league","showcase"],
  "bracket": ["tournament","showcase"],
  "consolation-bracket": ["tournament"],
  "fixture": ["tournament","league"],
  "session": ["camp"],
  "court": ["tournament","league","showcase"],
  "score": ["tournament","league","showcase"],
  "attendance": ["camp"],
  "results-archive": ["tournament","league","showcase"],
  "spoiler": ["tournament","league","showcase"],
  "standings": ["tournament","league"],
  "player-stats": ["tournament","league","showcase"],
  "season-records": ["league"],
  "live-scores": ["tournament","league","showcase"],
  "notifications": ["tournament","league","showcase"],
  "live-stream": ["tournament","league","showcase"],
  "court-status": ["tournament","league","showcase"],
  "ai-assistant": ["tournament","league","camp","showcase"],
  "user": ["tournament","league","camp","showcase"],
  "moderation": ["tournament","league","camp","showcase"],
}

/** API routes for each resource:action. */
export const ROUTE_MAP: Record<string, { method: string; path: string }[]> = {
  "event:create": [{"method":"POST","path":"/api/events"}],
  "event:read": [{"method":"GET","path":"/api/events"}],
  "event:update": [{"method":"PUT","path":"/api/events/{id}"}],
  "event:delete": [{"method":"DELETE","path":"/api/events/{id}"}],
  "division:create": [{"method":"POST","path":"/api/divisions"}],
  "division:read": [{"method":"GET","path":"/api/divisions"}],
  "division:update": [{"method":"PUT","path":"/api/divisions/{id}"}],
  "division:delete": [{"method":"DELETE","path":"/api/divisions/{id}"}],
  "registration:register-team": [{"method":"POST","path":"/api/registrations/team"}],
  "registration:register-player": [{"method":"POST","path":"/api/registrations/player"}],
  "registration:read": [{"method":"GET","path":"/api/registrations"}],
  "team:create": [{"method":"POST","path":"/api/teams"}],
  "team:read": [{"method":"GET","path":"/api/teams"}],
  "team:update": [{"method":"PUT","path":"/api/teams/{id}"}],
  "team:delete": [{"method":"DELETE","path":"/api/teams/{id}"}],
  "player:create": [{"method":"POST","path":"/api/players"}],
  "player:read": [{"method":"GET","path":"/api/players"}],
  "player:update": [{"method":"PUT","path":"/api/players/{id}"}],
  "roster:manage": [{"method":"POST","path":"/api/rosters"},{"method":"DELETE","path":"/api/rosters/{id}"}],
  "find-team:read": [{"method":"GET","path":"/api/find-team"}],
  "bracket:generate": [{"method":"POST","path":"/api/brackets"}],
  "bracket:read": [{"method":"GET","path":"/api/brackets"}],
  "consolation-bracket:generate": [{"method":"POST","path":"/api/consolation-brackets"}],
  "consolation-bracket:read": [{"method":"GET","path":"/api/consolation-brackets"}],
  "fixture:generate": [{"method":"POST","path":"/api/fixtures"},{"method":"POST","path":"/api/matches"}],
  "fixture:read": [{"method":"GET","path":"/api/fixtures"}],
  "session:define": [{"method":"POST","path":"/api/sessions"}],
  "session:read": [{"method":"GET","path":"/api/sessions"}],
  "court:assign": [{"method":"POST","path":"/api/courts"}],
  "court:read": [{"method":"GET","path":"/api/courts"}],
  "score:enter": [{"method":"POST","path":"/api/scores"},{"method":"PUT","path":"/api/matches/{id}/status"}],
  "score:read": [{"method":"GET","path":"/api/scores"}],
  "attendance:record": [{"method":"POST","path":"/api/attendance"}],
  "attendance:read": [{"method":"GET","path":"/api/attendance"}],
  "results-archive:read": [{"method":"GET","path":"/api/results-archive"}],
  "spoiler:toggle": [{"method":"PUT","path":"/api/preferences/spoiler"}],
  "spoiler:read": [{"method":"GET","path":"/api/preferences/spoiler"}],
  "standings:read": [{"method":"GET","path":"/api/standings"}],
  "player-stats:read": [{"method":"GET","path":"/api/player-stats"}],
  "season-records:read": [{"method":"GET","path":"/api/season-records"}],
  "live-scores:read": [{"method":"GET","path":"/api/live-scores"}],
  "notifications:subscribe": [{"method":"POST","path":"/api/notifications/subscribe"}],
  "notifications:read": [{"method":"GET","path":"/api/notifications"}],
  "live-stream:manage": [{"method":"POST","path":"/api/live-streams"}],
  "live-stream:read": [{"method":"GET","path":"/api/live-streams"}],
  "court-status:read": [{"method":"GET","path":"/api/court-status"}],
  "ai-assistant:create-event": [{"method":"POST","path":"/api/ai/create-event"}],
  "ai-assistant:suggest-bracket": [{"method":"POST","path":"/api/ai/suggest-bracket"}],
  "ai-assistant:qa": [{"method":"POST","path":"/api/ai/qa"}],
  "user:manage": [{"method":"GET","path":"/api/users"},{"method":"PUT","path":"/api/users/{id}"}],
  "moderation:manage": [{"method":"GET","path":"/api/moderation"},{"method":"PUT","path":"/api/moderation/{id}"}],
}

/** Public read endpoints (no auth required). */
export const PUBLIC_READS: { method: string; path: string }[] = [
  { method: "GET", path: "/api/events" },
  { method: "GET", path: "/api/divisions" },
  { method: "GET", path: "/api/registrations" },
  { method: "GET", path: "/api/teams" },
  { method: "GET", path: "/api/players" },
  { method: "GET", path: "/api/brackets" },
  { method: "GET", path: "/api/consolation-brackets" },
  { method: "GET", path: "/api/fixtures" },
  { method: "GET", path: "/api/sessions" },
  { method: "GET", path: "/api/courts" },
  { method: "GET", path: "/api/scores" },
  { method: "GET", path: "/api/attendance" },
  { method: "GET", path: "/api/results-archive" },
  { method: "GET", path: "/api/standings" },
  { method: "GET", path: "/api/player-stats" },
  { method: "GET", path: "/api/season-records" },
  { method: "GET", path: "/api/live-scores" },
  { method: "GET", path: "/api/live-streams" },
  { method: "GET", path: "/api/court-status" },
  { method: "GET", path: "/api/match-referees" },
]

/** Implementation status for all resources (including planned/not_started). */
export type ResourceStatus = "implemented" | "planned" | "not_started"
export const RESOURCE_STATUS: Record<string, { status: ResourceStatus; group: string; designFeatures: string[] }> = {
  "event": { status: "implemented", group: "events", designFeatures: ["Browse events","Event detail page","Create event"] },
  "division": { status: "implemented", group: "events", designFeatures: ["Age & gender divisions"] },
  "registration": { status: "implemented", group: "events", designFeatures: ["Register team","Register as player"] },
  "team": { status: "implemented", group: "teams-players", designFeatures: ["Create team profile"] },
  "player": { status: "implemented", group: "teams-players", designFeatures: ["Create player profile"] },
  "roster": { status: "implemented", group: "teams-players", designFeatures: ["Manage roster"] },
  "find-team": { status: "implemented", group: "teams-players", designFeatures: ["Find a team"] },
  "bracket": { status: "implemented", group: "schedules-brackets", designFeatures: ["View bracket","Generate brackets"] },
  "consolation-bracket": { status: "implemented", group: "schedules-brackets", designFeatures: ["Consolation / back draw"] },
  "fixture": { status: "implemented", group: "schedules-brackets", designFeatures: ["View fixture schedule","Generate fixtures"] },
  "session": { status: "implemented", group: "schedules-brackets", designFeatures: ["Define session schedule"] },
  "court": { status: "implemented", group: "schedules-brackets", designFeatures: ["View court assignments","Assign courts"] },
  "score": { status: "implemented", group: "scores-results", designFeatures: ["Enter scores","View game results","Confirm match status","View match status"] },
  "attendance": { status: "implemented", group: "scores-results", designFeatures: ["Record attendance"] },
  "results-archive": { status: "implemented", group: "scores-results", designFeatures: ["View results archive"] },
  "spoiler": { status: "implemented", group: "scores-results", designFeatures: ["Spoiler mode"] },
  "standings": { status: "implemented", group: "rankings-standings", designFeatures: ["View standings table","View rank movement","View rankings history"] },
  "player-stats": { status: "implemented", group: "rankings-standings", designFeatures: ["View player stats"] },
  "season-records": { status: "implemented", group: "rankings-standings", designFeatures: ["View season records"] },
  "live-scores": { status: "implemented", group: "live-realtime", designFeatures: ["Live scores"] },
  "notifications": { status: "implemented", group: "live-realtime", designFeatures: ["Push notifications"] },
  "live-stream": { status: "implemented", group: "live-realtime", designFeatures: ["Live stream links"] },
  "court-status": { status: "implemented", group: "live-realtime", designFeatures: ["Court status board"] },
  "ai-assistant": { status: "implemented", group: "ai-assistant", designFeatures: ["Create event by chat","Bracket suggestions","Q&A"] },
  "user": { status: "implemented", group: "admin", designFeatures: ["Manage all users"] },
  "moderation": { status: "implemented", group: "admin", designFeatures: ["Moderate listings"] },
}
